- run/pdf2john.py
Commit efc315e926f521cc41c002742a994776edbacc1d broke pdf2john.py, at least for the pdf files I'm currently testing, i.e. following format (in hashcat)
-m 10500 = PDF 1.4 - 1.6 (Acrobat 5 - 8)
The signature (which I've investigated here) is: $pdf$2*3*128*
Some example hashes (which currently don't work, but with this pull request should work):
https://mega.co.nz/#!7UABCa5J!t1j7SGclg6UA3X_x1tGpWO7tGiu3D7G7oYBOsSRSUMA
The main problem here is the indentation (which for python is very important, yes sucks).
Greetz from hashcat's dev
philsmd, atom
> pdf2john.py problem, commit efc315e926f521cc41c002742a994776edbacc1d broke it

- run/pdf2john.py
According to the Adobe PDF documentations ( for instance https://wwwimages2.adobe.com/content/dam/Adobe/en/devnet/pdf/pdfs/PDF32000_2008.pdf ) , the /Length attribute in the encryption dictionary was not available/used for PDF documents with a PDF version number < 1.4.
The documentation says: (Optional; PDF 1.4; only if V is 2 or 3) The length of the encryption key, in bits. The value shall be a multiple of 8, in the range 40 to 128. Default value: 40.
Indeed, for PDF versions < 1.4 /Length afaik does never exist and hence the current code fails, generating something like this:
$pdf$1\*2\*\*...  instead of $pdf$1\*2\*40\*...
Hashes without a keysize are currently not acceted neither by jtr, nor by oclHashcat.
Example hashes to test (feel free to share/upload/post them): …
> pdf2john /Encrypt /Length problem for PDF versions 1.1 - 1.3

- run/pdf2john.py
- Fix `AttributeError: 'str' object has no attribute 'decode'` when using python v3.x
- Use basename for pdf2john.py usage instead of full path
> pdf2john: Fix AttributeError

- src/siemens-s7_fmt_plug.c
Fix bug: #1090
update:
According to the valid() function, the hash below can also pass the valid check.
"$siemens-s7$1$599fe00cdb61f76cc6e949162f22c95943468acb$0"
So, there is a bug in get_binary().
line 120: static void get_binary(char *ciphertext)
line 121: {
line 122: static union {
line 123: unsigned char c[BINARY_SIZE];
line 124: ARCH_WORD dummy;
line 125: } buf;
line 126: unsigned char *out = buf.c;
line 127: char *p;
line 128: int i;
line 129: p = strrchr(ciphertext, '$') + 1;
line 130: for (i = 0; i < BINARY_SIZE; i++) {
line 131: out[i] = 
line 132: (atoi16[ARCH_INDEX(p)] << 4) |
line 133: atoi16[ARCH_INDEX(p[1])];
line 134: p += 2;
line 135: }
line 136: 
line 137: return out;
line 138: }
In line 129, p points to "0", and BINARY_SIZE is 20. But in line 132 and 133 it tries 
to …
> Add check for get_binary()

- src/siemens-s7_fmt_plug.c
Add check for hex string and lower case, see #1091 
Add check for outcome field, close #1094
> fix valid() in siemens-s7_fmt_plug.c

- src/7z_fmt_plug.c
The result when p points to different string.
String p points to | Result    
---------------------- | -------------
"0"                       | PASS
""                         | PASS
"."                       | PASS
"1"                       | FAILED
Should "" and "." pass the valid() check?
If they are should not, I guess **the author wants only "0"**?
Am I right?  @kholia
> fix valid bug for 7z_fmt_plug.c

- src/androidfde_fmt_plug.c
$ cat input
$fde$16$04b36d4290b56e0fcca9778b74719ab8$16*b45f0f051f13f84872d1ef1abe0ada59$0f61d28f7466c0435040cc845a67e6734500de15df3ba6f48d2534ca2a7b8f910d7547357e8f1ec7364bab41383f5df9b5fb43fcd4a1e06189ce3c6ba77ec908b066e73a508e201c941fb409e9abdc051c3c052a735b01e56be61efa635e82cbceab18db1ba645b93f7befb83155852f0004a7c7d6800e9fa5f0d3c133dd2496f92110c3cdcfb16dcf57df8de830969e18514a34d4917de14597da19f9f7dc81eca2d7d461c91e0a8aeac06bafe89866d24f2b4991b4295b6277d0ff4ad97f1fa58e20f8a24e2062f84c318eb36cfbb4671117bc3522afcf7737353589cae0dce0d7c3341f457af654543758f3f005bd4d68fa2b35777cb2ea5f8f69c4debcfb1d8b2a601320e4f8621dc6e99434007388bdc0ceebc722f9ed44cbce3914bf144db332276e719f6b48108cde55916d861d19dc8c03ac76a2dad322457073111e441488228f13649073aa3aadfab51dadf89a0827acba284154a9e18d926facef43852a0 …
> fix bug of androidfde_fmt_plug::valid()

- src/blackberry_ES10_fmt_plug.c
There is a bug in src/blackberry_ES10_fmt_plug.c
$ cat format
$bbes10$76BDF6BE760FCF5DEE7B20E27632D1FEDD9D64E1BBCC941F42957E87CBFB96F176324B2E2C71976CEBE67CA6F400F33F001D7453D80F4AF5D80C8A93ED0BA0E6$DB1C19C0$
$ john format
This format can pass the valid(), but in **get_salt()** function, p points **""** which should be **"DB1C19C0"**. So the end of format can not be **'$'**.
```C
static void *get_salt(char *ciphertext)
{
char *p;
static struct custom_salt cs;
memset(&cs, 0, sizeof(cs));
p = strrchr(ciphertext, '$') + 1;
strcpy((char*)cs.salt, p);
return (void *)&cs;
}
```
> fix valid() function in src/blackberry_ES10_fmt_plug.c

- src/mkv.c
This is a bug found by fuzzing the options of John.
$7z$0$19$0$1122$8$d1f50227759415890000000000000000$1412385885$112$112$5e5b8b734adf52a64c541a5a5369023d7cccb78bd910c0092535dfb013a5df84ac692c5311d2e7bbdc580f5b867f7b5dd43830f7b4f37e41c7277e228fb92a6dd854a31646ad117654182253706dae0c069d3f4ce46121d52b6f20741a0bb39fc61113ce14d22f9184adafd6b5333fb1
$ ./configure && make -sj8
$ ./john 7z_fmt --markov::default:
Loaded 1 password hash (7z, 7-Zip [SHA256 AES 32/64])
Will run 8 OpenMP threads
Note: This format may emit false positives, so it will keep trying even after
finding a possible candidate.
**Segmentation fault (core dumped)**
#0  get_markov_options (db=db@entry=0x104a1c0 <database>, mkv_param=0x187d0af "default",
mkv_minlevel=mkv_minlevel@entry=0x7fffb278c0f8, …
> fix segfault: --markov::default:

- src/unicode.c
> report error message and exit when --input-encoding= a long string

- src/7z_fmt_plug.c
1. Remove the useless parameter for sevenzip_decrypt() function
2. Add static to sevenzip_kdf() function
> remove the useless parameter for sevenzip_decrypt() function

- run/ecryptfs2john.py
Since version 105 (See See https://launchpad.net/ecryptfs/+milestone/105) eCryptfs uses a new file version with the salt included in the file. I had the new file version parsing capability to JTR.
> Add eCryptfs file version 2

- run/aix2john.py
- run/bitcoin2john.py
- run/blockchain2john.py
- run/efs2john.py
- run/openssl2john.py
Change deprecated optparse to argparse in:
- aix2john.py
- bitcoin2john.py
- blockchain2john.py
To fix part of this issue:  Python helpers overhaul #1057 
------EDITED----
Added:
- efs2john.py
- openssl2john.py
> Change deprecated optparse to argparse

- src/listconf.c
- src/options.c
- src/recovery.c
1. report glibc version with --list=build-info
2. Add _BSD_SOURCE and _DEFAULT_SOURCE definitions to listconf.c for HAVE_OPENCL (We use setenv() here, but didn't have the feature request definitions...)
3. Fix some memory leaks for ./john --status
4. Report build timestamp with --list=build-info
5. Report MS compiler version with --list=build-info
> A few fixes which might need discussion

- src/pp.c
Close #1242
mpf_div(perc, fpos, count);
Handle the case that `0==count`
> Close #1242

- src/mpz_int128.h
- src/pp.c
Close #1268 
When **GNP** is supported, `mpf_t` is not `double` and it is defined in `gmp.h`.
GMP has the function `mpf_sgn` to check the value of `mpf_t`, and I define one in `mpz_int128.h`
> Fix: 32bit build with GMP fails

- src/ssh2john.c
`OPENSSL_free(data);` is **double free** in the case below:
1. `PEM_read_bio(bp, &nm, &header, &data, &len)`  return true
2. `OPENSSL_free(data)`
3. `PEM_read_bio(bp, &nm, &header, &data, &len)`  return false
4. `goto out;`
5. `OPENSSL_free(data)`
So step 5 double free **data**.
$ ../ssh2john ssh-new-format-1.key
```
! test_ssh/openssh-new-format-keys/ssh-new-format-1.key : input keyfile validation failed
=================================================================
==60725==ERROR: AddressSanitizer: attempting double-free on 0x61e00000f080 in thread T0:
#0 0x7f577e3115c7 in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x545c7)
#1 0x7f577dce4f8c in CRYPTO_free (/lib/x86_64-linux-gnu/libcrypto.so.1.0.0+0x5ff8c)
#2 0x4e538a in …
```
> Fix: ssh2john.c double free

- src/gpg2john.c
> Fix: gpg2john.c buffer over flow

- src/keepass2john.c
There is **heap-buffer overflow** in `BytesToUInt64()`, since the array which **s** points to maybe smaller than 8.
```C
static uint64_t BytesToUInt64(unsigned char * s)
{
uint64_t v = s[0];
v |= (uint64_t)s[1] << 8;
v |= (uint64_t)s[2] << 16;
v |= (uint64_t)s[3] << 24;
v |= (uint64_t)s[4] << 32;
v |= (uint64_t)s[5] << 40;
v |= (uint64_t)s[6] << 48;
v |= (uint64_t)s[7] << 56;
return v;
}
```
$ ../keepass2john failed_keepass
```C
=================================================================
==53903==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200000efb4 at pc 0x50a0df bp 0x7ffe1d01d7d0 sp 0x7ffe1d01d7c8
READ of size 1 at 0x60200000efb4 thread T0
#0 0x50a0de in BytesToUInt64 …
```
> Fix: keepass2john heap-buffer-overflow

- src/keepass2john.c
There are some **assert()** in keepass2john.c.
```C
$ ../keepass2john  failed_keepass
keepass2john: keepass2john.c:165: process_old_database: Assertion 'count == 1' failed.
Aborted
```
```
$ emacs failed_keepass
^C\331\242\232e\373K\265^@^@^C^@^B^P^@1~A\353\266| ^@L\300\3061\333\237S         ^@n_*Q\320\275\232!^W\370\266\337\210\335\213A\274\244e\362\210^\\317\2305\307\331\345z^W\3\
07\372
^D^@^B^@^@^@^@^D^@^M
^M^C\331\242\232e\373K\265\345e\315&\201\312^\j^S\270G\366\206\211'^Z84\301\310M"\355
```
So I replaced the assert() by checking the return value of fread().
> Remove assert(count == 1) by check the return of fread()

- src/keepass2john.c
If the buffer size is small then the size to be written into it, there will be **buffer overflow**.
```C
Inlining keepass/out/crashes/id:000005,sig:06,src:000037,op:havoc,rep:32
*** buffer overflow detected ***: ../keepass2john terminated
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x7338f)[0x7f4d6ab3b38f]
/lib/x86_64-linux-gnu/libc.so.6(__fortify_fail+0x5c)[0x7f4d6abd2c9c]
/lib/x86_64-linux-gnu/libc.so.6(+0x109b60)[0x7f4d6abd1b60]
/lib/x86_64-linux-gnu/libc.so.6(__fread_chk+0x13c)[0x7f4d6abd223c]
../keepass2john[0x50a95e]
../keepass2john[0x50abff]
../keepass2john[0x50b572]
../keepass2john[0x73e066]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f4d6aae9ec5]
../keepass2john[0x406b33]
======= Memory map: ========
00400000-00989000 r-xp 00000000 08:01 8657382 …
```
> Check the buffer size before fread(): keepass2john

- src/zip2john.c
Check the buffer size before fread().
If the buffer size is small then the size to be written into it, there will be **buffer overflow**.
```C
*** buffer overflow detected ***: ../zip2john terminated
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x7338f)[0x7fb5db9e238f]
/lib/x86_64-linux-gnu/libc.so.6(__fortify_fail+0x5c)[0x7fb5dba79c9c]
/lib/x86_64-linux-gnu/libc.so.6(+0x109b60)[0x7fb5dba78b60]
/lib/x86_64-linux-gnu/libc.so.6(__fread_chk+0x13c)[0x7fb5dba7923c]
../zip2john[0x50280a]
../zip2john[0x503aa2]
../zip2john[0x73e1e9]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7fb5db990ec5]
../zip2john[0x406b33]
======= Memory map: ========
00400000-00989000 r-xp 00000000 08:01 8657382 …
```
> Check the buffer size before fread(): zip2john

- src/keepass2john.c
- src/keyring2john.c
$ ./configure && make -sj8
$ ../keyring2john  failed_pw
```C
keyring2john: keyring2john.c:38: fget32_: Assertion 'count == 1' failed.
Aborted (core dumped)
```
$ emacs failed_pw
```
GnomeKeyring
^M^@
^@^@^@^@^@^@^@^Hopenwall^@^@^@^@^@..^@O\365\200\334^@^@^@^@^@^@^@^@^@^@^D\232|9^T\236\210\343\351\251^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@\327^Q\272\270\207\265\370^Hopenwad\
l^@^A^@^@^@..^@O\365\200\334^@^@^@^@^@^@^@^D^@^@^D\232|9^T\236\210\343\351\251^@^@^@^@^@
^@^@^@^@^A^@^@^Hopenwall^@^@^@^@^@..^@d^@\200\334^@^@^@^@^@^@^@^@^@L^D\232|9^T\236\210\343\351\251^@^@^@^@^@^@^@^@^@^@^@^@^@^Hopenwall^@^@^@^@^@..^@d^@\200\334^@^@^@^@^@^@^\
@^@^@L^D\232|9^T\236\210yring
^M^@
^@^@^@^@^@^@^@^Hopenwall^@^@^@^@^@&.^@O\365\200\334^@^@^@^@^@^@^@^@^@^@^D\232|9^T\236\210\343\351\251^@^@^@^@^@^@^@^@^@^@^@^@^@^ …
```
> Fix: keyring2john remove assert by checking the return value

- src/pwsafe2john.c
$ ../pwsafe2john  failed_pw
```C
pwsafe2john: pwsafe2john.c:69: process_file: Assertion 'count == 1' failed.
Aborted (core dumped)
```
$ emacs failed_pw
```
PWS3\244\220\345(@^@^@^@,t\240w\203\357\342^XW^Uy\211PWS35\215
```
> pwsafe2john.c: Remove assert by checking the return value of fread()

- src/pwsafe2john.c
Build warning:
```C
pwsafe2john.c: In function ‘process_file’:
pwsafe2john.c:53:6: warning: unused variable ‘count’ [-Wunused-variable]
int count;
^
```
> pwsafe2john.c: Remove unused variable

- src/vncpcap2john.c
There is problem with the `const u_char *pcap_next(pcap_t *p, struct pcap_pkthdr *h);`
```C
struct pcap_pkthdr {
struct timeval ts;	/* time stamp */
bpf_u_int32 caplen;	/* length of portion present */
bpf_u_int32 len;	/* length this packet (off wire) */
};
```
**caplen** means the length of packet we actually get.
**len** means the whole length of packet which should be.
Actually, caplen <= len, and the size of the packet should be **caplen**
$ ../vncpcap2john  failed_pw
```C
=================================================================
==130183==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6310000107ff at pc 0x7fb63ea52822 bp 0x7ffd04f6b3c0 sp 0x7ffd04f6ab80
READ of size 8388608 at 0x6310000107ff thread T0
#0 0x7fb63ea52821 …
```
> Use header.caplen instead of header.len

- src/keepass2john.c
- src/keyring2john.c
- src/keystore2john.c
- src/kwallet2john.c
Use: 
```C
warn_exit("%s: Error: read failed: %s.", argv[0], strerror(errno)); 
```
instead of: 
```C
warn_exit("Error: read failed."); 
```
> Use: warn_exit("%s: Error: read failed: %s.", argv[0], strerror(errno));

- src/wpapcap2john.c
1. Change full_packet to malloc(). The packet size may be bigger than 65535.
2. `pkt_hdr.incl_len <= pkt_hdr.orig_len`,
```C
typedef struct pcaprec_hdr_s {
uint32 ts_sec;         /* timestamp seconds */
uint32 ts_usec;        /* timestamp microseconds */
uint32 incl_len;       /* number of octets of packet saved in file */
uint32 orig_len;       /* actual length of packet */
} pcaprec_hdr_t;
```
The incl_len is the packet size, so use incl_len when copy packet.
> Fix: wpapcap2john.c buffer overflow

- src/john.c
> Report error if config file does not exist when '--config=somefile'

- src/BF_fmt.c
- src/opencl_bf_fmt_plug.c
Fix spell mistake, there is  **no BF_common_plug.c**
> Fix spell mistake, there is no BF_common_plug.c

- src/signals.c
Johnny had a problem : it couldn't pause a cracking session on Windows. To make Johnny be able to safely stop john on Windows, we had to send a CTRL_C_EVENT to the console in Johnny and modify john core. The core john patch is discussed there by Solar, you can see the diff too. 
http://www.openwall.com/lists/john-dev/2015/05/31/4
Even though the commit of Solar is in bleeding-jumbo https://github.com/magnumripper/JohnTheRipper/commit/b9cd224a86b3cdb4c8f3b56256d14a1a81928177, magnum made a small mistake in merging commit https://github.com/magnumripper/JohnTheRipper/blob/bleeding-jumbo/src/signals.c and he didn't kept the most important line SetConsoleCtrlHandler(NULL, FALSE);.
> Fix crash when receiving CTRL_C_EVENT on Windows from parent like Johny

- src/bench.c
- src/configure
- src/configure.ac
- src/listconf.c
- src/listconf.h
@magnumripper this adds support for -fsanitize=undefined.
I did not push that change into your repo, so that you can review and suggest changes.
But feel free to just pull and fix any issues you see. 
I tested similar changes on top of https://github.com/loverszhaokai/JohnTheRipper/tree/fuzz_option and found several instances of undefined behavior.
For now, I decided to add `-fsanitize-undefined-trap-on-error` together with `-fsanitize=undefined`.
That makes it easier to use gdb and look at the backtrace.
Without `-fsanitize-undefined-trap-on-error`, you get nice error messages, but they might scroll off the screen, unnoticed among other output:
The first message didn't occur with gcc 5.1.1, but with clang 3.5.0:
```
scrypt_fmt.c:179:9: runtime error: index 18446744073709551615 out of …
```
> Add --enable-ubsan (UndefinedBehaviorSanitizer)

- run/bitcoin2john.py
Expose the underlying exception in the error log, causing the open to fail.
> Explain DBError exception.

- src/pseudo_intrinsics.h
AVX512:
`#define vset_epi64 _mm512_set_epi64`
AVX2:
`#define vset_epi64 _mm128_set_epi64x`
SSE:
`#define vset_epi64 _mm_set_epi64x`
The suffix `x` can be sometimes confusing.
> fix an error introduced in commit 9783278

- src/pomelo_plug.c
emmintrin.h - SSE2 header, while immintrin.h is an AVX header.
> Fixed wrong header (was immintrin.h - AVX header)

- src/formats.c
Fix test_fmt_8_bit() to handle all the cases.
See
http://www.openwall.com/lists/john-dev/2015/08/06/15
http://www.openwall.com/lists/john-dev/2015/08/06/16
> Fix test_fmt_8_bit() to handle all the cases

- src/arm32le.h
- src/configure
- src/m4/jtr_generic_logic.m4
- src/mic.h
- src/ppc64.h
- src/pseudo_intrinsics.h
- src/rawSHA1_ng_fmt_plug.c
- src/rawSHA256_ng_fmt_plug.c
- src/rawSHA512_ng_fmt_plug.c
- src/simd-intrinsics.h
- src/wordlist.c
All 330 formats passed self-tests on ARM (with gcc 4.7.3).
There're still some problems with an older compiler (gcc 4.6.*), but I haven't figured it out yet.
> Add NEON intrinsics

- src/XSHA512_fmt_plug.c
- src/XSHA_fmt_plug.c
- src/citrix_ns_fmt_plug.c
- src/dynamic_fmt.c
- src/mssql05_fmt_plug.c
- src/mysqlSHA1_fmt_plug.c
- src/nt2_fmt_plug.c
- src/ntlmv1_mschapv2_fmt_plug.c
- src/oracle11_fmt_plug.c
- src/rawMD4_fmt_plug.c
- src/rawMD5_fmt_plug.c
- src/rawSHA1_fmt_plug.c
- src/rawSHA1_linkedIn_fmt_plug.c
- src/rawSHA224_fmt_plug.c
- src/rawSHA256_fmt_plug.c
- src/rawSHA384_fmt_plug.c
- src/rawSHA512_fmt_plug.c
- src/rawmd5u_fmt_plug.c
- src/salted_sha1_fmt_plug.c
- src/sapG_fmt_plug.c
- src/ssha512_fmt_plug.c
as discussed in https://github.com/magnumripper/JohnTheRipper/pull/1693
> Avoid strcpy if key is already aligned in set_key()

- src/keyring_fmt_plug.c
See http://www.openwall.com/lists/john-dev/2015/08/22/2
> Fix keyring crypt_all() which causes the cmp_all() always return 1

- src/CircleCI-MinGW.sh
Wine warnings / errors aren't treated as fatal anymore
We now need an alternate way to see if john actually failed during the
self-tests.
> Make CircleCI testing more robust

- src/dynamic_compiler.c
- src/dynamic_compiler.h
- src/dynamic_compiler_fmt_plug.c
@jfoug that was some bad hard-coding you did there again. I changed the number of test vectors to a macro in the header, and fixed all code to adopt except within that debug `big_gen_one()` stuff (marked with FIXME).
But something is not right. Please review, and see if you can find whatever little problem remains. Either there is something wrong with my changes, or the max-length tests actually found a real bug immediately.
This looks right to me:
```
$ ../run/john -test -form:dynamic='md4($s.$p),debug'
push
app_sh
.
app_p
f4h
crc32 = 75D868CA
pExpr=md4($s.$p)
extraParams=,debug
signature=@dynamic=md4($s.$p),debug@
line0=@dynamic=md4($s.$p)@46738b902316f5625b8c2dafb25559d0$719a288e
line1=@dynamic=md4($s.$p)@929234abc284b595cd96d85aeddcb42d$3d85c237 …
```
> Dynamic compiler: Add max-length and zero-length test vectors.

- src/opencl/cryptsha256_kernel_GPU.cl
- src/opencl/sha256_kernel.cl
- src/opencl/sha512_ng_kernel.cl
- src/opencl_rawsha256_fmt_plug.c
- src/opencl_rawsha512_ng_fmt_plug.c
In fact, I failed to see an error. But this fixes it 
BTW: I guess one of the Openwall's machines has this driver version, so I can test it there.
> Fix (or workaround?) for sha256crypt running on AMD 15.5 driver.

- src/opencl/cryptsha256_kernel_GPU.cl
Sorry, I wasn't aware of it. 
*****
BTW: on super (not sure in which openwall machine you guys are using TS).
```
$ ./jtrts.pl raw-sha256-opencl 
Can't locate JSON/XS.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at ./jtrts.pl line 8.
BEGIN failed--compilation aborted at ./jtrts.pl line 8.
```
> Previous fix for sha256crypt is necessary for Catalyst 15.7 too.

- src/opencl/cryptsha512_kernel_GPU.cl
* (15.7 Catalyst driver). It is 2x-3x faster now.
> Fine tune the OpenCL sha512crypt kernel for GCN on super.

- src/common-opencl.c
- src/opencl/cryptsha512_kernel_GPU.cl
While tuning LWS:
* There is a GWS value in use. Memory buffers are limited to this GWS value. Suppose it is 768.
* Maximun LWS is, e.g., 1024.
Without this check, a crypt_all(1024) will happen (ops, segmentation fault in some formats on CPU for sure). Allocated buffers are limited to 768 "items".
**********
Please merge the previous PR first.
> Fix for a bug while tuning LWS

- src/opencl/cryptsha512_kernel_GPU.cl
* Tested on super.
Not a big deal, but good enough.
> For sm_5x, vector operators do a better job in OpenCL sha512crypt.

- src/opencl_sha512.h
* See #1819.
I did only a fast test. 
```
../run/john ~/testhashes -form=sha512crypt-opencl -fork=3  -dev=2,1,0 --incremental
```
Everything seems ok.
> OpenCL: Use bitalign for ror_64() in shared code in Claudio's formats.

- run/dynamic.conf
Seems nobody published such a type already, whereas JtR cracks mysql(-sha1) and oracle hashes.
I've successfully used that new type today on real life databases hashes.
Might it be usefull for anybody else...
> Dynamic type for PostgreSQL stored MD5 hashes

- run/pem2john.py
- src/pem_fmt_plug.c
http://www.openwall.com/lists/john-users/2015/10/18/2
Solar is getting around 3500 c/s on our "super" box, while this code is able to get around 14000 c/s on our "bull" box ("super" is currently busy).
https://github.com/bwall/pemcracker/blob/master/test.pem is being used for benchmarking.
We do *not* have support for all possible ciphers, and key derivation functions. See https://github.com/dlitz/pycrypto/blob/master/lib/Crypto/IO/PKCS8.py for details.
Also, we do *not* have a working "pem2john.py" for now.
> Fast PEM cracker

- src/pseudo_intrinsics.h
- src/rawSHA1_ng_fmt_plug.c
- src/rawSHA256_ng_fmt_plug.c
since the latter is more intuitive (borrowed from AltiVec's vec_any_eq);
and drop vtestz_epi32 as it's not used anywhere.
> Rename vtesteq_epi32 to vanyeq_epi32

- run/aix2john.pl
- run/aix2john.py
This PR is for a couple of small bugfixes around the run/aix2john.pl and run/aix2john.py files. 
Consider a demonstration AIX 'shadow' file which, for the purposes of testing, is stored in ~/_aix/etc-security-passwd but would normally live in /etc/security/passwd on an AIX system.
```
$ cat ~/_aix/etc-security-passwd 
guest:
password = *
stuart: 
password = i9oX8gKSX2wtQ
lastupdate = 1448384447
nobody: 
password = * 
lpd: 
password = * 
stufus: 
password = VIsSD5LXPKxno
lastupdate = 1448384447
flags = ADMCHG
```
When looking at the two scripts (which more or less do the same thing), neither appeared to work correctly against this file.
```
$ perl aix2john.pl < ~/_aix/etc-security-passwd 
guest:i9oX8gKSX2wtQ
:VIsSD5LXPKxno
$ python aix2john.py ~/_aix/etc-security-passwd 
usage: aix2john.py …
```
> Fix aix conversion scripts

- src/common-opencl.c
[1] From now on only beta quality software will be provided (if provided, of course).
[2] Radeon™ HD 8000 – HD 8400, HD 7000 – HD 7600, HD 6000, and HD 5000 Series.
BTW: Crimson is useless on Linux if one is trying OpenCL on legacy hardware. This might be the case on Windows.
PS: 15.7.1 is a windows only version. The last available driver for Linux is 15.9.
> Include the last [1] WHQL certified driver for the 2nd generation of legacy hardware [2].

- src/common-opencl.c
If changed this way, we can control better the recommendations. 
* E.g., legacy can have a set of recommended drivers. GCN a different one.
> Improve recommendations about OpenCL drivers.

- src/opencl_rawsha256_fmt_plug.c
- src/opencl_rawsha512_ng_fmt_plug.c
Super:
```
./jtrts.pl -noprelims -stoponerror -type raw-sha256-opencl raw-sha512-ng-opencl sha256crypt-opencl sha512crypt-opencl xsha512-ng-opencl
[...]
All tests passed without error.  Performed 7 tests.  Time used was 145 seconds
```
> Mask tune fix for raw-sha[256/512]

- run/axcrypt2john.py
- src/axcrypt_fmt_plug.c
Two files added:
- axcrypt2john.py
- axcrypt_fmt_plug.c
The first one's outputs needed data for the cracker. It actually supports two formats : file.axx and file.axx + key-file
There is no way in the file.axx to be sure that user's provided key-file is the right one as any file can be used to proceed encryption. Nevertheless, AxCrypt provides a key-file generator that outputs a .txt file containing 53 bytes in base64 format, so if you manage to find that kind of file, it is likely to be the good one.
I tried to follow currently used coding-style (except for tabs)
TODO:
*add SIMD support for SHA1 part
*add doc/AxCrypt-Auditing-HOWTO file, as there are many things to say :)
Happy new year john community!
> AxCrypt file format + parser

- doc/README.keystore
- src/opencl/keystore_kernel.cl
- src/opencl_keystore_fmt_plug.c
Further to Issue #1964 ... an OpenCL implementation for finding Java Keystore 'outer' password(s) (makes no attempt to implement finding password(s) for 'inner' private-key-based alias password(s)).
Appears to work well on AMD GPUs, but not tested on nVidia GPUs apart from those in 2 relatively ancient MacBook Pro's in which self-testing fails (as it does for the majority of SHA-based OpenCL formats).
In essence, the kernel implements generic OpenCL SHA-1 hashing for <password + very long salt> where the salt is almost as long as the keystore file itself. Current maximum salt length is hard-coded as 4096 bytes but this may turn out to be insufficient for keystores with many contained aliases. In theory, the kernel may be useful for hashing of other formats with long salts.
OpenMP is …
> keystore-opencl format

- src/opencl_rawsha512.h
False positives < 0.05% (for 100,000 and 3,000,000 test cases).
> Shrink the hash/spread function. 

- run/john.conf
- run/password_found.sh
- src/logger.c
Adding new configuration key in john.conf: ExecOnCrackedPassword
If this configuration is enabled, the value of this parameter (it should be a command) will be executed when a password is found, passing the login name and the cracked password as parameters.
> Trigger command when password found

- src/common-opencl.c
It is a bad idea to pick CUs as the seed number. One might fail to use all CUDA cores/Stream processors.
*********
BTW: the new lcm() function can be placed in some generic functions file. If we will merge this, I can do the move and an -amend.
> GWS should be multiple of processors count not multiple of CUs.

- src/Makefile.in
I've seen errors in some situations. This fix git describe errors when it fails to find a valid tag.
> Always save the commit used to build JtR.

- src/common-opencl.c
- checking to ensure there is at least one working OpenCL device.
Doesn't hurt and can improve JtR error messages.
> Improve OpenCL error handling.

- run/pfxng2john.py
- src/pfx_ng_fmt_plug.c
Weird OpenSSL functions are now avoided (unlike the original pfx format).
Support for different mac algorithms (SHA-256 to SHA-512) is still pending.
> pfx-ng format

- run/dynamic.conf
```
$ ../run/john --format=dynamic_1550 --test
Benchmarking: dynamic_1550 [md5($u.:mongo:.$p) (... AVX2 8x3]... DONE
Many salts:	30992K c/s real, 30992K c/s virtual
Only one salt:	22616K c/s real, 22616K c/s virtual
```
```
$ ../run/john --format=mongodb --test
Benchmarking: MongoDB, system / network [MD5 32/64]... (4xOMP) DONE
Speed for cost 1 (salt type) of 0 and 1
Raw:	10381K c/s real, 2674K c/s virtual
```
> Faster way to crack MONGODB-CR hashes

- src/options.c
@magnumripper the following seems to be a valid warning, simply de-indenting the "if block" should get rid of this warning. 
```
$ gcc --version
gcc (GCC) 6.1.1 20160621 (Red Hat 6.1.1-3)
Copyright (C) 2016 Free Software Foundation, Inc.
```
```
$ make
...
gcc ...options.c -o options.o
options.c: In function ‘opt_init’:
options.c:706:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
if (!two_values)
^~
options.c:708:6: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
if (negative && options.loader.min_cost[i] == 0) {
^~
```
I don't actually know what this code does, so a careful review is needed.
> Fix a misleading indentation compiler warning

- run/pfxng2john.py
- src/pfx_ng_fmt_plug.c
- src/pkcs12_plug.c
This is a bit hacky but it works.
pkcs12_plug.c uses a weird combination of spaces and tabs for indentation. We need a separate commit to fix that. I should have been more careful while checking in the file.
I have replaced spaces with tabs in `pkcs12_pbe_derive_key` function.
> Add support for sha512 in pfx-ng format

- .travis.yml
@magnumripper This does not stop TravisCI from testing the `mscash2-opencl` format. Any ideas why this doesn't work.
Update: I had changed things in the wrong place in the .travis.yml file, fixed now.
> Fix TravisCI failures by disabling some OpenCL formats

- src/opencl_gpg_fmt_plug.c
- I saw no regressions on super (even on dev=0)
> Adjust gpg-opencl auto-tune max duration.

- src/opencl/cryptsha512_kernel_GPU.cl
- src/opencl_sha2_common.h
Is this a reasonable solution for #2215 ?
It works on super (which uses CUDA 8). I bet no new problems introduced.
****
In this change:
1. if there is a known problem, we do something.
2. otherwise, let the compiler do its best.
> Fix sha512crypt-opencl failing self tests on NVIDIA OpenCL driver 361

- doc/HDAA_README
- src/HDAA_fmt_plug.c
The current implementation for HDAA only covered RFC 2617, but was not able to
test digest auth responses in the old scheme.
> Added support for HDAA as defined in RFC 2069.

- run/john.conf
- src/logger.c
Please see previous pull request for use case #2247
Added config file parameters LogFilePermissions, PotFilePermissions, IgnoreLogChmodErrors.
Small issue: open() on line 102 of logger.c ignores perms_t on O_CREAT and perms are still set on create to the less permissive defaults. Perms don't actually get set to more permissive perms until second run of John when chmod() is called in log_file_init(). I'm not that familiar with C or the John code, so it may be a umask I'm not seeing somewhere. 
Besides the previously mentioned issue, feature works properly in my testing so far.
> Added LogFilePermissions, PotFilePermissions, IgnoreLogChmodErrors

- src/john.c
> path_init() must be called prior to CPU fallback mechanism

- .travis.yml
- .travis/test.sh
Travis requires some changes 'as is'.
- Tested on 'my' CI. Passes.
- Elapsed time increases in aprox 20 min (100% more). From 17 - 20 to 35 - 40.
> TravisCI: add ASAN into gcc build step

- src/gpg2john.c
- Tested on 'my' CI. Passes.
- Fixes and closes #2288
> Fix a out-of-range compare bug in gpg2john

- doc/INSTALL
This PR updates the compile instructions for OSX (tested with OSX Sierra 10.12)
- The brew link command is not recommended by homebrew. So the path to the include files is passed to `./configure`
- Use an option to provide the GCC compiler instead of symlinking it systemwide
- Added configure and make commands
> update OSX compile instructions

- src/leet_cc_fmt_plug.c
https://github.com/hashcat/hashcat/issues/541 has some real leet.cc hashes.
The current input hash format is "username$hash" where the username acts as a salt. How can I make the input hash format "username:hash" instead of "username$hash"? Do I need to implement a custom `prepare` function to do this?
> New format for cracking leet.cc hashes

- .travis.yml
- .travis/check.sh
- .travis/test.sh
Instead of https://github.com/magnumripper/JohnTheRipper/pull/2302 and https://github.com/magnumripper/JohnTheRipper/pull/2304, I was tempted to use this approach:
In the PR you can see (just an example from a remote past):
- gcc (ASAN) and clang (without ASAN) evaluating the build
- gcc (ASAN) on a recent compiler (in case of problems, it won't fail the CI build)
- TS on gcc on 16.04 LTS (in case of problems, it won't fail the CI build)
Thinking about  5fc8e78,  if JtR is failing because of ASAN, the new "infra" allow to 'fix' the build, e.g.:
- evaluate the build using gcc and clang on a stable OS **without** ASAN 
- test gcc (or clang) with ASAN only on a recent compiler - without a build fail.
- TS and whatever  - without a build fail.
> CI: improvement

- src/hmac_sha_plug.c
libressl deprecated the SHA_* functions and kept only the SHA1_* ones.
since they do the same (the existing code even mixed  calls to them up!)
let's just use the SHA1 ones everywhere so we're compatible with openssl
and libressl.
> fix build against libressl

- src/listconf.c
- src/mscash_common_plug.c
Missed changes
And this line in common.h (nvcc) (?)
```
#elif __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 7) || defined(__INTEL_COMPILER) || __NVCC__
```
> CUDA: more cosmetic cleanups

- src/common-opencl.h
All CI tests passed.
- undesired consequences are a possibility.
> OpenCL: make errors non-fatal for a "--test" run

- src/loader.c
It is not "the" fix, but it shows what is wrong. See #2366.
It fixes and closes #2366.
> loader: fix the --show

- src/common.h
It is not clear to me how the include "tree" should work inside JtR. Despite that:
- if this patch fixes the remaining problems on CI, I will merge it;
- it is safe;
Short list of concerns now:
> fix: add a missing include in common.h

- src/leet_cc_fmt_plug.c
dynamic_82 hashes with 64-byte salts trigger a crash in leet format due
to promiscuous valid function.
[crasher.txt](https://github.com/magnumripper/JohnTheRipper/files/684861/crasher.txt) (example hash which triggers a crash).
> leet: avoid crash while processing dynamic_82 type hashes

- doc/README.apex
The dump-apex-hashes.sql script was recently removed from the "unused" directory. This commit adds the removed script into the documentation file itself.
> Add dump-apex-hashes.sql script to README.apex

- src/memory.c
- src/memory.h
- src/wpapcap2john.c
* fix and close #2372
* a workaround for wpapcap2john.c is necessary
* I tried to avoid the workaround linking it against memory.o. But, then, I realized more modules are necessary. So, better to hear from you guys.
> Fix HEAP issues on JtR MinGW builds

- src/memory.h
I missed the else part.
****
The news are: we can now build, do some real cracking, and succeed a `--test-full` run on Windows using HEAD **without** tricks.
```
john -test-full=0
[...]
All 359 formats passed self-tests!
```
```
john --list=build-info
Version: 1.8.0-jumbo-1-5476-g6a58e5d
Build: mingw64 64-bit SSE2-ac
SIMD: SSE2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
$JOHN is 
Format interface version: 14
Max. number of reported tunable costs: 3
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 5.3.0
Crypto library: OpenSSL
OpenSSL library version: 01000207f
OpenSSL 1.0.2g  1 Mar 2016
GMP library version: 6.1.0 …
```
> minGW: fix for a memdbg bug introduced in b701bc0

- doc/README-PDF
- run/lib/ExifTool.pm
- run/lib/PDF.pm
- run/lib/RandomAccess.pm
- run/pdf2john.pl
- run/pdf2john.py
This is more reliable than the "pdf2john.py" script.
Upstream is at https://github.com/kholia/npdf2john URL. This PR is based
on the older "master" branch rather than the newer "ng" branch.
Fixes issue #2388.
> Add pdf2john.pl tool for extracting hashes from PDF files

- circle.yml
Use Fedora 25 instead of old Fedora 22 in CircleCI.
> Use Fedora 25 in CircleCI

- src/CircleCI-MinGW.sh
- src/Makefile.legacy
This renaming is breaking quite a few things.
This PR tries to fix https://github.com/magnumripper/JohnTheRipper/issues/2397 to some extent.
> Fix the rename-to-exe logic for the MinGW build

- src/common-opencl.c
- src/listconf.c
On a broken OpenCL system, JtR needs to be able to output as much information as possible.
https://github.com/magnumripper/JohnTheRipper/issues/2422
> Be more resilient on --list=opencl-devices

- src/wpapcap2john.c
I noticed that in the latest git revision ```wpapcap2john``` doesn't actually print hashes when procesing a capture file. Or, if a capture file contains many handshakes, it prints hashes for only some of them (but sometimes for none at all). I reproduced the issue using the [example capture file from Wireshark wiki:](https://wiki.wireshark.org/SampleCaptures?action=AttachFile&do=view&target=wpa-Induction.pcap)
```
$ ./wpapcap2john wpa-Induction.pcap
wpa-Induction.pcap: Radiotap headers stripped
Learned BSSID 00:0C:41:82:B2:55 ESSID 'Coherer' from beacon
1 ESSIDS processed
```
Expected result was to see the messages "Key1/Key2 hit...", then "Key3/Key4 hit..." and hash printed before "1 ESSID processed".
It looks like the program doesn't process some handshakes because [this …
> Make sure wpapcap2john initialises allocated memory with zeros.

- doc/README.FileVault2
- src/fvde_common.h
- src/fvde_common_plug.c
- src/fvde_fmt_plug.c
The heavy lifting is done by the https://github.com/kholia/fvde2john project which is a hacked up version of https://github.com/libyal/libfvde project. Big thanks to Omar Choudary, Felix Grobert and Joachim Metz for making this format possible.
See https://github.com/kholia/fvde2john/blob/master/README.txt for usage instructions. I can add these usage instructions to our repository too.
Is the name "FVDE" okay or do you have a better naming idea?
> Add support for cracking FileVault 2

- src/gpg2john.c
This fixes https://github.com/magnumripper/JohnTheRipper/issues/2449.
> gpg2john.c: fix compilation error in case of missing zlib-dev

- run/padlock2john.py
- src/aes_ccm.h
- src/aes_ccm_plug.c
- src/padlock_fmt_plug.c
Sample Padlock databases for testing,
* [padlock-empty-openwall.txt](https://github.com/magnumripper/JohnTheRipper/files/837456/padlock-empty-openwall.txt)
* [padlock-something-openwall.txt](https://github.com/magnumripper/JohnTheRipper/files/837458/padlock-something-openwall.txt)
* [padlock-password@12345.txt](https://github.com/magnumripper/JohnTheRipper/files/837460/padlock-password.12345.txt) (password is "password@12345")
Fixes https://github.com/magnumripper/JohnTheRipper/issues/2333.
> Add support for cracking Padlock databases

- run/bestcrypt2john.py
- src/aes_xts.h
- src/aes_xts_plug.c
- src/bestcrypt_fmt_plug.c
- src/pkcs12_plug.c
Notes,
+ Only AES-256 with CBC / XTS mode supported
+ Only SHA-256 / Whirlpool / SHA-512 supported
+ Tested with BestCrypt 3.0.3 on Linux and BestCrypt 9.03 on Windows
Whirlpool + AES-256 XTS seems to be the default combination.
XTS mode is working now ;)
> Initial support for Jetico BestCrypt 8.x / 9.x

- run/dmg2john.py
http://www.openwall.com/lists/john-dev/2016/06/10/1
DMG images for testing are available at https://github.com/kholia/VileFault/tree/master/tests.
Fixes issue https://github.com/magnumripper/JohnTheRipper/issues/2151. Both the `encrypted_blob_size` values (i.e. 48 and 64) are handled well.
Also see PR https://github.com/magnumripper/JohnTheRipper/pull/2447 discussion.
> dmg2john.py: handle encrypted_blob_size with value 64 properly

- run/office2john.py
Sample OneNote files for testing -> [sample-onenote-files.zip](https://github.com/magnumripper/JohnTheRipper/files/855335/sample-onenote-files.zip).
> Add support for cracking MS OneNote (.one) files

- doc/README.BitLocker
- src/aes_ccm.h
- src/aes_ccm_plug.c
- src/bitlocker_common.h
- src/bitlocker_common_plug.c
- src/bitlocker_fmt_plug.c
Hi,
This PR adds support for cracking Windows BitLocker passwords.
+ Tested with Windows 8.1 and 10 BitLocker volumes
+ AES CBC and XTS modes are supported
+ BitLocker To Go is supported
This PR introduces a new reliable `bitlocker2john` tool which works with all the sample images we have. The hashes produced by this new tool have the information required for Elena's BitCracker to work too, once it is trivially modified.
I will work with Elena Ago to see if we can improve and use her version of the `bitlocker2john` tool.
Big thanks to Joachim Metz and Elena Ago for making this format possible.
https://github.com/kholia/libbde/tree/bitlocker2john/samples has BitLocker encrypted images available for testing.
> Add support for cracking Windows BitLocker passwords

- src/opencl_rawsha256_fmt_plug.c
- src/opencl_rawsha512_gpl_fmt_plug.c
- src/rawSHA256_common.h
- src/rawSHA256_common_plug.c
- src/rawSHA512_common.h
- src/rawSHA512_common_plug.c
Affects only raw-SHA256 and x/raw-SHA512 OpenCL formats.
> OpenCL: fix for a non SIMD build

- src/common-opencl.c
Print more information, if needed and requested.
> OpenCL: improve error handling in --list=opencl-devices

- run/pcap2john.py
- src/net_ah_fmt_plug.c
This can later be expanded to cover more HMAC algorithms in the Authentication Header (AH).
[VRRP-AH.zip](https://github.com/magnumripper/JohnTheRipper/files/919063/VRRP-AH.zip) has some .pcap files for testing this.
> Add support for IPsec Authentication Header (AH) hashes

- run/geli2john.py
- src/geli_common.h
- src/geli_common_plug.c
- src/geli_fmt_plug.c
This is a super slow format. I will try creating an OpenCL version too.
Here are some [geli samples](https://github.com/magnumripper/JohnTheRipper/files/923669/geli-samples.zip) for testing.
> Add support for cracking FreeBSD GELI hashes

- src/racf2john.c
racf2john currently dumps DES RACF hashes, this update
allows it to also dump the newer type (2014) KDFAES hashes.
The new password algorithm announcement can be found here:
https://www-01.ibm.com/support/docview.wss?uid=isg1OA43999
```
sh-4.4$ run/racf2john
Usage: racf2john [RACF binary files]
sh-4.4$ run/racf2john ./testdb.bin
BBBBBBB:$racf$*BBBBBBB*932C1BBBB12A8274
C123456:$racf$*C123456*50A4B524A1854E38
A123456:$racf$*A123456*E7D7E66D00018000000800320010001041E09CD903BD84255D547CC162DCC1EC135D5D0AF2961EE5DD01B5FF489D2776
B123456:$racf$*B123456*E7D7E66D0001800000080032001000103D743EDF9DB18E2762E9C3F801672954A787F176DCF675EBE303B463FC81775A
```
The short hashes are DES and are currently supported by John for cracking.
The longer hashes are not yet supported by John, but do represent the …
> racf2john update to dump KDFAES hashes

- src/bitlocker2john.c
This PR enables `bitlocker2john.c` to generate hashes compatible with the BitLocker CPU format. The BitLocker GPU format will need to be modified to use this new hash format.
@e-ago Please review this. Do you have enough information now to modify the GPU format suitably?
> Various bitlocker2john.c cleanups

- src/racf2john.c
Since my CI builds use 'Werror' enabled, this change is needed.
> racf2john: mute a compiler warning

- src/PO_fmt_plug.c
Otherwise, the compiler could do an implicit conversion resulting in a negative number (see line 197).
> PO: fix a bad conversion in a signed char buffer

- .travis.yml
- .travis/check.sh
This PR enables building of JtR on OS X. The building and testing on OS X completes in under 8 minutes, it seems.
This fixes issue https://github.com/magnumripper/JohnTheRipper/issues/2454.
> Use OS X support in Travis CI

- run/geli2john.py
- src/geli_common_plug.c
There is not much to review here. I have uploaded GELI encrypted sample disk images to http://openwall.info/wiki/john/sample-non-hashes page.
> All FreeBSD GELI versions (v0 to v7) are supported now

- src/rawSHA1_linkedIn_fmt_plug.c
Looks like Raw-SHA1-Linkedin can use a plaintext length of 125 for non-SIMD builds.
Tested this build (suggested by Solar in john-users):
```
$ make distclean
$ ./configure --disable-native-tests CFLAGS='-O2 -mno-sse2 -mno-mmx -U__SSE__'
```
> Increase Raw-SHA1-Linkedin's PLAINTEXT_LENGTH for non-SIMD builds

- src/ospf_fmt_plug.c
Sample OSPF pcap files can be found at https://c0decafe.de/svn/codename_loki/test/.
https://github.com/Ettercap/ettercap/pull/798 is the corresponding PR in Ettercap.
> Add support for more OSPF authentication algorithms

- run/kerberom/README.md
- run/kerberom/bin/BUILD.md
- run/kerberom/kerberom.py
- run/kerberom/kerberom.spec
- run/kerberom/modules/rom/_crypto/ARC4.py
- run/kerberom/modules/rom/_crypto/MD4.py
- run/kerberom/modules/rom/_crypto/MD5.py
- run/kerberom/modules/rom/ccache.py
- run/kerberom/modules/rom/crypto.py
- run/kerberom/modules/rom/krb5.py
- run/kerberom/modules/rom/pac.py
- run/kerberom/modules/rom/rich.py
- run/kerberom/modules/rom/util.py
This is a new version of the run/kerberom tool. It provides Windows support (needing PyInstaller if you want to create a standalone binary) and especially the support of Windows implicit authentication. This is particularly interesting if one managed to get another current logon context, for example in redteam assessments, thus not needing any credential to use kerberom and retrieve TGS to crack with krb5tgs format.
The Linux part was a bit modified so that it output samaccountname:ticket, but this does not impact john implementation :+1:  .
This should not be the final version, when I find time I'll implement the other krb5tgs format (thus not based on ARC4 but SHA1) and adapt the tool to retrieve the corresponding hashes :wink: 
Cheers!
> kerberom: new version adding Windows support and Windows implicit authentication mechanisms

- src/configure
- src/configure.ac
Currently, autoconf checks for the existence of the SSL_library_init symbol in order to verify that libssl can be linked. A recent update to OpenSSL (>= 1.1.0) removed quite a few legacy functions, including this one. This commit checks for the presence of SSL_CTX_new instead, which exists in OpenSSL >= 1.0.0.
> autoconf: Replace deprecated symbol check for OpenSSL >= 1.1.0

- src/Makefile.legacy
when building packages (e.g. for openSUSE Linux)
(random) filesystem order of input files
influences ordering of functions in the output,
thus without the patch, builds (in disposable VMs) would usually differ.
See https://reproducible-builds.org/ for why this matters.
> sort input files

- src/Makefile.in
Since it is harmless, and can be useful for some people, I'm proposing the patch. 
* It does static code analysis and output warnings like these:
```
[misc.c:98]: (style) The scope of the variable 'block' can be reduced.
[misc.c:121]: (style) The scope of the variable 'pos' can be reduced.
[misc.c:122]: (style) The scope of the variable 'c' can be reduced.
[misc.c:384]: (style) The scope of the variable 't' can be reduced.
[misc.c:56]: (warning) %u in format string (no. 1) requires 'unsigned int' but the argument type is 'signed int'.
[misc.c:76]: (warning) %u in format string (no. 1) requires 'unsigned int' but the argument type is 'signed int'.
[7z_fmt_plug.c:591]: (style) The scope of the variable 'len' can be reduced.
[7z_fmt_plug.c:509]: (error) Signed integer overflow for expression …
```
> maint: add a static code analysis tool

- src/ethereum_common.h
- src/ethereum_common_plug.c
- src/ethereum_fmt_plug.c
- src/opencl_ethereum_fmt_plug.c
The format completes benchmarking, prints the speed and then runs into some weird glibc memory check failures.
Try doing `../run/john --format=ethereum-opencl --test` to reproduce the problem.
Any ideas about what might be going wrong?
Update: The `crypt_out` base size was incorrect (16 instead of 32). Fixing this seems to have fixed the weird memory failures!
> Partial OpenCL support for Ethereum format

- run/multibit2john.py
- src/multibit_fmt_plug.c
Ported from https://github.com/gurnec/btcrecover/commit/8a6e74e66 commit.
The hashes need re-extraction using `multibit2john.py` after this commit.
This should fix issue https://github.com/magnumripper/JohnTheRipper/issues/2578.
> Reduce false positives in MultiBit format

- src/ztex/device_format.c
- src/ztex/device_format.h
- src/ztex/jtr_device.c
- src/ztex/jtr_mask.c
- src/ztex/pkt_comm/cmp_config.c
- src/ztex/pkt_comm/inpkt.c
- src/ztex/pkt_comm/inpkt.h
- src/ztex/pkt_comm/word_gen.c
- src/ztex/pkt_comm/word_gen.h
- src/ztex/task.c
- src/ztex_descrypt.c
Improvements in ztex library
- fixed memory leak
- correct handling of FMT_REMOVE flag
- moved some code from format to library
- some cleanup
- fixed compiler warning
- set line terminator to LF and removed trailing spaces in modified C files
> Improvements in ztex library

- src/opencl/ethereum_presale_kernel.cl
- src/opencl_ethereum_presale_fmt_plug.c
- src/opencl_keccak.h
AES on CPU (current bleeding-jumbo code),
```
$ OMP_NUM_THREADS=1 ../run/john --test --format=ethereum-presale-opencl
Benchmarking: ethereum-presale-opencl, Ethereum Presale Wallet ...
Speed for cost 1 (iteration count) of 2000
Raw:	313223 c/s real, 310182 c/s virtual
```
This increases to `409600 c/s` for OMP_NUM_THREADS=16.
AES + Keccak on GPU,
```
$ OMP_NUM_THREADS=1 ../run/john --test --format=ethereum-presale-opencl
Benchmarking: ethereum-presale-opencl, Ethereum Presale Wallet ...
Speed for cost 1 (iteration count) of 2000
Raw:	385505 c/s real, 385505 c/s virtual
```
There is a decent speed increase for OMP_NUM_THREADS=1 compared to AES-on-CPU code.
> Ethereum format: Move AES decryption + Keccak to GPU

- run/john.conf
- src/ztex/device_format.c
- src/ztex/pkt_comm/cmp_config.c
- src/ztex/task.c
- Fixed  incorrect handling of automated (w/o hitting a key) status reporting at the start of --restore, there's the case where get_key() is called before crypt_all().
- In salt->cost[cost_num]  initialized are only array elements that match non-null tunable_cost_name's. The rest (up to FMT_TUNABLE_COSTS) are uninitialized memory.
> bugfixes in ztex-bcrypt

- run/money2john.py
- src/money_fmt_plug.c
This fixes https://github.com/magnumripper/JohnTheRipper/issues/2601.
MS Money deals with non-ASCII passwords pretty weirdly. Please have a look at it.
Here are some [sample MS Money DBs](https://github.com/magnumripper/JohnTheRipper/files/1117821/Sample.MS.Money.DBs.zip) for testing.
> Add support for MS Money

- src/gpg_common_plug.c
Brute forcing symmetrically encrypted GPG files without MDC results in a lot of false positives. Adding FMT_NOT_EXACT flag allows cracking to continue in such cases.
> Add FMT_NOT_EXACT in GPG format to handle files without MDC

- src/ssh_ng_fmt_plug.c
It is necessary to build inside CI.
> Remove one unused function in ssh_ng format

- run/openssl2john.py
This reverts the changes made by commit d297620f376, as we need compatibility with Python 2.4 for now.
Files encrypted with "openssl enc" which do not use base64 encoding are also supported now.
> Few enhancements for openssl2john.py

- src/wpapcap2john.c
- src/wpapcap2john.h
This should help with issue https://github.com/magnumripper/JohnTheRipper/issues/2636.
This fixes various ASan crashes found with the help of libFuzzer.
The most important change in this PR is,
``` diff
@@ -513,11 +521,15 @@ static void HandleBeacon(uint16 subtype)
while (((uint8*)tag) < pFinal) {
char *x = (char*)tag;
+               if (x + 2 > (char*)pFinal || x + 2 + tag->taglen > (char*)pFinal)
+                       break;
if (tag->tagtype == 0 && tag->taglen < sizeof(essid))
memcpy(essid, tag->tag, tag->taglen);
x += tag->taglen + 2;
tag = (ether_beacon_tag_t *)x;
}
```
> Make wpapcap2john more robust in input handling

- doc/libFuzzer-HOWTO.txt
- src/Makefile.in
- src/Makefile.legacy
- src/SIPdump.c
- src/calc_stat.c
- src/configure
- src/configure.ac
- src/dmg2john.c
- src/eapmd5tojohn.c
- src/genmkvpwd.c
- src/john.c
- src/keepass2john.c
- src/mkvcalcproba.c
- src/raw2dyna.c
- src/tgtsnarf.c
- src/uaf2john.c
- src/vncpcap2john.c
- src/wpapcap2john.c
This patch introduces multiple changes.
+ libFuzzer is enabled when --enable-libfuzzer configure option is used
+ keepass2john.c is now a standalone program
+ dmg2john.c is now a standalone program
+ Fuzzing is implemented for keepass2john, dmg2john, vncpcap2john, uaf2john, eapmd5tojohn, and wpapcap2john
+ Stub fuzzing functions for other targets are implemented
> Enable usage of libFuzzer with JtR

- run/openssl2john.py
- src/openssl_enc_fmt_plug.c
https://blog.malwarebytes.com/cybercrime/2017/07/the-key-to-the-old-petya-has-been-published-by-the-malware-author/ (relevant read).
> Add support for SHA-256 in openssl-enc format

- src/CircleCI-MinGW.sh
This enables detection of stack smashing problems on Linux. ASan is unable to detect such problems under certain conditions.
> Enable -fstack-protector-all for a CircleCI build

- src/opencl_DES_bs_f_plug.c
- src/opencl_DES_bs_h_plug.c
See #2652
****
* Notes:
* Parallel per-salt kernel build is disabled by default on HEAD.
* The 4096 limit is not working properly. That said, anyone can crash JtR HEAD using a proper hash file.
```
#0  0x000000000079dc64 in create_tables (htype=<value optimized out>, loaded_hashes_ptr=<value optimized out>, 
num_ld_hashes=<value optimized out>, offset_table_ptr=0x7fffffffa090, offset_table_sz_ptr=0x7fffffffa098, 
hash_table_sz_ptr=0x7fffffffa09c, verb=0) at bt.c:474
#1  create_perfect_hash_table (htype=<value optimized out>, loaded_hashes_ptr=<value optimized out>, num_ld_hashes=<value optimized out>, 
offset_table_ptr=0x7fffffffa090, offset_table_sz_ptr=0x7fffffffa098, hash_table_sz_ptr=0x7fffffffa09c, verb=0) at bt.c:696
#2  0x0000000000611192 in fill_buffer (salt=<value optimized out>, …
```
> Warn about the slow startup at many salts in descrypt-opencl

- run/lastpass2john.py
- src/lastpass_fmt_plug.c
Changes,
+ Variable iteration count is supported now
+ The lastpass2john.py utility generates correctly formatted hashes now
This should fix issues https://github.com/magnumripper/JohnTheRipper/issues/890 and https://github.com/magnumripper/JohnTheRipper/issues/883.
Sample data for testing this PR -> [LastPass v3.x Sample Data.zip](https://github.com/magnumripper/JohnTheRipper/files/1220463/LastPass.v3.x.Sample.Data.zip)
> Few fixes for the LastPass format

- src/Makefile.in
This should fix the autoconf warnings you reported earlier today.
> Cleanup old putty2john build stuff

- src/dashlane_common_plug.c
I was invoking our BytesToKey implementation in a wrong manner earlier, bits aren't the same as bytes ;)
> Get rid of EVP_BytesToKey from Dashlane format

- src/opencl/wpapsk_kernel.cl
- src/opencl_aes_ctx.h
- src/opencl_cmac.h
- src/opencl_sha2_ctx.h
- src/opencl_wpapsk_fmt_plug.c
- src/wpapsk.h
Closes #2648.
The support for vectorization was disabled for now. It can be re-enabled
once I add support for running the wpapsk_final_sha256() in scalar mode
after running the others vectorized. Just a matter of work but very few
devices want vectorized code anyway, nowadays.
> WPAPSK-opencl: Add support (GPU side) for 802.11w / WPA-PSK-SHA256.

- src/secp256k1/ecmult.h
- src/secp256k1/ecmult_gen.h
- src/secp256k1/ecmult_gen_impl.h
- src/secp256k1/ecmult_impl.h
- src/secp256k1/field.h
- src/secp256k1/field_impl.h
- src/secp256k1/group.h
- src/secp256k1/group_impl.h
This should fix https://github.com/magnumripper/JohnTheRipper/issues/2693.
> Eliminate warnings about unused functions from secp256k1 code

- run/pgpdisk2john.py
- src/pgpdisk_fmt_plug.c
Usage of EME2-AES with PGP Virtual Disks is broken in SED 10.4.1 MP1 in Windows 7 64-bit. The generated disk images are corrupt (e.g. CheckBytes are all zero).  Such images "mount" but don't work afterwards, and can't be unmounted.
The same EME2-AES feature works fine when used on macOS.
> Add support for EME2-AES in PGP Disk format

- src/opencl/pgpdisk_kernel.cl
- src/opencl_pgpdisk_fmt_plug.c
- src/pgpdisk_common.h
- src/pgpdisk_common_plug.c
- src/pgpdisk_fmt_plug.c
Writing a pure GPU kernel would involve a lot of work, like implementing Twofish and CAST5 on the GPU.
This fixes #2699.
> OpenCL support for PGP Disk format

- run/pcap2john.py
This should fix https://github.com/magnumripper/JohnTheRipper/issues/2368.
```
$ ../run/pcap2john.py 
Usage: ../run/pcap2john.py [.pcap files]
Note: This program does not have the functionality of wpapcap2john, SIPdump, and vncpcap2john.
```
This note is also displayed during the actual use of the program.
> Show limitations of pcap2john.py explicitly

- src/ztex/pkt_comm/cmp_config.c
- src/ztex/ztex_scan.c
- src/ztex/ztex_scan.h
- fixed bug in memory allocation in a case where number of hashes per salt exceeds the maximum number supported by bitstream;
- changed the behavior when it detects 3rd party firmware on the board - now it just overwrites it.
> Ztex improve

- src/keepass2john.c
See http://www.openwall.com/lists/john-users/2017/09/02/1 for details.
I have only compile-tested this change.
> Make error messages more informative in keepass2john.c

- src/CircleCI-MinGW.sh
See https://github.com/magnumripper/JohnTheRipper/issues/2543 for details.
AVX stuff works great but AVX2 stuff is broken for some formats.
> Enable AVX and AVX2 in MinGW builds

- src/pgpsda_common_plug.c
I learnt to use the Swedish keyboard today! PGP doesn't not allow copy-pasting of the password.
> Add another test vector in PGP SDA format

- .travis.yml
- .travis/check.sh
- .travis/test.sh
Closes #2736. 
* The goal is to test and produce a result as fast as possible
* The build jobs (ones that can't fail) will run in approx 25 minutes
* It is possible to reduce the time if we separate the slower test into 2 sets (cpu and opencl)
* Apple stuff can take hours to start to build, so I made it 'optional' (the build result do not depend on it).
> Update Travis CI tests

- src/common.h
> Fix MAYBE_INLINE macro for GCC 5+

- src/asn1_plug.c
I found no reason for a printf re-definition.
> Mute a compiler warning [-Wmacro-redefined]

- src/configure
- src/m4/ax_opencl.m4
Portable Computing Language (pocl) aims to become a MIT-licensed
open source implementation of the OpenCL standard which can be
easily adapted for new targets and devices, both for homogeneous
CPU and heterogeneous GPUs/accelerators.
It can't run all formats, but it can be used to improve our OpenCL
testing using Docker images.
> Add pocl as a valid OpenCL implementation

- src/wpapcap2john.c
- src/wpapcap2john.h
@kholia here's my stab at #2751. My code too is somewhat hairy, but it's less intrusive and keeps full functionality of `wpa[ess]` ie. dupe checking and so on.
What I do is "fabricate" a fake 802.11 header using the original Ethernet data. It seems to work just fine.
> wpapcap2john: Re-introduce support for Ethernet encapsulation. See #2751

- run/sshng2john.py
Don't just look at the first line of a private key. Some keys have extra info in them.
This is a PR version of the patch attached in issue https://github.com/magnumripper/JohnTheRipper/issues/2759.
> Make input parsing more robust in sshng2john.py

- src/ztex/device_bitstream.h
- src/ztex/task.c
- src/ztex_bcrypt.c
- src/ztex_descrypt.c
Such a limit appeared because of 16-bit word(key) ID in word_list/template_list packet and internally in FPGA where IDs are stored/processed.
Now it just sends several packets where necessary.
> Removed limit of (2^18-4) keys/board per crypt_all()

- src/bitlocker2john.c
- src/opencl/bitlocker_kernel.cl
- src/opencl_bitlocker_fmt_plug.c
In this pull request:
- bitlocker2john code reworked (more checks on VMK format)
- bitlocker-opencl:
- code cleanup 
- comments in main attack kernel
NB. False positive occurred (see issue opened on my repo: https://github.com/e-ago/bitcracker/issues/1 ); I found an empirically verified and more restrictive check to avoid this type of false positives (-s option, see README https://github.com/e-ago/bitcracker). In the future I will improve this option with a slower but more robust check.
Is it possible to add this optional check in this JtR version? (opening in a different pull request)
> BitLocker-OpenCL

- src/common-opencl.c
- src/john.c
- src/loader.c
- src/options.c
- src/options.h
- src/ztex_bcrypt.c
- src/ztex_descrypt.c
The '--device' option can handle OpenCL CPUs, OpenCL accelerators, OpenCL GPUs, and ZTEX boards.
* CI is happy (even for a ztex build).
> Rename 'gpu_devices' to be adequate to any accelerator

- src/common-gpu.c
- src/common-gpu.h
- src/common-opencl.c
- src/common-opencl.h
- src/john.c
So, anyone can list and use the same device(s) more than once while
forking (e.g., to compensate the performance difference between
devices).
Closes #2778
> Allow to duplicate a device on --devices list

- src/listconf.c
I want to be able to use
```
for mode in `./john --list=ext-modes`; do ./john --external=$mode ...; done
```
without this change, I get 
```
No generate() for external mode: hybrid_example
```
etc.
Not sure whether these hybrid modes should be listed under ext-filters.
I think so, because they can filter input words just like regular filters.
And even if they don't, they can be used in addition to another mode which generates the candidates.
Please comment, and I'll adjust my pull request.
BTW: What's the intended difference between ext-filters and ext-filters-only?
Does a generator with a filter make sense?
I think an external mode which has both is somehow broken.
> ./john --list=ext-modes should only list standalone external modes

- src/gpg_common.h
- src/gpg_common_plug.c
- src/gpg_fmt_plug.c
- src/opencl/gpg_kernel.cl
- src/opencl_gpg_fmt_plug.c
This tries to fix #2784 and https://github.com/magnumripper/JohnTheRipper/issues/2242.
@solardiz Are the reliability problems with `gpg-opencl` format gone for you as well (with this patch)?
Do I need to tweak the cost description? In particular, what should happen to `hash algorithm [1:MD5 2:SHA1 3:RIPEMD160 8:SHA256 9:SHA384 10:SHA512 11:SHA224]` string?
> Remove CPU fallback from GPG OpenCL format

- run/office2john.py
This should fix #2780.
The new approach is slower but it should be more robust.
> Use brute-force in office2john.py to discover RC4 Encryption Header

- src/krb5_asrep_fmt_plug.c
> Fix and improve valid in krb5asrep format

- src/putty2john.c
See https://github.com/magnumripper/JohnTheRipper/issues/814 for some background.
[Old-SSH1-Keys.zip](https://github.com/magnumripper/JohnTheRipper/files/1340073/Old-SSH1-Keys.zip) <- data for testing.
> Bail out for SSH1 keys in putty2john

- src/gpg2john.c
```
gpg2john.c: In function ‘gpg2john’:
gpg2john.c:400:6: warning: too many arguments for format [-Wformat-extra-args]
fprintf(stderr, "Error: Ensure that the input file contains a single private key only.\n", filename);
```
Safe to merge
> Mute a compiler warning

- src/gpg_common.h
- src/gpg_common_plug.c
- src/opencl/gpg_kernel.cl
- src/opencl_gpg_fmt_plug.c
This fixes https://github.com/magnumripper/JohnTheRipper/issues/2788.
There are some hacks present (e.g. addition of `int format` ) but it works (TM).
> Add OpenCL support for SHA-256 based S2K

- src/CircleCI-MinGW.sh
- src/john.c
- src/listconf.c
- src/x86-64.S
- src/x86.S
This ensures that messages like "Sorry, AVX2 is required for this build" matches what CPU features are actually tested with cpuid. See #2764.
> Make sure our definition of CPU name matches what was actually defined with the cpuid tests. See #2764.

- src/opencl_gpg_fmt_plug.c
Found, and patch supplied by Steven Noonan.
This fixes https://github.com/magnumripper/JohnTheRipper/issues/2814.
> Initialize Twofish correctly in GPG OpenCL format

- src/wpapmk.h
- src/wpapsk.h
It is:
```
uint32_t eapol_size;
```
****
Please, squash.
> Remove a comparison of an unsigned < 0

- run/krbpa2john.py
This was tested with Windows 8.1 client, Windows 2012 R2 Active Directory Domain Controller, and instructions from https://github.com/nidem/kerberoast.
[AD-2012-openwall@123-TGS-SPN.zip](https://github.com/magnumripper/JohnTheRipper/files/1400827/AD-2012-luser-openwall.123-TGS-SPN.zip) <- sample .pcap for testing this PR.
The TGS-REP hash extracted from this .pcap is crackable by both JtR and `tgsrepcrack.py`.
Next, I would like to verify if this also works against the TGS-REP messages generated by krb5 software running on Linux.
Update: No luck with cracking the TGS-REP messages generated by krb5 software running on Linux. According to https://adsecurity.org/?p=2293 article, "The TGS is encrypted using the target service accounts’ NTLM password hash and sent to the user (TGS-REP)". I …
> Add support for extracting TGS-REP hashes

- doc/Kerberos-Auditing-HOWTO.md
The `krb5-23` format was dropped in commit d8f6bf523f86d012c99813bddfa372588072e6cb.
This is related to https://github.com/magnumripper/JohnTheRipper/issues/2824.
> Update documentation to reflect removal of krb5-23 format

- src/krb5_common.h
- src/krb5_common_plug.c
- src/krb5_db_fmt_plug.c
This fixes https://github.com/magnumripper/JohnTheRipper/issues/2824 and https://github.com/magnumripper/JohnTheRipper/issues/636.
Both etype 2 and etype 3 share the same hashing scheme. In other words, the `krb5-3` format can crack etype 3 and etype 2 hashes both.
> Add support for cracking Kerberos des-cbc-md5 hashes

- src/krb5_asrep_fmt_plug.c
This should fix https://github.com/magnumripper/JohnTheRipper/issues/2835.
> Add missing null-termination in KRB5 AS-REP format

- run/dynamic.conf
- run/neo2john.py
@frank-dittrich Is using the `dynamic_1608` number OK or should I use something else?
[Sample Neo Wallets.zip](https://github.com/magnumripper/JohnTheRipper/files/1424842/Sample.Neo.Wallets.zip) (for testing).
This code was generated by the dynamic compiler.
> Add support for cracking Neo wallets

- src/rawMD4_fmt_plug.c
- src/rawMD5_fmt_plug.c
- src/rawMD5flat_fmt_plug.c
Although it shouldn't matter in case of hexadecimal encoding, the Raw MD4, MD5 and MD5 flat format not only couldn't handle uppercase characters, but the error message was not really helpful. This issue was discussed in #2842.
> Raw-MD{4,5{,flat}}: handle uppercase hex digits

- src/inc.c
- src/mask.c
- src/mask.h
See #2785
Tested with some stuff like:
```
../run/john --stdout --incremental | head -n 5
../run/john --stdout --incremental --min-len=14 --max-length=20 | head -n 5
../run/john --stdout --incremental --min-length=20 --max-length=20 | head -n 1
../run/john --incremental --stdout --min-length=40 --mask='?w?w?w' | head -n 5
../run/john --incremental --stdout --min-length=20 --mask='?w?w' | head -n 1
```
> Allow -max-len to bump Incremental's maxlen to beyond the conf

- src/opencl_electrum_modern_fmt_plug.c
It appears twice (the removed one outside the `#ifdef` OPENCL).
> Remove a duplicate #include

- src/Makefile.in
- src/mask.h
- src/mask_ext.h
- src/opencl_mask.h
- src/opencl_mask_extras.h
It is not OpenCL related. That said, a 'core' file like cracker.c
cannot depend on any OpenCL (opencl_*.h) file.
> An OpenCL #define was defined in the wrong place

- src/known_hosts_fmt_plug.c
Tested on PPC64 Debian 8 VM (emulated using QEMU).
> Fix salt alignment in known_hosts format

- src/HDAA_fmt_plug.c
- src/NT_fmt.c
- src/XSHA512_fmt_plug.c
- src/formats.c
- src/krb5_db_fmt_plug.c
- src/md2_fmt_plug.c
- src/mdc2_fmt_plug.c
- src/odf_fmt_plug.c
- src/office_common_plug.c
- src/opencl_salted_sha_fmt_plug.c
- src/opencl_xsha512_fmt_plug.c
- src/palshop_fmt_plug.c
- src/panama_fmt_plug.c
- src/pst_fmt_plug.c
- src/salted_sha1_common.h
- src/tiger_fmt_plug.c
- src/whirlpool_fmt_plug.c
- src/zipmonster_fmt_plug.c
Enhanced format self test, making sure that hash formats with format tags do have a split() function which adds the format tag when processing raw hashes.
(Otherwise, raw hashes end up in the pot file).
Plus fixes for problems uncovered with the enhanced self test
Some formats added the format tag in binary(), but that's the wrong place.
Some formats listed the wrong tag in the format's signatures.
The first commit includes the fixes for failed tests, the second commit includes the enhanced self test.
(I want to avoid `git bisect` trouble.)
> Some format fixes (split() function ...), and improved format self test

- src/gpg_common_plug.c
This is related to https://github.com/magnumripper/JohnTheRipper/issues/1892.
I have added additional test-vectors to verify this stuff.
> Fix cracking of GPG files using 64-bit symmetric encryption

- doc/DYNAMIC
- run/dynamic.conf
It seems that we already support all the webEdition hash formats. I am documenting the webEdition hash formats below for reference purposes.
File `we_users_user.class.php` from webEdition_6390.tgz, 
``` PHP
public static function makeSaltedPassword(&$useSalt, $username, $passwd, $strength = 15){
$passwd = substr($passwd, 0, 64);
if(version_compare(PHP_VERSION, '5.3.7') >= 0){
$useSalt = self::SALT_CRYPT;
return crypt($passwd, '$2y$' . sprintf('%02d', $strength) . '$'.self::getHashIV(22));
} else {
$useSalt = self::SALT_MD5;
return md5($passwd . md5($username));
}
}
```
Under webEdition_6400.tgz,
``` PHP
public static function makeSaltedPassword(&$useSalt, $username, $passwd, $strength = 15){
$passwd = substr($passwd, 0, 64);
if(version_compare(PHP_VERSION, '5.3.7', '>=')){
$useSalt = …
```
> Correct casing for webEdition word

- src/dynamic_fmt.c
Hopefully, this is the correct fix. I am merging this now as this is breaking some custom builds.
> Fix a typo in dynamic format

- src/opencl_cryptsha512.h
- src/opencl_fvde_fmt_plug.c
- src/opencl_krb5pa-sha1_fmt_plug.c
- src/opencl_office_fmt_plug.c
- src/opencl_rakp_fmt_plug.c
- src/opencl_rar5_fmt_plug.c
- src/opencl_rawmd4_fmt_plug.c
- src/opencl_zip_fmt_plug.c
I am not sure about the `SALT_ALIGN` change in `opencl_cryptsha512.h`. Rest all look OK to me.
> Fix alignment problems in various OpenCL formats

- src/opencl_electrum_modern_fmt_plug.c
This reverts commit f8debd25b141837f43d86273359244b9b568a1a1.
I'll merge this soon. The revert can't be done using GitHub (itself) tools.
> Revert "maint: remove a duplicate #include"

- src/7z_fmt_plug.c
This helps with https://github.com/magnumripper/JohnTheRipper/issues/2889. Also see https://github.com/magnumripper/JohnTheRipper/pull/2891.
It seems to work fine in practice.
> Relax CRC validation check in 7z format

- run/john.conf
- src/john.c
- src/options.h
- src/unicode.c
Normally, we try to handle Unicode characters not in our selected codepage with best effort. Enabling this option will instead translate any such character to "?" (default), to meet certain formats' behavior.
See https://github.com/magnumripper/JohnTheRipper/pull/2886 for discussion.
NOTE: ~~This is not 100% ready yet.~~ I would like to get some early feedback on this PR.
> Add EmulateBrokenEncoding feature

- src/LM_fmt.c
- src/NT_fmt.c
- src/jumbo.c
- src/jumbo.h
- src/misc.c
- src/misc.h
- src/nt2_fmt_plug.c
- src/opencl_lm_fmt_plug.c
- src/opencl_nt_fmt_plug.c
- src/pbkdf2_hmac_common_plug.c
- src/radmin_fmt_plug.c
- src/rawBLAKE2_512_fmt_plug.c
- src/rawKeccak_256_fmt_plug.c
- src/rawKeccak_512_fmt_plug.c
- src/rawMD4_fmt_plug.c
- src/rawMD5_fmt_plug.c
- src/rawMD5flat_fmt_plug.c
- src/rawSHA1_common_plug.c
- src/rawSHA224_fmt_plug.c
- src/rawSHA256_common_plug.c
- src/rawSHA384_fmt_plug.c
- src/rawSHA512_common_plug.c
- src/rawmd5u_fmt_plug.c
- src/sha3_512_fmt_plug.c
- src/skein_fmt_plug.c
- src/stribog_fmt_plug.c
See discussion at the end of #2845, in case of MD5, this resulted in a 25% speedup.
FWIW it passed self-tests on my machine. (Let's see how it does here, as opening a PR is the most obvious way for me to trigger your CI.)
There are still some `*cpy` + `strlwr` combos I was unsure whether they could be transformed, these could be done later by me or other adventurous contributors.
> Merged memcpy and strlwr calls

- src/inc.c
If needed and allowed, increase MaxLen when a valid value of MinLen is specified. Warn otherwise.
> Proposal: increase MaxLen if MinLen is specified and it is > MaxLen

- run/pcap2john.py
- src/tacacs_plus_fmt_plug.c
This fixes https://github.com/magnumripper/JohnTheRipper/issues/1430.
False positives can occur but they don't seem to be frequent (I did not find one during testing). I believe that we can reduce false positives by "decrypting" another "authentication reply" packet.
Sample .pcap files -> https://github.com/kholia/my-pcaps/tree/master/TACACS+
> Add support for cracking TACACS+ hashes

- src/as400_des_fmt_plug.c
- src/axcrypt_fmt_plug.c
- src/chap_fmt_plug.c
- src/lotus85_fmt_plug.c
- src/mysql_netauth_fmt_plug.c
- src/nukedclan_fmt_plug.c
- src/openbsdsoftraid_fmt_plug.c
- src/opencl_o5logon_fmt_plug.c
- src/pwsafe_fmt_plug.c
- src/racf_fmt_plug.c
- src/vnc_fmt_plug.c
I am not sure if this is actually required but I saw weird runtime cracking failures without this patch in `chap` format.
> Clear salt structure before usage

- src/uaf_encode.c
- src/uaf_hash.c
- src/unshadow.c
Compatibility (variable and datatype) changes for older AIX systems.
Parser changes to skip white space in unshadow process.
> AIX compiler compatibility and unshadow skips white spaces

- src/Makefile.in
I was planning to do this after the opencl_* move. Anyway, it is safe.
> Remove all OpenCL references in a non OpenCL build

- run/john.bash_completion
The old logic didn't work for ./john --show=types-[tab] ...
> Fix bash completion for ./john --show=types-json

- src/john.c
We certainly don't want it to have precedence over optimized formats. The old comment about it needing to be registered early (bc of thin formats) does not seem to apply anymore.
> Register dynamic formats last.

- src/XSHA512_fmt_plug.c
- src/XSHA_fmt_plug.c
- src/citrix_ns_fmt_plug.c
- src/common-simd-getpos.h
- src/common-simd-setkey32.h
- src/common-simd-setkey64.h
- src/mysqlSHA1_fmt_plug.c
- src/oracle11_fmt_plug.c
- src/rawMD4_fmt_plug.c
- src/rawMD5_fmt_plug.c
- src/rawSHA1_fmt_plug.c
- src/rawSHA1_linkedIn_fmt_plug.c
- src/rawSHA224_fmt_plug.c
- src/rawSHA256_fmt_plug.c
- src/rawSHA384_fmt_plug.c
- src/rawSHA512_fmt_plug.c
- src/salted_sha1_fmt_plug.c
- src/ssha512_fmt_plug.c
This block of common code, add common GETPOS header.  
It also handles get/set key logic for the complex SIMD formats. The formats NOT added into this code are formats doing complex SIMD mixing, but with unicode passwords.  Also, the complex SIMD mixing code from the HMAC* formats are not here, since that code is pretty much one off, being that the hash type is required to be know within the set_key function (for longer password handling), thus making them non-generic.
> Simd helper code  #2915 GETPOS and set/get key logic

- src/opencl_pem_fmt_plug.c
- src/pem_common.h
- src/pem_common_plug.c
- src/pem_fmt_plug.c
OpenMP makes a good difference to this format as decryption and verification is done on the CPU.
This fixes https://github.com/magnumripper/JohnTheRipper/issues/2940.
On `super`,
```
$  ../run/john --test=2 --format=PEM-OpenCL
Will run 32 OpenMP threads
Benchmarking: pem-opencl, PKCS#8 private key (RSA/DSA/ECDSA) [PBKDF2-SHA1 OpenCL 3DES]... (32xOMP) DONE, GPU util:48%
Raw:	268991 c/s real, 15836 c/s virtual
```
On i7-6600U CPU,
```
$ ../run/john --test --format=PEM
Benchmarking: PEM, PKCS#8 private key (RSA/DSA/ECDSA) [PBKDF2-SHA1 3DES 256/256 AVX2 8x]... (4xOMP) DONE
Speed for cost 1 (iteration count) of 2048 and 2049
Raw:	8827 c/s real, 2485 c/s virtual
```
The GPU utilization rate is not great. It would be great to get 3DES …
> OpenCL support for cracking PEM files

- src/opencl_krb5_asrep_aes_fmt_plug.c
This fixes https://github.com/magnumripper/JohnTheRipper/issues/2819.
On i7-6600U CPU,
```
$ ../run/john --test --format=krb5asrep
Benchmarking: krb5asrep, Kerberos 5 AS-REP etype 17/18/23 [MD4 HMAC-MD5 RC4 / PBKDF2 HMAC-SHA1 AES 256/256 AVX2 8x]... (4xOMP) DONE
Warning: "Many salts" test limited: 36/256
Many salts:	4562 c/s real, 1245 c/s virtual
Only one salt:	4517 c/s real, 1228 c/s virtual
```
On GPU,
```
$ ../run/john --test --format=krb5asrep-aes-opencl
Will run 32 OpenMP threads
Benchmarking: krb5asrep-aes-opencl, Kerberos 5 AS-REP etype 17/18 [PBKDF2-SHA1 OpenCL]... (32xOMP) DONE
Raw:	257003 c/s real, 57996 c/s virtual
```
> Add OpenCL support for cracking AS-REP hashes

- src/configure
- src/configure.ac
- src/x86-64.S
...but neither of BMI1, BMI2, MOVBE and FMA3.
Change ./configure default to *not* use `-march=native` or the like.
Note: 32-bit x86 CPU detection still use the Quick'n'Dirty approach of inferring AVX2 from MOVBE+FMA3 (which is against recommendations but IMHO better than not testing at all).
See #2881, #2764, #2716, #2679, #2674, #2384 and a bunch of others.
> Change run-time CPU detection for AVX2 to actually only check for AVX2

- src/ethereum_common_plug.c
- src/phpassMD5_fmt_plug.c
- src/phpass_common_plug.c
I am not sure about the `phpass` fix but it works fine (TM).
> Fix salt alignment in phpass and ethereum formats

- src/genmkvpwd.c
- src/gpg2john.c
- src/keepass2john.c
- src/mask.c
- src/mask.h
- src/mkv.c
- src/mkvcalcproba.c
- src/mkvlib.c
- src/mkvlib.h
- src/rar2john.c
- src/rar_common.c
- src/rar_fmt_plug.c
- src/unique.c
- src/wordlist.c
This is related to https://github.com/magnumripper/JohnTheRipper/issues/2961.
We can probably drop some explicit typecasts too?
Update:
Probably not.
> Fix warnings in MinGW builds

- src/m4/jtr_x86_logic.m4
- src/test_SIMD.c
Running one CPU detection test on ./configure and another during JtR runtime have been proved a bad idea.
> Use JtR runtime CPU detection in ./configure

- .travis.yml
- .travis/check.sh
* Probably due to its ancient version, gcc is much slower than clang for ASAN.
* No workaround is needed.
> Small tweaks for CI

- src/configure
- src/configure.ac
- src/m4/jtr_asm_magic.m4
- src/m4/jtr_generic_logic.m4
- src/m4/jtr_x86_logic.m4
See #2966, #2972.
I did all the right things in #2975 except I didn't source the M4 so the function was never called.
This works on OSX, let's see what it does to the build bots.
> Fixes for new CPU detection in ./configure (eg. non-Linux)

- src/common.c
- src/common.h
I have tested the three functions and everything is working well.
Thanks
> Rewrite common.c: isdec*() #2951

- src/rsvp_fmt_plug.c
This is related to https://github.com/magnumripper/JohnTheRipper/pull/2989.
After this patch,
```
$ ./jtrts.pl -noprelims  --type rsvp
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, JimF & others
- Testing:  John the Ripper v3-3677-g21e29cd5f OMP [linux-gnu 64-bit AVX2-ac]
--------------------------------------------------------------------------------
John Jumbo build detected.
form=rsvp-md5                     guesses: 1500 0:00:00:00 DONE  [PASSED]
.pot CHK:rsvp-md5                 guesses: 1500 0:00:00:00 DONE  [PASSED] (1500 val-pwd)
form=rsvp-sha1                    guesses: 1500 0:00:00:01 DONE  [PASSED]
.pot CHK:rsvp-sha1                guesses: 1500 0:00:00:00 DONE  [PASSED] (1500 val-pwd) …
```
> Restore new_keys logic for HMAC-SHA1 part in RSVP format

- src/ppc_cpuid.c
The former is not enough. Merging soon.
> Add more macros to check if the program is running on PPC

- src/dynamic_compiler.c
- src/dynamic_compiler_fmt_plug.c
- src/dynamic_fmt.c
- src/formats.c
- src/palshop_fmt_plug.c
This has been a LONG standing issue (in the test_fmt_split_unifies_case_3() function) which gave this error:
```
FAILED (should unify cases in split() and set FMT_SPLIT_UNIFIES_CASE (#3))
```
Due to the false positives, we have moved that logic from --test-full=0 and placed it into --test-full=1 so that the build bots would work.  Well with this fix, all of the false pos are gone. The one REAL problem (dyna_compiler) has been fixed, by making split deal with case.
The first patch does NOT move it back into --test-full=0.  I want to run on build bots first.  Once they are all happy, I will put a 2nd fix out that will move this logic from --test-full=1 and place it into --test-full=0 and make sure the build bots are happy still.  Once that happens we can merge.
> fmt_split_case issue dyna_compiler and --test-full=1

- src/configure
- src/configure.ac
- src/m4/ax_ztex.m4
- src/m4/jtr_arm_logic.m4
- src/m4/jtr_asm_magic.m4
- src/m4/jtr_generic_logic.m4
- src/m4/jtr_ppc_logic.m4
- src/m4/jtr_utility_macros.m4
- src/m4/jtr_x86_logic.m4
- src/x86-64.h
Add --enable-simd=foo option in a way that doesn't add it when building john.o (which may break CPU fallback). And some more clean-up.
> Test some AC enhancements & fixes

- src/configure
- src/configure.ac
In non SIMD builds, it is printing nothing where the CPU name is expected.
```
Target CPU ................................. , 64-bit LE
```
****
Well, to make things clear, maybe:
```
if test -n "$SIMD_NAME"; then
CPU_NAME="$host_cpu $SIMD_NAME"
else
CPU_NAME="$host_cpu no-SIMD"
fi
```
> Fix for non SIMD builds

- .gitattributes
- src/Makefile.in
When downloading an archive from github, there are some files which the user doesn't need and which should be ignored.
There has been confusion regarding version strings for quite some time:
-versions of downloaded git archives appeared to be newer than versions for local git repositories
-version strings for local git repos differed based on not annotated tags in local repositories, compared to the github repository or recently cloned github repositories.
This pull request should address the issues discussed in https://github.com/magnumripper/JohnTheRipper/issues/2481 and https://github.com/magnumripper/JohnTheRipper/issues/3014
> Unify version strings and ignore some files for git archive

- .travis.yml
It is no longer needed (the bug in the previous worker was fixed).
* The new image available for Travis fixed whatever was wrong.
> maint: remove the usage of 2017q3 worker

- doc/README.BitLocker
I am happy with the included `bitlocker2john.c` these days. I can now deprecate my own BitLocker hash extraction program.
CC @e-ago.
> Update README.BitLocker to reflect current state

- src/pp.c
This fixes https://github.com/magnumripper/JohnTheRipper/issues/2961, new warnings reported by @claudioandre.
> Fix warnings by using correct data types and format specifiers

- src/Makefile.in
I agree that seems unusual, but it can happen. The build will fail if there is any '%'.
The error is:
```
options.c:359:9: error: invalid conversion specifier ' ' [-Werror,-Wformat-invalid-specifier]
printf(JOHN_USAGE, name);
^
options.c:301:20: note: expanded from macro 'JOHN_USAGE'
"John the Ripper " JTR_GIT_VERSION _MP_VERSION DEBUG_STRING MEMDBG_STRING ASAN_STRING UBSAN_STRING " [" JOHN_BLD "]\n" \
^
./version.h:1:48: note: expanded from macro 'JTR_GIT_VERSION'
#define JTR_GIT_VERSION JOHN_VERSION "ormat:-%h %ci"
~~^
options.c:359:21: error: format specifies type 'int' but the argument has type 'char *' [-Werror,-Wformat]
printf(JOHN_USAGE, name);
^~~~
options.c:359:9: error: more '%' conversions than data arguments [-Werror,-Wformat]
printf(JOHN_USAGE, name);
^
options.c:305:10: …
```
> Handle a build outside git and archive

- src/x86-64.S
- src/x86-64.h
- src/x86-sse.h
Not sure if something is needed for 32-bit builds
> NT-old: Honor the --disable-simd configure option. Closes #3044.

- src/NETLM_fmt_plug.c
- src/hmacMD5_fmt_plug.c
- src/hmacSHA1_fmt_plug.c
- src/hmacSHA256_fmt_plug.c
- src/hmacSHA512_fmt_plug.c
Variable 'index' is used uninitialized in non-SIMD non-OpenMP builds.
* The style can be improved later (two initializations happening). I'm just fixing a bug.
> Fix for uninitialized variables

- src/idle.c
This commit add support for [Haiku][0], which is an BeOS-inspired operating system
[0]: https://www.haiku-os.org/
> idle: add Haiku support

- src/opencl_openbsdsoftraid_fmt_plug.c
This fixes https://github.com/magnumripper/JohnTheRipper/issues/3021 (Add OpenCL support for OpenBSD-SoftRAID stuff)
Also see PR https://github.com/magnumripper/JohnTheRipper/pull/3052.
A pure GPU format can be done later by improving upon this code.
Current performance,
```
$ ../run/john --test --format=OpenBSD-SoftRAID --cost=1,8192  # i7-6600U CPU
Benchmarking: OpenBSD-SoftRAID (8192 iterations) [PBKDF2-SHA1 256/256 AVX2 8x]... (4xOMP) DONE
Speed for cost 1 (kdf) of 1, cost 2 (iteration count) of 8192
Raw:	2407 c/s real, 706 c/s virtual
```
```
$ ../run/john --test --format=OpenBSD-SoftRAID-OpenCL
Will run 32 OpenMP threads
Benchmarking: OpenBSD-SoftRAID-opencl [PBKDF2-SHA1 OpenCL AES]... (32xOMP) DONE
Raw:	103260 c/s real, 13327 …
```
> Add OpenCL support for OpenBSD-SoftRAID stuff

- src/Makefile.in
* 'git describe' is no longer suitable to use while versioning. The versioning information was added to `param.h` recently.
See #3047
> Remove any tag from the JtR version

- src/Makefile.in
* OpenCL code (kernels and headers) are copied only for an OpenCL build;
* While building binaries, it is reasonable to create an OpenCL build and name it `john-opencl`, then `make clean` to build what will be the `john` binary; [1]
* All OpenCL stuff will be deleted during the `make clean`. A make target to do "the copy" will be a helper tool in this situation.
[1] 1st the OpenCL binary. Then, all fallback binaries, for example.
> Add a make target to copy OpenCL code

- src/common-opencl.c
- src/configure
- src/configure.ac
* realpath(3) is not able to produce the complete path on Windows + CygWin dlls.
* To me, this patch works better.
**[edited]** My fault, I added one unrelated commit. But they can be a set of tweaks.
* Group together all "no" on the configure report (easier to scan).
> Do not use realpath(3) on CygWin

- .gitattributes
- src/Makefile.legacy
- src/jumbo.h
- src/rar_common.c
- src/wpapmk.h
- src/wpapmk_fmt_plug.c
- src/wpapsk.h
- src/wpapsk_fmt_plug.c
Several fixes for legacy builds.
Legacy build warnings (linux-x86-64-native on an AVX system) introduced with commit 136a3e8:
```
rar2john.c: In function 'process_file':
rar2john.c:353:12: warning: format '%llu' expects argument of type 'long long unsigned int', but argument 4 has type 'long unsigned int' [-Wformat=]
"! HEAD_SIZE: %d, PACK_SIZE: %"PRIu64", UNP_SIZE: %"PRIu64"\n",
^
rar2john.c:353:12: warning: format '%llu' expects argument of type 'long long unsigned int', but argument 5 has type 'long unsigned int' [-Wformat=]
rar2john.c:556:40: warning: format '%llu' expects argument of type 'long long unsigned int', but argument 3 has type 'long unsigned int' [-Wformat=]
best_len += sprintf(&best[best_len], "*%"PRIu64"*%"PRIu64"*",
^
rar2john.c:556:40: warning: format '%llu' expects …
```
> Legacy build fixes

- src/multibit_fmt_plug.c
I am not sure about the KDF description text. I need a way to distinguish between the two scrypt based hashes (type 2 and type 3).
> Report tunable costs in multibit format

- run/staroffice2john.py
This program can handle file formats other than `.sxc` too.
Python 3 supported was improved too.
> Rename sxc2john.py to staroffice2john.py

- src/opencl/sspr_kernel.cl
- src/opencl_sspr_fmt_plug.c
- src/sspr_common.h
- src/sspr_common_plug.c
- src/sspr_fmt_plug.c
- src/sspr_variable_code.h
This fixes https://github.com/magnumripper/JohnTheRipper/issues/2901.
I think that faster non-CTX code can be used in the inner loop.
This hashing scheme is not too bad.
> Add OpenCL support for cracking NetIQ SSPR hashes

- src/bitlocker_fmt_plug.c
- src/electrum_fmt_plug.c
- src/external.c
- src/inc.c
- src/logger.c
- src/mscash2_fmt_plug.c
- src/nukedclan_fmt_plug.c
- src/opencl_7z_fmt_plug.c
- src/opencl_DES_bs_plug.c
- src/opencl_dashlane_fmt_plug.c
- src/opencl_electrum_modern_fmt_plug.c
- src/opencl_keystore_fmt_plug.c
- src/opencl_krb5_asrep_aes_fmt_plug.c
- src/opencl_libreoffice_aes_fmt_plug.c
- src/opencl_libreoffice_fmt_plug.c
- src/opencl_pem_fmt_plug.c
- src/opencl_staroffice_fmt_plug.c
- src/pomelo_plug.c
- src/rar2john.c
- src/rawSHA512_common_plug.c
- src/stribog_fmt_plug.c
- src/sunmd5_fmt_plug.c
I always kept the first #include directive, to avoid any breakage.
If there were development guidelines pointing out which dependencies exist between certain includes, I might have kept other #include directives, to keep alphabetic sorting intact, except for such dependencies.
> Remove duplicate #include preprocessor directives

- src/opencl_staroffice_fmt_plug.c
- src/staroffice_common.h
- src/staroffice_common_plug.c
- src/staroffice_fmt_plug.c
The logic added will work for busted AND correct logic SHA1.  Libre is correcting the bug, so we have to handle both flavors.
I reduced the PLAINTEXT length to 51, so that the first part of crypt_all does not have to deal with the bug. If we go above 51 bytes, then we will have to do the BKDF2 code twice (for some passwords). It is more simple to just accept 51 bytes only.
Then, the change is handled in the code after the pbkdf2.  It stores 2 4 byte ints in the binary. Each are just the first 4 bytes of the hash.  They will be the same value for lengths which do not trigger the bug.  BUT if the data object is of a length that triggers the bug, then the 2nd 32 bit value will be a hash using the busted SHA1 code.
Then in cmp_exact, we fully perform the hash, test and possibly re-sha1 with …
> Star/Libre Office. Handle their buggy SHA1 logic (optional)

- src/x86-sse.h
- src/x86.S
Take two. I managed to test this with a virtual machine with cpuid masks, I believe this one really fixes the problems. @claudioandre please test, and merge if it works.
The 32-bit cpuid assembler code is friggin' obfuscated code, with `xchgl` back and forth and push/pop. Very hard to follow through all `#ifdef`'s.
> Bugfix for 32-bit SSE4.1 and SSSE3 detection

- run/electrum2john.py
In electrum2john.py, the error message for unsupported Electrum seed version contains a small bug.
> electrum2john.py - Fix error due to unassigned variable

- run/ansible2john.py
- src/ansible_common.h
- src/ansible_common_plug.c
- src/ansible_fmt_plug.c
I am still working on,
* Avoiding `cracked` logic (DONE)
* OpenMP tuning (DONE according to https://github.com/magnumripper/JohnTheRipper/issues/3091)
* GPU format. Do we have HMAC-SHA256 on the GPU?
I might leave the GPU support for a new PR.
> Add support for cracking Ansible Vaults

- src/options.c
john options were referring to "doc/ENCODING" but actual file currently named as "doc/ENCODINGS"
> encodings file name

- run/dynamic.conf
- run/telegram2john.py
This fixes https://github.com/magnumripper/JohnTheRipper/issues/3183.
The passcode length is limited to 4. So no GPU support is needed ;)
@Banaanhangwagen You might be interested in this. Thanks for your work on this topic!
> Add support for cracking Telegram (Android) hashes

- run/hccapx2john.py
This is to replace hccap2john.c, also add support for AP nonce correction and message_pair flags for BE/LE and ap-less attack, where nonce corrections are not needed.
> Add new tool hccapx2john.py

- src/opencl_rawsha512_gpl_fmt_plug.c
```
$ ../run/john  -format:mask -list=formats
../run/john: /usr/local/cuda-8.0/targets/x86_64-linux/lib/libOpenCL.so.1: no version information available (required by ../run/john)
oldoffice-opencl, descrypt-opencl, krb5pa-md5-opencl, LM-opencl, 
mscash-opencl, mysql-sha1-opencl, nt-opencl, ntlmv2-opencl, Raw-MD4-opencl, 
Raw-MD5-opencl, Raw-SHA1-opencl, Raw-SHA256-opencl, Raw-SHA512-opencl, 
salted-sha1-opencl, SL3-opencl, XSHA512-opencl
```
> mask: add FMT_MASK flag to raw-SHA512-opencl

- run/pem2john.py
- src/opencl_pem_fmt_plug.c
- src/pem_common.h
- src/pem_common_plug.c
- src/pem_fmt_plug.c
This fixes https://github.com/magnumripper/JohnTheRipper/issues/3197.
The OpenCL format needs more attention with regards to OUTLEN (outlen) optimization.
> Add support for more ciphers in PEM format

- run/john.conf
Following the comment from some company claiming they can get passwords
typed from a phone call via T9.
There was a discovery that Fidelity investment was doing that kind of password conversion to be able to get passwords typed by phone.
I've successfully run this rule against Troy Hunt pwned password lists and found a few hundreds.
I think List.Rules:Extra is a good place don't hesitate to tell me if there's a better one.
> Add a cracking rule that converts words in t9

- run/aem2john.py
- src/opencl_sspr_fmt_plug.c
- src/sspr_common.h
- src/sspr_common_plug.c
- src/sspr_fmt_plug.c
I can't benchmark the hash(es) with an iteration count of 1000.
```
✗ ../run/john --test --format=sspr --cost=3,1000 
Benchmarking: sspr, NetIQ SSPR / Adobe AEM [MD5/SHA1/SHA256/SHA512 32/64]... DONE
Speed for cost 1 (KDF [0:MD5 1:SHA1 2:SHA1_SALT 3:SHA256_SALT 4:SHA512_SALT]) of 3, cost 2 (iteration count) of 100000
Warning: "Many salts" test limited: 14/256
Many salts:	53.3 c/s real, 53.3 c/s virtual
Only one salt:	53.8 c/s real, 53.8 c/s virtual
```
Am I invoking the `--cost` parameter correctly?
> Add support for cracking Adobe AEM hashes

- CONTRIBUTING.md
I'm not 100% sure, but it seems that if we add this file (its content can be improved, I know) the issue window will have a better/clearer header text.
> docs: add guidelines for contributing

- src/opencl_geli_fmt_plug.c
- src/opencl_keyring_fmt_plug.c
- src/opencl_keystore_fmt_plug.c
- src/opencl_krb5pa-md5_fmt_plug.c
- src/opencl_krb5pa-sha1_fmt_plug.c
- src/opencl_lotus5_fmt_plug.c
- src/opencl_ntlmv2_fmt_plug.c
- src/opencl_o5logon_fmt_plug.c
- src/opencl_office_fmt_plug.c
- src/opencl_oldoffice_fmt_plug.c
- src/opencl_pgpdisk_fmt_plug.c
- src/opencl_pgpsda_fmt_plug.c
- src/opencl_pgpwde_fmt_plug.c
> Use new scheme of LWS=NULL for less-than-full batches instead of rounding GWS up to LWS multiple.

- run/signal2john.py
- src/signal_fmt_plug.c
This cracks Signal Android app passphrases.
Notes, 
+  Modern versions of Signal do not support using a passphrase.
+ This was tested with Signal Android app version 4.13.5 only.
+ Run against `/data/data/org.thoughtcrime.securesms/shared_prefs/SecureSMS-Preferences.xml` file.
+ In modern version of Signal Android app (e.g. 4.19.3), the "Screen lock" code seems to be stored in plaintext in SecureSMS-Preferences.xml file
> Add support for cracking Signal passphrases

- src/gpg2john.c
- src/gpg_common_plug.c
This is related to https://github.com/magnumripper/JohnTheRipper/issues/3273 (Add support for cracking very old GPG keys).
> [GPG] Avoid incorrect processing of very old GPG keys

- run/network2john.lua
This is untested as we don't have a suitable .pcap file. Also, it is not trivial to generate a suitable .pcap file!
This is related to https://github.com/magnumripper/JohnTheRipper/issues/3275 (Add support for cracking DHCP authentication).
> Add support for cracking DHCPv4 authentication

- run/bitcoin2john.py
- src/bitcoin_fmt_plug.c
I have only tested this lightly.
This is related to https://github.com/magnumripper/JohnTheRipper/issues/3139 (Need less revealing *2john "hashes" for cryptocoin wallets & encrypted archives).
> Generate less revealing hashes for Bitcoin wallets

- run/telegram2john.py
- src/aes_ige.h
- src/aes_ige_plug.c
- src/telegram_common.h
- src/telegram_common_plug.c
- src/telegram_fmt_plug.c
TODO: OpenMP tuning stuff
Speed,
```
$ ../run/john --test --format=telegram  # i3-4005U CPU
Benchmarking: telegram [PBKDF2-SHA1 256/256 AVX2 8x AES]... (4xOMP) DONE
Speed for cost 1 (iteration count) of 4000
Warning: "Many salts" test limited: 2/256
Many salts:	867 c/s real, 230 c/s virtual
Only one salt:	898 c/s real, 227 c/s virtual
```
CC @MihaZupan.
This fixes #3280.
> Add support for cracking Telegram Desktop passcodes

- src/opencl/telegram_kernel.cl
- src/opencl_aes.h
- src/opencl_telegram_fmt_plug.c
NOTE: This needs to be converted to a pure OpenCL kernel before it can be merged. I might not be able to get this done soon.
@magnumripper I am still weak at writing (and debugging!) low level crypto primitives. Would it be possible for you to port the AES IGE stuff to OpenCL?
> OpenCL support for cracking Telegram Desktop passcodes

- src/FG2_fmt_plug.c
Fortigate passwords can also be stored in this format:
SH2|base64encode(salt|SHA256(salt|password|fortinet_magic))
> Support for FortiGate SHA256 format

- src/opencl/sap_pse_kernel.cl
- src/opencl_sappse_fmt_plug.c
- src/sap_pse_common.h
- src/sap_pse_common_plug.c
- src/sap_pse_fmt_plug.c
This fixes https://github.com/magnumripper/JohnTheRipper/issues/3302 (Add support for cracking SAP's PSE files with PBES1-3DES-SHA1).
```
$ ../run/john --test --format=sappse-opencl 
Device 2: AMD Radeon Pro 560 Compute Engine
Benchmarking: sappse-opencl, SAP PSE - PKCS12 PBE [SHA1 OpenCL]... DONE
Speed for cost 1 (iteration count) of 2048
Raw:	177124 c/s real, 19660K c/s virtual
```
```
$ ../run/john --test --format=sappse-opencl
Device 6: GeForce GTX TITAN X (Maxwell)
Benchmarking: sappse-opencl, SAP PSE - PKCS12 PBE [SHA1 OpenCL]... DONE
Speed for cost 1 (iteration count) of 2048
Raw:	761856 c/s real, 746917 c/s virtual, GPU util: 98%
```
> Add OpenCL support for cracking SAP's PSE files

- src/opencl/tezos_kernel.cl
This should fix the problems discovered in https://github.com/magnumripper/JohnTheRipper/pull/3317 (Add OpenCL support for cracking Tezos keys).
> Fix the size of salt buffer in Tezos kernel

- run/DPAPImk2john.py
Fix a formatting bug in DPAPImk2john.py's display_masterkey that strips leading 0 chars in GUID parts.
> Fix preferred master key display in DPAPImk2john.py

- src/ethereum_fmt_plug.c
- src/pbkdf2_hmac_sha256.h
Before,
```
$ ../run/john --test --format=ethereum --cost=0,2 
Benchmarking: ethereum, Ethereum Wallet [PBKDF2-SHA256/scrypt Keccak 256/256 AVX2 8x]... (4xOMP) DONE
Speed for cost 1 (iteration count) of 2000, cost 2 (kdf [0:PBKDF2-SHA256 1:scrypt 2:PBKDF2-SHA256 presale]) of 2
Many salts:	259548 c/s real, 65536 c/s virtual
Only one salt:	1267 c/s real, 319 c/s virtual
```
After,
```
$ ../run/john --test --format=ethereum --cost=0,2
Benchmarking: ethereum, Ethereum Wallet [PBKDF2-SHA256/scrypt Keccak 256/256 AVX2 8x]... (4xOMP) DONE
Speed for cost 1 (iteration count) of 2000, cost 2 (kdf [0:PBKDF2-SHA256 1:scrypt 2:PBKDF2-SHA256 presale]) of 2
Many salts:	614400 c/s real, 167868 c/s virtual
Only one salt:	4448 c/s real, 1218 c/s virtual
> Add SIMD support for cracking Ethereum Presale wallets

- src/charset.c
- src/charset.h
The Fedora Rawhide (or 27) MinGW GCC won't be happy with this reversion. I am working on finding away to make the CI happy as well.
This fixes issue #3333.
> Fix recent incorrect buffer resizing in charset handling code

- .travis/check.sh
- src/SIPdump.c
- src/c3_fmt.c
- src/configure
- src/configure.ac
- src/django_scrypt_fmt_plug.c
- src/dynamic_compiler.c
- src/dynamic_fmt.c
- src/mysql_netauth_fmt_plug.c
- src/scrypt_fmt.c
- src/truecrypt_fmt_plug.c
- src/undrop.c
I am introducing changes to silence GCC warnings. The changes to `configure` file were done by running `autoreconf`.
Next, I will start reverting the wrong changes I introduced in commit bf2048be86c352efdd02b107687a464937c81bd3.
It would be great if we can remove these warning silencing hacks at some point. I will start looking into this.
> Ignore GCC 8's -Wstringop-truncation warning

- src/dynamic_compiler.c
This is related to https://github.com/magnumripper/JohnTheRipper/issues/3339 (Review use of strncpy / strncat and the like).
GCC 8 doesn't like such a `strncpy` construct. I don't know if I still care about satisfying GCC 8 ;(
Tested with,
* ./jtrts.pl -type dynamic_39
* ./jtrts.pl -type dynamic_40
* ./jtrts.pl -type dynamic_1010
> Drop redundant memset zero padding before strncpy

- src/configure
- src/configure.ac
- src/m4/jtr_utility_macros.m4
This has to be implemented by checking if `-Wfoo` is supported because the `no-` forms will soft-fail.
> Autoconf: Add a way to check if -Wno-foo is supported.

- run/office2john.py
I added some conditional PY3 checks to facilitate backwards compatibility.
Anywhere there was a decodestring there is now a decodebytes option for PY3.
Fixes #3345 
**NOTE:** I noticed that this code needed to be changed in two places where I saw identical code blocks. This has a code duplication smell. That section should be made in to a subroutine that is called from those 2 spots.
> decodestring vs. decodebytes: Confirmed compatibility with Python 2.6 & 2.7

- doc/INSTALL-UBUNTU
This is required on Debian 9 and modern Ubuntu installations.
> Install zlib1g-dev package explicitly on Ubuntu (and Debian)

- src/bitlocker2john.c
The additional AES offset is not enabled until we can't prove that it is correct.
This is essentially https://github.com/magnumripper/JohnTheRipper/pull/3293 (bitlocker2john code reworked).
I am trusting @e-ago in this PR to do the right thing.
> Code reworked - added two different salt and aes offsets

- src/opencl/wpapsk_kernel.cl
- src/opencl_wpapmk_fmt_plug.c
- src/opencl_wpapsk_fmt_plug.c
- src/wpapmk.h
- src/wpapmk_fmt_plug.c
- src/wpapsk.h
- src/wpapsk_fmt_plug.c
Bot check. This is less of a hack than I fear it would be. We should unify more of WPAPSK and WPAPMK code but that's a separate issue.
> WPAPSK and -PMK formats: Add support for PMKID. Closes #3356.

- run/pcap2john.py
With this PR, installing the required packages (libraries) should be easier and safe (no root access required).
This PR is related to https://github.com/magnumripper/JohnTheRipper/issues/3382 (pcap2john.py is not user-friendly).
> Make pcap2john.py easier to deploy

- src/opencl/sspr_kernel.cl
- src/opencl_aes.h
- src/opencl_rawsha256.h
- src/opencl_rawsha512.h
- src/opencl_sha256crypt.h
- src/opencl_sha512crypt.h
Some buggy AMD/clang runtime seems to have problem with it. Closes #3387.
> OpenCL: Avoid anonymous unions.

- src/fvde_common.h
- src/fvde_common_plug.c
- src/fvde_fmt_plug.c
- src/notes_common.h
- src/notes_common_plug.c
- src/opencl/fvde_kernel.cl
- src/opencl_fvde_fmt_plug.c
- src/opencl_notes_fmt_plug.c
This fixes https://github.com/magnumripper/JohnTheRipper/issues/3267 (Modify FVDE mode to accept length 40 blob).
CC @trounce1, can you please test this PR?
Notes,
* Use https://github.com/kholia/apfs2john to extract hashes.
Usage,
```
$ sudo ./bin/apfs-dump-quick /dev/sdc1 log.txt 
Device /dev/sdc1 opened. Size is 1000304128
starting LoadKeybag
all blocks verified
Volume openwall is encrypted.
starting LoadKeybag
all blocks verified
Hint: Openwall
starting LoadKeybag
all blocks verified
!!!!!!!
$fvde$2$16$0d7426917b673738a1e39c987ec0f477$181461$...
!!!!!!!
```
Update: This steps may / may not work for system volumes.
> Add support for cracking APFS FVDE volumes

- doc/INSTALL
- src/configure
- src/configure.ac
- src/m4/jtr_utility_macros.m4
To achieve this I had to disable pkg-config by default, because it's broken. Actually I can't remember having seen a non-broken pkg-config in my entire life so it's probably a good thing in most cases but it might break some other system so you'd have to add --enable-pkg-config to the configure options.
This hopefully addresses #2347.
We need to test this on a few places before merging.
> AC: Find OpenSSL on macOS Homebrew without any special options.

- run/lib/PDF.pm
I have a few PDF documents which crack just fine after this warning/error is disabled.
> Relax parsing in pdf2john utility

- doc/README-ZTEX
- src/ztex/device.c
- src/ztex_md5crypt.c
- src/ztex_phpass.c
- Increased PLAINTEXT_LENGTH for phpass-ztex to 64, tested on a hash provided by Solar;
- In md5crypt-ztex, removed dummy "iteration count" tunable cost from a view of a user, let it pass "silently" to fpgas, without a modification of bitstream's application-level input packet processing unified for both "formats";
- Reviewed where it sets programmable clocks' frequency on fpga's "soft" reset (Global Set Reset, GSR).  Internal programmable clock sources (DCMs, PLLs) don't reset with GSR. It sets: if it finds "Frequency" in ```john.conf``` then it sets given frequency, else uses frequency value from ```struct device_bitstream```. Everything seems correct.
- Minor corrections.
> improvements to md5crypt-ztex, phpass-ztex

- src/ztex/device.c
- src/ztex/device_format.c
- src/ztex/device_format.h
- src/ztex/jtr_device.c
- src/ztex/task.c
- src/ztex/task.h
- src/ztex_bcrypt.c
- src/ztex_descrypt.c
- src/ztex_drupal7.c
- src/ztex_md5crypt.c
- src/ztex_phpass.c
- src/ztex_sha256crypt.c
- src/ztex_sha512crypt.c
- Use of verbosity. With -v=4 it prints mask size, keys_per_crypt on ```reset()```. With -v=5 it prints every ```crypt_all``` call with result count.
- Indexing the list of results (```struct task_result_list```) collected in ```crypt_all()```. With ```--test```, ```--test_full=1``` it sometimes (on a pseudo-random fashion) returns large number of results, sometimes >60K in 1 crypt_all, unless indexed it looks like it hangs (takes tens of seconds of CPU time to process).
- Reviewed parameters in some ztex format to better fit tests. Still there're questions - if tests properly represent various real uses and corner cases? And it also raises questions on how tests operate, e.g. for sha512crypt-ztex ```test-full=1``` runs crypt_all with max.number of keys 10 times, for Drupal7-ztex 4 times, …
> various ztex improvements

- src/configure
- src/configure.ac
See https://github.com/magnumripper/JohnTheRipper/pull/3439#issuecomment-432281202
Autoconf:
- Change  `-Wno-stringop-truncation` to `-Wno-error=stringop-truncation`
- Add `-Wno-error=format-overflow`.
NOTE that this make the warnings reappear - it just stops build from failing due to `--enable-werror`. Is this the way to go? I'd rather not suppress the warnings. Comments appreciated.
> Tweak error/warning handling in gcc-8

- src/adxcrypt_fmt_plug.c
This is related to https://github.com/magnumripper/JohnTheRipper/issues/3438 (Formats failing on non-x86 ).
> Enable ADXCRYPT to run on BE (e.g. mips64) machines

- src/opencl/solarwinds_kernel.cl
- src/opencl_solarwinds_fmt_plug.c
- src/solarwinds_common.h
- src/solarwinds_common_plug.c
- src/solarwinds_fmt_plug.c
Current speed,
```
$ ../run/john --format=solarwinds-opencl --test
Benchmarking: solarwinds-opencl, SolarWinds Orion [PBKDF2-SHA1 OpenCL]... DONE
Raw:	45936 c/s real, 46369 c/s virtual, GPU util: 99%
```
CPU speed,
```
$ ../run/john --format=solarwinds --test
Will run 32 OpenMP threads
Benchmarking: solarwinds, SolarWinds Orion [PBKDF2-SHA1 128/128 AVX 4x]... (32xOMP) DONE
Raw:	3200 c/s real, 103 c/s virtual
```
The GPU utilization percentage is decent.
> Add support for cracking SolarWinds Orion hashes

- run/openssl2john.py
- src/openssl_enc_fmt_plug.c
Sometimes you don't know any part of the plaintext, but the plaintext is mostly ascii characters. 
With this patch, you can define the ascii threshold.
> format openssl-enc. Implement ascii percentage check.

- src/opencl_common.c
MESA was reported as Crimson driver.
> OpenCL: fix AMD driver info

- doc/RULES
- src/rules.c
@solardiz is the `#` character OK or do you have a better suggestion? For `min_length` there doesn't seem to be need for the additional +/- 1 constants that max_length have, does it? If we need them later I was thinking `@` for `min_length - 1` and `$` for `min_length + 1`. as the three then come in sequence on many keyboards.
> Expose min_length constant in rules

- src/opencl_common.c
Fix HEAD. JtR can run if the OpenCL build lock is failing. No reason to abort.
After this patch, a message will be printed, but JtR will work (as it used to before
> Stop aborting on lock error #3482

- src/racf_kdfaes_fmt_plug.c
Support for KDFAES RACF hashes.
This fixes https://github.com/magnumripper/JohnTheRipper/issues/2511 (Support RACF KDFAES hashes).
Note: This is a reference implementation. A usable, GPU implementation will be coming up in the future.
> Add support for RACF KDFAES hashes (v0.15)

- src/john.c
- src/opencl_common.c
- src/opencl_common.h
- src/options.c
I tested it like this:
```
rm -f ../run/pot; ../run/john -form:SHA256crypt-opencl alltests.in -incremental -max-run=30 -fork=2            #OK
rm -f ../run/pot; ../run/john -form:SHA256crypt-opencl alltests.in -incremental -max-run=30 -fork=2 -dev=0,1,2 #error 
rm -f ../run/pot; ../run/john -form:SHA256crypt-opencl alltests.in -incremental -max-run=30 -fork=2 -dev=6     #OK
rm -f ../run/pot; ../run/john -form:SHA256crypt-opencl alltests.in -incremental -max-run=30 -fork=2 -dev=6,7   #OK
rm -f ../run/pot; ../run/john -form:SHA256crypt-opencl alltests.in -incremental -max-run=30 --fork=3 -dev=1,2   #OK
rm -f ../run/pot; ../run/john -form:SHA256crypt-opencl alltests.in -incremental -max-run=30          -dev=1,2,3 #error 
rm -f ../run/pot; ../run/john -form:SHA256crypt-opencl alltests.in …
```
> OpenCL versus Fork validation

- src/opencl_rawsha256_fmt_plug.c
- src/opencl_rawsha512_gpl_fmt_plug.c
> OpenCL: xSHA512 lacks proper binary_hash()

- src/dynamic_fmt.c
- src/dynamic_types.h
ties to #3417  Possibly #2425 
NOTE, may not be ready to merge.  @magnumripper has worked out some debugging code, and I think there may still be an issue when single mode completes, and all the partial buckets are run.  I think the last array element may still exhibit the problem, and may take some additional work.  
HOWEVER, what we found was dynamic 'min_keys_per_crypt' was hard coded to 64.  This did not work all the time. Prime example was AVX2 md5.  Here SIMD32 was 8, and SIMD_PARA was 3. That means each SIMD block was 24.  24 does not evenly divide into 64.  Thus, the code would clear 64 buffers, BUT later code uses full buffer counts (which in this case were 72).  SO the last 8 buffers would get data appended to them, but NEVER properly reset between runs.  So those 8 buffers …
> fixed dynamic overflows in single mode

- src/opencl/cryptsha512_kernel_GPU.cl
> OpenCL: tune sha512crypt for Intel

- src/configure
- src/m4/jtr_utility_macros.m4
Without this patch, configure needs to be called with additional arguments.
This patch is made to be similar to the surrounding lines.
> configure: detect openssl installed by MacPorts on macOS

- src/HDAA_fmt_plug.c
RFC 7616 section 3.4 does not put such constraints on cnonce: it specifies that cnonce is ASCII-only (we may want to check this property, but I don't see why john should reject invalid cnonce values).
The examples of RFC 7616 section 3.9.1 contain non-hex values for nonce and cnonce.
Note that RFC 7616 section 3.3 recommends that the nonce is Base64 or hexadecimal data, but it is not mandatory.
> HDAA: remove check that cnonce is lowercase hex

- src/common.c
- src/common.h
- src/jumbo.c
- src/jumbo.h
- src/misc.c
- src/misc.h
- src/sap_pse_common_plug.c
Here are changes to common.[ch] and misc.[ch] which have been triggered by findings from within the unit-tests project.
Also, one format was changed (it's valid).  It was the only format not handling the change to ishex("") now returning false (prior logic returned true).
There was also a change made in jumbo.[ch] but only for a VC build, and only for VC 2015 or newer.  2015 fixed the snprintf function (leaving the older 'busted' logic in the _snprintf function).  Now, (v 2015), the snprintf works properly, and having a wrapper varargs function to handle it makes things more complex.
There is a comment in the first commit, that lists all things changed.
> Common.[ch] and misc.[ch] changes

- src/misc.c
This is required for 32 bit builds (where size_t is not 64 bits).
> fixed bullet-proof code to not core on 32 bit builds

- src/sapB_fmt_plug.c
- src/sapG_fmt_plug.c
Doing arithmetic on the contents of a void pointer is not defined (or at least NOT portable).  I believe this is an implementation defined operation (vs undefined), but in the same case, this is not portable.
This all falls down to this (and what the sizeof actually is
```c
#include <stdio.h>
int get_size(void *p) {
return sizeof(p[0]);
}
int main() {
printf ("size of void object is:  %d\n", get_size(0));
}
```
This compiles on gcc and VC.  Gcc returns sizeof void object as 1.  VC returns its size as 0 (which 0 REALLY is correct, as per the C standard).
I did find this:   https://www.geeksforgeeks.org/void-pointer-c-cpp/   ``` 2) The C standard doesn’t allow pointer arithmetic with void pointers. However, in GNU C it is allowed by considering the size of void is 1 ```   and this: …
> using void* in arithmetic is not valid, even though gcc extension allows

- src/params.h
- src/unique.c
Anyone please test this out and optionally review. Basically the change was merely switching from `unsigned int` to `size_t` which allows for arbitrarily large data buffer/hash sizes if `sizeof(size_t) >= 8`.
Some new/revised options as well:
```
Usage: unique [-v] [-inp=FILE] [-cut=N] [-log=N] [-[max-]mem=N] OUTPUT-FILE [-ex_file[_only]=FILE
-v                 verbose mode, output stats before each slow pass (if any)
-inp=FILE          read from FILE instead of stdin
-cut=N             truncate input lines to N bytes
-cut=LM            for LM: Split lines longer than 7 in two, and uppercase
-hash-size=N       override the hash size (given in log2). The default is
25 for 2304 MB, memory use doubles for each increment
-buf=N             Total allowed buffer size, in GB. If -hash-size isn't …
```
> unique: Add 64-bit support, for large buffers/hash tables, and other tweaks.

- src/opencl/cryptmd5_kernel.cl
This fixes the problem described in https://github.com/magnumripper/JohnTheRipper/pull/3622#issuecomment-459312997
Also, the `-test -mask` speed improves with this change, but I'm not sure what this is actually benchmarking because the speed doesn't change as I'd have expected it to with different mask lengths (I am getting the same high speed for much longer masks, which is unrealistic, and even for mask lengths exceeding 15, which is this format's max). Perhaps our `-test -mask` is broken.
```
[solar@super run]$ rm -r ~/.nv/ComputeCache
[solar@super run]$ LWS=256 GWS=10240 ./john -test=10 -form=md5crypt-opencl -dev=3 -v=5 -mask='?a?a?a?a?a?a?a' 
initUnicode(UNICODE, ASCII/ASCII)
ASCII -> ASCII -> ASCII
Device 3: GeForce GTX 1080
Benchmarking: md5crypt-opencl, crypt(3) $1$ [MD5 …
```
> md5crypt-opencl: choose slow path on len >= 10*4*8 instead of on x[9]

- src/opencl/cryptmd5_kernel.cl
The below description is edited to reflect extra commits pushed to this PR.
Since our private array variables are effectively in cached global memory, it makes sense to minimize accesses to them (more so than to minimize the amount of memory allocated, which has only indirect effect on speed through changes in locality of reference). Included in this PR are three relevant commits where one packs the contents of 2 tiny used-to-be arrays into 3 32-bit registers just before the main loop (the former "array elements" are then extracted by the loop using shifts and masks), another further reduces the number of reads from the current MD5 input buffer for commonly seen input lengths (there's no need to read zeroes beyond the filled length, and we can also infer when we'd read the 0x80 padding …
> Further md5crypt-opencl optimizations

- src/opencl/cryptmd5_kernel.cl
Much better speeds at length 8:
```
[solar@super run]$ rm -r ~/.nv/ComputeCache; ./john -form=md5crypt-opencl -dev=0,3,4,5 -fork=4 pw-md5crypt-diffsalt -v=4 -mask='?a?a?a?a?a?a?a?a'
Using default input encoding: UTF-8
Loaded 1000 password hashes with 1000 different salts (md5crypt-opencl, crypt(3) $1$ [MD5 OpenCL])
Node numbers 1-4 of 4 (fork)
Device 0: gfx900 [Radeon RX Vega]
Device 5: GeForce GTX TITAN
Device 4: GeForce GTX TITAN X
Device 3: GeForce GTX 1080
1: Local worksize (LWS) 64, global worksize (GWS) 32768 (512 blocks)
Press 'q' or Ctrl-C to abort, almost any other key for status
4: Local worksize (LWS) 128, global worksize (GWS) 172032 (1344 blocks)
2: Local worksize (LWS) 32, global worksize (GWS) 163840 (5120 blocks)
3: Local worksize (LWS) 32, global worksize (GWS) 1572864 …
```
> md5crypt-opencl: Further specialization for password length 8

- doc/README-ZTEX
- run/john.conf
- src/ztex/Makefile.in
- src/ztex/device_format.c
- src/ztex/ztex.c
- src/ztex/ztex.h
- src/ztex/ztex_scan.c
- src/ztex/ztex_sn.c
- src/ztex/ztex_sn.h
Each board has a factory programmed Serial Number (SN). JtR displays
SNs on startup and in information/error messages. To hide SNs, you can
list SNs of your boards in [List.ZTEX:Devices] section in john.conf.
Board numbers (starting from 1) will appear instead of SNs. You can
specify these numbers in --dev command-line option.
> [List.ZTEX:Devices] - ability to hide Serial Numbers

- src/sip_fmt_plug.c
Wrong comment statement which may confuse: NONCE_COUNT should go prior to CNONCE
RFC: https://tools.ietf.org/html/rfc2617#section-3.2.2.1
request-digest  = <"> < KD ( H(A1),     unq(nonce-value)
":" nc-value
":" unq(cnonce-value)
":" unq(qop-value)
":" H(A2)
The code which actually concatenates the values however is correct:
snprintf(salt.static_hash_data, STATIC_HASH_SIZE, ":%s:%s:%s:%s:%s",
login.nonce, login.nonce_count, login.cnonce,
login.qop, static_hash);
> [SIP] Wrong comment statement which may confuse

- src/ztex/ztex_scan.c
- src/ztex_drupal7.c
- allow to specify SN in ```-dev``` cmd-line option if board is listed in config; 
- drupal7 min_keys value to reflect new bitstream (makes 1% performance difference)
> ZTEX: small corrections

- doc/INSTALL-UBUNTU
Removes the `$ ` prompt for two commands. I think this is appropriate because none of the earlier commands include the `$ ` prompt.
> Fixes command line prompt ambiguity

- src/Makefile.in
The unit-tests isn't built by `make` nor by `make check`.
> Build unit-tests on `make check`

- run/keystore2john.py
Make it work with both by adding .decode('utf-8')
to hexlified data. Python2 thinks it has type 'str'
and python3 treats it as 'bytes'. After decode()
both think it has type 'str'.
This should fix issue #3658 .
> keystore2john.py: Python2/3 compatibility

- src/cracker.c
I think this is more or less exactly as suggested, no reason to make it more complicated.
> cracker.c: Detect when a reset() call lowered min. kpc, adjust warnings accordingly

- src/config.c
JtR uses the `fopen:` as a pattern for this kind of error message. For now just path_expand() the file name before printing it.
``` 
Found 15 matches of fopen: in 10 files.	
charset.c	
pexit("fopen: %s", path_expand(charset));      [position 643:10]	
config.c	
pexit("fopen: %s", path_expand(cfg_name));      [position 244:11]	
cracker.c	
pexit("fopen: %s", path_expand(options.activepot));      [position 619:10]	
fuzz.c	
pexit("fopen: %s", options.fuzz_dic);      [position 99:10]	
pexit("fopen: %s", status_file_path);      [position 536:10]	
pexit("fopen: %s", file_name);      [position 617:10]	
inc.c	
pexit("fopen: %s", path_expand(charset));      [position 618:10]	
loader.c	
pexit("fopen: %s", path_expand(name));      [position 216:10]	
pexit("fopen: %s", name);      [position 1376:12] …
```
> Clarify the error `fopen: $JOHN/john.conf`

- src/path.c
As it is now, `cfg_init()` misbehaves when a file name contains directory components. To fix that and handle both situations (file names with and without directory information), the use of `basename()` is needed.
See https://github.com/magnumripper/JohnTheRipper/pull/3681#issuecomment-475896251
> Stop duplicating the path in cfg_init()

- src/Makefile.in
- src/Makefile.legacy
- src/subsets.c
- src/unicode_range.c
- src/unicode_range.h
unicode_range.c: Work around brain-dead clang claiming to be compatible with gcc despite it isn't. Closes #3691
> unicode_range.c: Work around brain-dead clang

- src/config.c
- src/john.c
- src/path.c
- src/path.h
Well, in my opinion, this is the way to go. I dislike the idea of changing `$JOHN`and I want to kill `*_ex()`.
```
Tested:
$ ../run/john --test=0 --config=../run/john.ini           # renamed john.conf
Testing: [...]   # => Works
$ ../run/john --test=0 --config=\$JOHN/john.ini           # renamed john.conf
Testing: [...]   # => Works
$ ../run/john --test=0 --config=../abc/config.ini         # wrong conf file name
fopen: ../abc/config.ini: No such file or directory
$ ../run/john --test=0                                    # missing john.conf
fopen: ../run/john.conf: No such file or directory
```
> Take 2: modify cfg_name inside cfg_init() cautiously

- src/opencl_common.c
As seeing in https://github.com/magnumripper/JohnTheRipper/blob/bleeding-jumbo/src/opencl_common.c#L1219
> OpenCL: mute a warning on Windows

- src/cracker.c
- src/single.c
I opted to say "base candidates" when mask accel is in effect, see #3718
> Cosmetic fixes, #3718

- src/ztex_md5crypt.c
- src/ztex_sha256crypt.c
- src/ztex_sha512crypt.c
- Discussed in #3721
- If password file contains only hashes with zero salt length, John reverts to CPU version.
- After the fix included in the next hardware design versions, the warning will be removed.
> {sha256|sha512|md5}crypt-ztex: salt_len=0: warning, don't process

- run/benchmark-unify
- run/relbench
There are many changes between 1.8.0-jumbo-1 and bleeding-jumbo which cannot be mapped, e.g. changes from Raw to many salts / Only one salt and vice versa.
That also means, some of the performance regressions will not be seen.
> relbench fix and benchmark-unify adjustments

- src/opencl_common.c
For tuning, use the largest of these:
- mask_add_len (if -mask)
- options.req_maxlength (if set, and min not set)
- options.req_minlength (if set, and max not set)
- self->params.benchmark_length & 0x7f
For J2, maybe.
> OpenCL: tune for the length a run will be using

- src/bench.c
- src/mask.c
- src/mask.h
without calling mask_init().  Use said function when benchmarking
with mask, for getting a proper (length n) message.  See #3780.
> mask.c: Export a function for evaluating mask_add_len from a mask

- src/ansible_fmt_plug.c
- src/drupal7_common.h
- src/phpassMD5_fmt_plug.c
- src/racf_kdfaes_fmt_plug.c
- src/wpapsk.h
With this, all formats (except for "monero", now disabled) passed `-test` for me on sparc64. (Of course, it's always possible some of the remaining formats passed test by lucky rather than guaranteed alignment.)
> Fix some unaligned accesses, enhance some salt_hash()

- src/SIPdump.c
- src/eapmd5tojohn.c
> SIPDump and eapmd5tojohn: source <getopt.h> instead of declaring extern optind.

- src/7z_fmt_plug.c
> 7z: stop to modify the caller's key in set_key()

- src/bench.c
- src/formats.h
- src/gost_fmt_plug.c
- src/haval_fmt_plug.c
Fixes #3819.
Let's _not_ squash these commits.
> Benchmark fixes; Unbreak "haval" format's OpenMP

- run/john.conf
- src/john.c
- src/ztex/device_format.c
- src/ztex/fpga-bcrypt/README.md
- src/ztex/jtr_device.c
- src/ztex/jtr_device.h
- src/ztex_bcrypt.c
- Moved board initialization from ```init()``` to ```reset()```. That fixes all ```show=``` options, removes the necessity to skip format registration dependent on command-line options.
- Print the list of boards only once per run. Don't print every board if ```verbosity < VERB_DEFAULT```.
- Print count of boards.
- bcrypt-ztex default frequency is set to 150 MHz.
- small fixes, documentation updates.
This fixes #3709
> ztex improvements

- src/ztex/device.c
- src/ztex_bcrypt.c
- Corrected error handling
- Works fine with mask iterating over lengths
- Tested on a salt with 3M hashes (performance almost equals to a run with 513 hashes , memory usage ~700M)
> bcrypt >512 hashes/salt fix

- src/sip_fmt_plug.c
- src/sip_fmt_plug.h
And adds a test vector that is qop=auth. By nanosonde.
> SIP: fix for fails cracking qop=auth

- src/bench.c
- src/john.c
- src/mask.c
- src/mask.h
To be called after *_done(). It seems, that in mask the done() method
is not only a cleanup; it has some pending tasks to do. The cleanup
has to be done later.
> mask: add event to free (destroy) mask objects

- src/packaging/build.sh
- src/packaging/com.openwall.John.appdata.xml
- src/packaging/com.openwall.John.desktop
Magnum, to be part of a repository, a reviewer suggest to upstream these files. So, that is up to you. 
My opinion is:
* `build.sh`: no. It is not related to upstream at al.
* `appdata.xml`: maybe, why not.
* `.destop`: uhmmmm, useless to upstream. Anyway, harmless.
**[edited]**
https://flathub.org/builds/#/builders/32/builds/2621
> Upstream packaging stuff

- src/opencl_hash_check_128_plug.c
> hash_table: ocl_hc_128_prepare_table uninitialized allocation

- src/opencl_rawsha256_fmt_plug.c
It was resulting in a cracking performance less than ideal.
> OpenCL: rawSHA256 force auto-tuning

- run/john.conf
- src/gpu_common.c
We are interpreting this as intent to keep the GPU temperature around
the limit.
> OpenCL: if SleepOnTemperature = 1, print sleeping message once

- src/django_scrypt_fmt_plug.c
- src/ethereum_fmt_plug.c
- src/multibit_fmt_plug.c
- src/scrypt_fmt.c
- src/yescrypt/yescrypt-opt.c
- src/yescrypt/yescrypt-platform.c
I'd like my separate commits here to be retained on merge - please don't squash them.
Fixes #2871. The most notable speedup is for Ethereum, from:
```
[solar@super src]$ GOMP_CPU_AFFINITY=0-31 OMP_NUM_THREADS=31 ../run/john -test -form=ethereum -cost=2,1:1
Will run 31 OpenMP threads
Benchmarking: ethereum, Ethereum Wallet [PBKDF2-SHA256/scrypt Keccak 128/128 AVX 4x]... (31xOMP) DONE
Speed for cost 1 (iteration count) of 1024, cost 2 (kdf [0:PBKDF2-SHA256 1:scrypt 2:PBKDF2-SHA256 presale]) of 1
Warning: "Many salts" test limited: 39/256
Many salts:     4741 c/s real, 359 c/s virtual
Only one salt:  4712 c/s real, 361 c/s virtual
```
to:
```
[solar@super src]$ GOMP_CPU_AFFINITY=0-31 OMP_NUM_THREADS=31 ../run/john -test -form=ethereum -cost=2,1:1
Will run 31 OpenMP threads
Benchmarking: …
```
> scrypt-using format enhancements

- src/cracker.c
Also make message a little shorter, avoiding a line wrap decision.
> Don't suggest setting RelaxKPCWarningCheck when it's already set.

- run/john.conf
- src/7z_fmt_plug.c
- src/opencl_7z_fmt_plug.c
- src/params.h
... so user can decide.  Have it default to true, since we've only had a single report of false negative and that was an archive of somewhat dubious origin.  Closes #3806.
Note: This commit also tosses some config stuff around, to keep related things together.
> 7z formats: Move the compile-time TRUST_PADDING macro to a john.conf option

- src/XSHA512_fmt_plug.c
- src/XSHA_fmt_plug.c
- src/django_scrypt_fmt_plug.c
- src/scrypt_fmt.c
- src/sunmd5_fmt_plug.c
This is meant to address #3882, but wasn't actually tested with gcc 9 yet - need to test before closing that issue.
> Workaround gcc 9 change for const vs. OpenMP shared()

- src/eapmd5tojohn.c
This fixes icc warnings:
```
eapmd5tojohn.c(1079): warning #167: argument of type "void (*)()" is incompatible with parameter of type "__sighandler_t"
signal(SIGINT, cleanexit);
^
eapmd5tojohn.c(1080): warning #167: argument of type "void (*)()" is incompatible with parameter of type "__sighandler_t"
signal(SIGTERM, cleanexit);
^
eapmd5tojohn.c(1081): warning #167: argument of type "void (*)()" is incompatible with parameter of type "__sighandler_t"
signal(SIGQUIT, cleanexit);
^
eapmd5tojohn.c(1146): warning #167: argument of type "void (*)()" is incompatible with parameter of type "__sighandler_t"
signal(SIGALRM, break_pcaploop);
^
```
The signal handlers look wrong to me in that they use async-signal-unsafe functions such as exit(3), but that's a separate issue.
> eapmd5tojohn: Use proper signal handler prototypes

- src/opencl_salted_sha_fmt_plug.c
- src/opencl_sl3_fmt_plug.c
I just can't find whatever bug is triggered by not doing this.  Closes #3880.
> SL3 and salted-sha1 opencl formats: Revert to using LWS=NULL when count is lower than GWS

- src/opencl_rawsha256_fmt_plug.c
- src/opencl_rawsha512_gpl_fmt_plug.c
This is harmless and will be needed after J1.
> OpenCL: SHA256 and SHA512 force tune after fmt_done()

- src/dmg2john.c
...when types are different sizes (seen on Win64). Closes #3902
> Avoid a problem casting size_t to negative and then to off_t

- src/bench.c
- src/loader.c
- src/options.c
> Pass correct salt into crypt_all() in benchmarks

- src/MD5_fmt.c
- src/Makefile.in
- src/Makefile.legacy
- src/john.c
- src/md5crypt_long_fmt.c
See #3872.
This commit unplugs the format, renames it to md5crypt-long and adds support for $apr1$.
> Refactor and repurpose aix-smd5 format.

- src/opencl_common.h
See #3918.
I think this is enough pre-release. Changing autoconf is more error-prone so let's wait with that until post release.
> Check OpenCL headers version and bail out if 1.2 is not supported.

- src/bench.c
> Ensure we never benchmark less than two salts for "Many salts".

- src/rpp.c
Closes #3935.
Before:
```
$ ../run/john -stdout -w -rules-stack:wordlist,signle
Using default input encoding: UTF-8
No "wordlist,signle" mode rules found in ../run/john.conf
```
After:
```
$ ../run/john -stdout -w -rules-stack:wordlist,signle
Using default input encoding: UTF-8
"signle" not found; No "wordlist,signle" mode rules found in ../run/john.conf
```
> Better error message when some rule is missing in a list, eg. --rules=one,two.

- src/openbsdsoftraid_fmt_plug.c
- src/x86-64.h
As discussed starting with https://github.com/magnumripper/JohnTheRipper/issues/2914#issuecomment-491791916
> 2x SHA-1 for XOP; OpenBSD-SoftRAID benchmark fix

- src/memory.c
it was breaking "make debug" on non-SIMD targets.
> memory.c: Move the dump_stuff* debug functions out of #if SIMD... blocks,

- .ci/disable_formats.sh
> Re-enable some formats on CI

- src/zip2john.c
fixes 2 minor typos in the comments about the $pkzip2$ format
> minor: typo in documentation of zip2john
