magnumripper/JohnTheRipper

src/opencl/DES_bs_finalize_keys_kernel.cl, src/opencl/DES_bs_kernel.cl, src/opencl/DES_bs_kernel_f.cl, src/opencl/DES_bs_kernel_h.cl, src/opencl_DES_WGS.h, src/opencl_DES_bs.h, src/opencl_DES_bs_b_plug.c, src/opencl_DES_bs_f_plug.c, src/opencl_DES_bs_h_plug.c, src/opencl_DES_bs_plug.c, src/opencl_DES_fmt_plug.c, src/opencl_DES_hst_dev_shared.h, src/opencl_DES_kernel_params.h
@magnumripper please test and merge descrypt-opencl.
=> Descrypt opencl

doc/INSTALL, doc/README-CUDA, doc/README-OPENCL, src/Makefile.stub
@frank-dittrich @magnumripper is this slightly better? 
While we can definitely maintain the legacy build system, why do we actually care?
=> Stop wasting time in maintaining the legacy build system

src/Makefile.legacy
@magnumripper is this needed too?
=> Emit a scary message when Makefile.legacy is used

doc/README-MIC, src/config.sub, src/configure.ac, src/mpz_int128.h, src/unused/gmp.patch, src/unused/openssl.patch
There're some minor modifications to autoconf scripts and a source file.
A tutorial is also added, named README-MIC.
=> Building for MIC

run/keyring2john.py
Added keyring2john.py according to https://github.com/magnumripper/JohnTheRipper/issues/549
=> Added keyring2john.py

README.md
=> Be more user friendly using a better README file in Github

src/chap_fmt_plug.c, src/dahua_fmt_plug.c, src/eigrp_fmt_plug.c, src/hsrp_fmt_plug.c, src/mongodb_fmt_plug.c, src/mysql_fmt_plug.c, src/pst_fmt_plug.c, src/tcp_md5_fmt_plug.c
I've currently only tweaked with formats that has a predefined OMP_SCALE larger than 4096 and passes the tests.
=> OMP_SCALE tuned for MIC

src/config.c
=> Must check cfg_database->list before cfg_add_line()

src/autoconfig.h.in, src/configure, src/configure.ac, src/jumbo.c, src/jumbo.h
Also remove the use of bzero, which is deprecated.
=> some bug fixes

src/common-gpu.c, src/common-opencl.c, src/opencl/sha256_kernel.cl, src/opencl_mask_extras.h, src/opencl_rawsha256.h, src/opencl_rawsha256_fmt_plug.c, src/opencl_rawsha512_fmt_plug.c, src/rawSHA256_common.h
Discussion opened:
* there are 2 'remove me' that need some analysis before merge.
=> Mask mode implementation in raw-sha256-opencl

doc/README-MIC, src/configure, src/configure.ac, src/m4/jtr_mic_logic.m4
Those flags are placed in m4/jtr_mic_logic.m4
=> Add special compiler flags for MIC

src/cq_fmt_plug.c
=> fix get_salt() in cq_fmt_plug.c

src/dynamic_fmt.c
=> fix segfault: --field-separator-char=c

src/common-opencl.c, src/opencl/sha256_kernel.cl, src/opencl_mask_extras.h, src/opencl_rawsha256.h, src/opencl_rawsha256_fmt_plug.c
Also, adjust c/s for mask mode benchmark.
=> Make things clear to the OpenCL compiler.

src/opencl/cryptsha512_kernel_GCN.cl, src/opencl/sha256_kernel.cl, src/opencl/sha512_kernel.cl, src/opencl_mask_extras.h, src/opencl_rawsha256.h, src/opencl_rawsha256_fmt_plug.c, src/opencl_rawsha512.h, src/opencl_rawsha512_fmt_plug.c, src/opencl_sha256.h, src/opencl_sha512.h
=> Mask mode implementation in [raw/x]-sha512-opencl.

src/opencl/sha256_kernel.cl, src/opencl/sha512_kernel.cl, src/opencl_sha2_common.h
=> Handle AMD weakness.

src/XSHA512_fmt_plug.c, src/common-opencl.c, src/common-opencl.h, src/opencl/cryptsha512_kernel_GPU.cl, src/opencl/sha256_kernel.cl, src/opencl/sha512_kernel.cl, src/opencl_cryptsha256_fmt_plug.c, src/opencl_cryptsha512_fmt_plug.c, src/opencl_rawsha512_fmt_plug.c, src/opencl_sha512.h, src/rawSHA512_common.h, src/rawSHA512_fmt_plug.c, src/rawSHA512_ng_fmt_plug.c
=> Some tweaks

src/opencl/sha256_kernel.cl, src/opencl/sha512_kernel.cl, src/opencl_rawsha256_fmt_plug.c, src/opencl_rawsha512_fmt_plug.c
- see: https://github.com/magnumripper/JohnTheRipper/issues/1037#issuecomment-71936052
1. There are other ways to go. I saw some performance penalty trying the obvious one.
2. md4 is up to you
3. Tests on more hardware is still pending.
=> Fix for the intermitent mask error on CPU.

src/regex.c
=> Fix spell mistake

src/listconf.c
another try, this time hopefully correct
=> Report glibc version with --list=build-info

src/pseudo_intrinsics.h, src/rawSHA1_ng_fmt_plug.c, src/wordlist.c
it's too slow under benchmarking
=> remove the emulation of _mm512_cmp_epi8_mask

src/mic.h
MIC model: 5110P
icc version: 15.0.2
=> mic.h: tune interleaving factors

src/john.c
=> Close #1230

src/wow_srp_fmt_plug.c
=> StripZeros: Copy as much as ct2_size to ct2 to avoid buffer overflow

src/SKEY_fmt_plug.c
=> Fix SKEY Format get_binary()

src/ssh_fmt_plug.c
=> Fix SSH Format get_salt()

src/rar5_common.h
Close #1260 
The hash should be **rejected by** `valid()`
=> Fix rar5 common valid()

src/sunmd5_fmt_plug.c
remove some redundant comments BTW
=> add OpenMP support to sunmd5

src/ssh2john.c
=> Fix ssh2john

src/sunmd5_fmt_plug.c
drop the `threadprivate` stuffs and write the OpenMP clause in a more verbose form
=> sunmd5: revise OpenMP support

src/gpg2john.c
=> Fix: gpg2john global-buffer-overflow

src/gpg2john.c
There is **buffer overflow** in `give()`, since it does not check the size of buf.
```C
public void
give(int len, unsigned char *buf)
{
int i;
for (i = 0; i < len; i++)
buf[i] = Getc();
}
```
$ ../gpg2john failed_gpg
```C
==97936==ERROR: AddressSanitizer: global-buffer-overflow on address 0x0000013bc7c0 at pc 0x7a58cb bp 0x7ffd6279d320 sp 0x7ffd6279d318
WRITE of size 1 at 0x0000013bc7c0 thread T0
#0 0x7a58ca in give /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/gpg2john.c:393
#1 0x7a6482 in encrypted_Secret_Key /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/gpg2john.c:2394
#2 0x7a8268 in Secret_Key_Packet /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/gpg2john.c:2226
#3 0x7a86a8 in parse_packet …
```
=> Fix: gpg2john global-buffer-overflow: give()

src/gpg2john.c
There is **buffer overflow** in `give_pdump()`, since it does compare `len` and `sizeof(gecos)`
```C
public void
give_pdump(int len)
{
int i;
for (i = 0; i < len; i++)
gecos[i] = Getc();
gecos[i] = 0;
}
```
$ ../gpg2john failed_gpg
```C
=================================================================
==26342==ERROR: AddressSanitizer: global-buffer-overflow on address 0x0000013ba780 at pc 0x7a5253 bp 0x7ffda1e4bdd0 sp 0x7ffda1e4bdc8
WRITE of size 1 at 0x0000013ba780 thread T0
#0 0x7a5252 in give_pdump /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/gpg2john.c:413
#1 0x7a5452 in User_ID_Packet /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/gpg2john.c:985
#2 0x7a86d6 in parse_packet …
```
=> Fix: gpg2john global-buffer-overflow: give_pdump()

src/keystore2john.c
Fix bug of fread().
$ ./configure && make -sj8
$ ../keystore2john  failed_pw
```C
*** buffer overflow detected ***: ../keystore2john terminated
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x7338f)[0x7f1ac820238f]
/lib/x86_64-linux-gnu/libc.so.6(__fortify_fail+0x5c)[0x7f1ac8299c9c]
/lib/x86_64-linux-gnu/libc.so.6(+0x109b60)[0x7f1ac8298b60]
/lib/x86_64-linux-gnu/libc.so.6(__fread_chk+0x13c)[0x7f1ac829923c]
../keystore2john[0x50cf1e]
../keystore2john[0x50d4d4]
../keystore2john[0x71a07b]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f1ac81b0ec5]
../keystore2john[0x406b33]
======= Memory map: ========
00400000-00966000 r-xp 00000000 08:01 8657353                            /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/run/john
00b65000-00b67000 r--p …
```
=> Fix: keystore2john remove assert and check buffer size of fread()

src/kwallet2john.c
$ configure && make -sj8
$ ../kwallet2john failed_pw
```C
*** buffer overflow detected ***: ../kwallet2john terminated
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x7338f)[0x7f060724938f]
/lib/x86_64-linux-gnu/libc.so.6(__fortify_fail+0x5c)[0x7f06072e0c9c]
/lib/x86_64-linux-gnu/libc.so.6(+0x109b60)[0x7f06072dfb60]
/lib/x86_64-linux-gnu/libc.so.6(__fread_chk+0x13c)[0x7f06072e023c]
../kwallet2john[0x507190]
../kwallet2john[0x507496]
../kwallet2john[0x7202f9]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f06071f7ec5]
../kwallet2john[0x406b33]
======= Memory map: ========
00400000-0096d000 r-xp 00000000 08:01 8657358                            /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/run/john
00b6c000-00b6e000 r--p 0056c000 08:01 8657358 …
```
=> kwallet2john.c: Check the return value of fread()

src/luks2john.c
$ ../luks2john   file_does_exist
Segmentation fault (core dumped)
=> luks2john.c: Check return value of jtr_fopen()

src/rar2john.c
**Remove assert** and  **check the buffer size**  before fread()
=> rar2john.c: Remove assert and check the buffer size before fread()

src/keyring2john.c
=> Remove build warning

src/rar2john.c
Use `printf("%zu")` to print `size_t`
=> Use printf("%zu") to print size_t

src/pseudo_intrinsics.h, src/sse-intrinsics.c
tested on MIC, no noticeable performance improvement
=> use scatter instruction in sse-intrinsics

.travis.yml, src/MinGW-bootstrap.sh, src/travis-cc.sh
@jfoug @magnumripper @frank-dittrich this is what the MinGW build stuff will look like.
=> Add support for MinGW builds, with <3 from JimF!

src/lineage_fmt_plug.c
The discussion is at https://github.com/magnumripper/JohnTheRipper/issues/1420 URL.
=> Add support for "lineage" hashes

run/dynamic.conf
@jfoug @magnumripper does this PR make sense?
=> dynamic_1016 never did md5($s,$p), it does md5($p,$s) instead!

src/Makefile.in, src/build_table.c, src/common-opencl.c, src/hash_type_128.c, src/hash_type_192.c, src/hash_types.h, src/interface.h, src/mask.c, src/mask_ext.c, src/mask_ext.h, src/mt.h, src/opencl/md4_kernel.cl, src/opencl_device_info.h, src/opencl_mask_extras.h, src/opencl_rawmd4_fmt_plug.c, src/twister.c
@magnumripper please merge with bleeding jumbo. Also please review commit edc9544 and add other GCN gpus in case I missed some.
=> Bitmap perf test

src/opencl/sha1_kernel.cl, src/opencl_rawsha1_fmt_plug.c
@magnumripper please merge and delete raw-sha1-opencl-test
=> Raw sha1 opencl test

src/john.c, src/mask.c, src/mask.h, src/opencl/mscash_kernel.cl, src/opencl_mscash_fmt_plug.c
@magnumripper  Please test and merge.
Some changes were made to john.c.
=> Gpu mask tune

src/pseudo_intrinsics.h, src/rawSHA1_ng_fmt_plug.c, src/rawSHA256_ng_fmt_plug.c, src/rawSHA512_ng_fmt_plug.c, src/sse-intrinsics.c
all formats should work with AltiVec now
=> some fixes and optimizations for AltiVec

doc/README.coding-style
=> Add doc/README.coding-style. See #350 and #1567

src/formats.c, src/john.c, src/options.c, src/options.h
1. Crack max passwords at the same time
2. Detect FMT_* flags error
=> Test full option

src/common-opencl.c, src/opencl_cryptsha256_fmt_plug.c, src/opencl_cryptsha512_fmt_plug.c, src/opencl_rawsha256_fmt_plug.c, src/opencl_rawsha512_fmt_plug.c
=> Just to check if it will hurt on CI

src/formats.c
=> Remove build warning. Close #1605

src/vms_fmt_plug.c
This test vector is important which can improve the code coverage.
=> Add test vector for vms

src/formats.c
See http://www.openwall.com/lists/john-dev/2015/08/06/14
1. is_key_right() ignores the result of get_key() when invoked by test_fmt_case()
2. Check the length of string returned by get_key() which should between plaintext_min_length and plaintext_length
=> Fix: is_key_right()

src/formats.c
crypt       ->  should set FMT_8_BIT
wpapsk  ->  should not set FMT_8_BIT
=> Fix the detects of FMT_8_BIT for crypt and wpapsk

src/john.c, src/luks_fmt_plug.c, src/sapG_fmt_plug.c
=> Add FLG_TEST_FULL_CHK in some cases which need FLG_TEST_CHK

src/DOMINOSEC8_fmt_plug.c
=> Add FMT_8_BIT for dominosec8

src/formats.c
Change s_size to err_buf in is_key_right() and fmt_self_test_full_body of formats.c
=> Change s_size to err_buf

src/vnc_fmt_plug.c
See http://www.openwall.com/lists/john-dev/2015/08/22/15
=> Fix the crypt_all() of vnc

src/7z_fmt_plug.c, src/rar_fmt_plug.c
and work around the alignment issue of stack arrays
=> Add SIMD support to RAR

run/office2john.py
Tested with Python 2.7.10 and Python 3.4.3 on Ubuntu
=> Update olefile to 0.42.1 (released 2015-01-24)

src/pseudo_intrinsics.h, src/simd-intrinsics.c, src/simd-intrinsics.h, src/x86-64.h
and fix some code targeting AVX512 that's never tested
=> Introduce AVX-512's ternary logic instructions

src/arm32le.h
based on experimentation on ZedBoard
=> Tune interleaving paras for ARM

src/opencl/cryptsha512_kernel_GPU.cl
=> Fine tune the OpenCL sha512crypt kernel for Nvidia sm_5x on super. 

src/opencl/cryptsha512_kernel_GPU.cl
* AMD driver still surprises me.
=> Seems to be better to revert to the previous statement 

src/common-opencl.c, src/common-opencl.h, src/opencl_rawsha256_fmt_plug.c, src/opencl_rawsha512_ng_fmt_plug.c
* A PR just to think about it.
=> Adjust Claudio's raw SHA2 formats to deal with GPU mask mode benchmark.

src/opencl_hash_check_128.h, src/opencl_hash_check_128_plug.c, src/opencl_nt_fmt_plug.c, src/opencl_rawmd4_fmt_plug.c, src/opencl_rawmd5_fmt_plug.c
@magnumripper This patch should fix #1798 along with merging hash checking in a common file but it is not in a polished state. Eventually, I'll add more functions to common file. But for now, please merge.
=> 128b common hash check

src/asn1.h, src/asn1_plug.c, src/ssh_ng_fmt_plug.c
Thanks to Martin Kleppmann, Jens Getreu, Jouni Malinen (Reaver WPS),
and TinyBER!
=> Make ssh-ng saner by using a tiny ASN.1 decoder

src/opencl_cryptsha256.h, src/opencl_cryptsha256_fmt_plug.c, src/opencl_cryptsha512.h, src/opencl_cryptsha512_fmt_plug.c, src/opencl_rawsha256.h, src/opencl_rawsha256_fmt_plug.c, src/opencl_rawsha512.h, src/opencl_rawsha512_ng_fmt_plug.c, src/opencl_sha256.h, src/opencl_sha2_common.h, src/opencl_sha512.h
* indent -kr -i4 -ts4 -nlp -nbbo -ncs -l79 -lc79 -bad -il0
* astyle --style=kr -t4 -U -H -xC79 -c -k3 -z2
=> Run indent and astyle ONLY.

src/gpg2john.c, src/gpg_fmt_plug.c
@magnumripper I need help in locating, and linking against the GPGME library.
This pull request includes "gpgme.m4", which might be of some help.
=> Add support for cracking files using GPG symmetric encryption

run/iwork2john.py, src/iwork_fmt_plug.c
This work was done for the http://www.kth.se/student/kurser/kurs/DD2395?l=en course.
=> Add support for cracking Apple iWork '13 files

src/iwork_common.h, src/iwork_common_plug.c, src/iwork_fmt_plug.c, src/opencl_iwork_fmt_plug.c
DO NOT MERGE YET!
@magnumripper how is this code even working when the "currentsalt.length" is set to a wrong value in the "set_salt" function?
=> GPU support for cracking Apple iWork files

src/common-opencl.c, src/common-opencl.h, src/opencl/cryptsha512_kernel_GPU.cl, src/opencl_cryptsha512_fmt_plug.c, src/opencl_sha512.h
Gain seen on super:
\> 3k c/s on GCN
\> 15k c/s on NVIDIA
=> Allow to calibrate SHA512crypt kernel to any GPU:

src/opencl_cryptsha256_fmt_plug.c, src/opencl_cryptsha512_fmt_plug.c
=> Fix a memory leak in sha[256/512]-opencl.

src/configure, src/configure.ac, src/regex.c
I added a version check, which should prevent linking john against an incompatible version of rexgen, In addition, the same changes as for rexgen 1.2.8 are included.
Regards, Jan
=> compiles cleanly with rexgen 1.3.1, contains version check for rexgen

run/axcrypt2john.py
Remaining: writing doc/AxCrypt-Auditing-HOWTO
=> AxCrypt format: added support to parse self-decrypting binary

src/common-opencl.c
=> Improve find_valid_opencl_device() detection.

src/opencl/sha256_kernel.cl, src/opencl/sha512_ng_kernel.cl, src/opencl_mask_extras.h, src/opencl_rawsha512.h, src/opencl_rawsha512_ng_fmt_plug.c
=> Improve Raw-SHA2-opencl scalability.

src/opencl_rawsha512_ng_fmt_plug.c
=> Mute a compiler warning.

src/opencl_rawsha512_ng_fmt_plug.c
=> Tune memory used by raw-SHA2-opencl.

doc/AxCrypt-Auditing-HOWTO.md
it no longer needs to pad hash up to 20bytes
=> Changed instructions to fit new format validation

src/opencl_rawsha512_ng_fmt_plug.c
=> Fix a memory overread. Closes #2049.

src/opencl_sha512.h
*****
Do not merge, Let's clean backlog first.
=> Format a file.

src/opencl/cryptsha512_kernel_GPU.cl, src/opencl_sha2_common.h
*****
Do not merge, Let's clean backlog first.
=> Congratulations NVIDIA!

src/opencl_cryptsha256_fmt_plug.c, src/opencl_cryptsha512_fmt_plug.c, src/opencl_rawsha512_ng_fmt_plug.c
Using this pattern seems better.
=> Do nothing if db is not set.

src/pseudo_intrinsics.h
This commit changes code only in NEON's part.
It cross-compiles with gcc 4.7.3 and passes all self-tests on QEMU (I have no access to any ARM machine currently).
=> Unify the format of NEON and Altivec's intrinsics.

src/opencl/cryptsha512_kernel_DEFAULT.cl, src/opencl/cryptsha512_kernel_GPU.cl, src/opencl_cryptsha512_fmt_plug.c
Openwall's super can handle 1/4Mc/s. Precisely: 258957c/s
```
$ ../run/john ~/data/testhashes -form=sha512crypt-opencl -fork=5  -dev=gpu --incremental
```
=> Tune SHA512crypt-opencl further. Improvement 1-2 kc/s.

src/opencl/sha256_kernel.cl, src/opencl_mask_extras.h, src/opencl_rawsha256.h, src/opencl_rawsha256_fmt_plug.c
=> Raw sha256 scalability

src/opencl/sha256_kernel.cl, src/opencl_mask_extras.h, src/opencl_rawsha256.h, src/opencl_rawsha256_fmt_plug.c, src/opencl_rawsha512_ng_fmt_plug.c
WIP
BTW: I need to improve my bash-fu. I must record my tests somehow. It is difficult and boring to re-test from scratch.
=> Memory Tune

src/opencl/sha512_ng_kernel.cl, src/opencl_rawsha512.h, src/opencl_rawsha512_ng_fmt_plug.c
- Sync with raw-SHA256.
- Use a k=2 Bloom Filter.
*************
=> raw-SHA512 [OpenCL]:

src/common-opencl.c, src/common-opencl.h, src/opencl_rawsha256_fmt_plug.c, src/opencl_rawsha512_ng_fmt_plug.c
=> Do not use a #define as a function.

run/korelogic.conf
Spelling fix in a comment: equivelent to equivalent
=> Pushing Solar's recent commit.

doc/DYNAMIC_SCRIPTING, doc/INSTALL, src/Makefile.legacy, src/cryptsha256_fmt_plug.c, src/idea-JtR.h, src/idea_plug.c, src/mdc2-JtR.h, src/mdc2dgst_plug.c, src/opencl/keystore_kernel.cl
There should be no overlap with Claudio's pull request(s) here.
=> Assorted spelling fixes

doc/DYNAMIC_COMPILER_FORMATS.md
This is a proof-of-concept for https://github.com/magnumripper/JohnTheRipper/issues/1993.
=> Document known formats built using the dynamic compiler

run/john.conf, src/7z_fmt_plug.c, src/cracker.c, src/cracker.h, src/dyna_salt.c, src/dyna_salt.h, src/dynamic.h, src/dynamic_fmt.c, src/loader.c, src/loader.h, src/oldoffice_fmt_plug.c, src/opencl_7z_fmt_plug.c, src/recovery.c, src/status.c, src/status.h, src/wpapsk.h
Not ready for merging yet, but this PR can be used to look at the "sum" of diffs. See #2082
=> Multisalt resume

doc/INSTALL-UBUNTU
I have this change around me for a while. In order to document it, I think a PR should be a better approach.
=> Improve the Ubuntu OpenCL documentation.

doc/DYNAMIC_COMPILER_FORMATS.md
Thanks to Davy Douhine for this work.
=> Document support for cracking JBoss AS 7.1 hashes

run/luks2john.py
This is a port of luks2john.c to Python.
=> Port luks2john.c to Python

run/kerberom/README.md, run/kerberom/kerberom.py, run/kerberom/modules/rom/_crypto/ARC4.py, run/kerberom/modules/rom/_crypto/MD4.py, run/kerberom/modules/rom/_crypto/MD5.py, run/kerberom/modules/rom/ccache.py, run/kerberom/modules/rom/crypto.py, run/kerberom/modules/rom/krb5.py, run/kerberom/modules/rom/pac.py, run/kerberom/modules/rom/util.py
As discussed by email with @magnumripper here is the PR
This tool is aimed to retrieve ARC4-HMAC encrypted tickets to be cracked with john. 
Usage is provided in the README.md. I will write an HOWTO following, to explain what are the prerequisite within kerberos to use the tool.
I've put it in /run as I didn't know where exactly it should be. 
If I make any modification within the main git repository that are useful I'll backport them here.
If you have any requests/suggestions, do not hesitate.
=> Add tool "kerberom" to /run

src/common-opencl.c
For a system wide build, $JOHN is (or should be) read-only. So, binary kernels should be saved inside user private HOME.
- 1st attempt: CI and comments.
=> Allow an OpenCL system wide build.

run/bks2john.py, src/bks_fmt_plug.c, src/pkcs12.h, src/pkcs12_plug.c
The PKCS #12 KDF will be useful for cracking PFX files as well.
=> Add support for "BKS" (BouncyCastle) format keystore files

run/mongodb2john.js
This ones comes from @averagesecurityguy :+1:
=> Add utility to extract MongoDB hashes in JtR format

run/dynamic.conf
@jfoug please review this, thanks!
=> Rename MONGODB-MiTM system hashes to MONGODB-CR network hashes

run/mongodb2john.js, src/mongodb_scram_fmt_plug.c
SIMD support is missing for now.
=> Add support for cracking MongoDB SCRAM-SHA-1 system hashes

src/config.c, src/pp.c, src/rpp.c, src/single.c, src/wordlist.c
=> added .log message directive code into rules scripts.  #2140

src/palshop_fmt_plug.c
This format is reverse engineered from InsidePro Hash Manager.
=> Add support for MD5(Palshop) hashes

run/dynamic.conf
Thanks to JimF for making this work!
@jfoug please review this, thanks!
=> Add support for cracking SocialEngine hashes

src/zipmonster_fmt_plug.c
This is a super slow format due to MD5 x 50000 operations.
=> Add support for cracking MD5(ZipMonster) hashes

.travis.yml, src/opencl_rawsha512_ng_fmt_plug.c
=> Fix XSHA512-ng-opencl

src/unused/camellia_fmt_plug.c
I think that the current file name is misleading. Suggestions?
=> Add support for cracking Poison Ivy "hashes"

.travis.yml
For testing purposes; not a real PR.
Please, merge only IF this is what you guys would like to see in.
=> Re-enable mscash2-opencl format on Travis CI.

src/nsec3_fmt_plug.c
This is taken from the https://github.com/anonion0/nsec3map project.
=> Add support for cracking NSEC3 hashes

src/gpg2john.c
=> gpg2john: allow multi-part message blobs (i.e. large file support).

src/regex.c
=> Fix for a warning seen when compiling against regex master

src/opencl_DES_bs.h, src/opencl_lm.h
- tested on 'my' CI. Passes.
- Fixes and closes #2289
=> Fix an ld warning seen on CI

src/regex.c, src/unicode.c, src/unicode.h
We now properly convert to wchar_t. Closes #2296.
=> Regex mode: Fix for recent changes in librexgen.

src/common-opencl.c
- I have 1 zVIDIA GPU + 1 zMD GPU. Two platforms installed. 
- I removed the zVIDIA board, no software changes.
- the system will report 2 installed platforms with only one device available in one of them.
- Or one of my drivers starts to misbehave after an upgrade.
In any case, this patch is safe and tested. But:
- I have no access to a real crazy machine to improve it further.
=> OpenCL: a platform could have no devices

.github/issue_template.md, .github/pull_request_template.md
=> github: add guidelines to github users when they create an issue or a PR

.github/issue_template.md
I'm creating "umbrella" issues in order to hint JtR users that devs are aware of some issues.
=> Improve issue guidelines trying to avoid CUDA and OpenCL known issues

.travis.yml, .travis/check.sh
Just in case anyone is interested of save a test for a non OpenMP build.
* No errors was found.
=> CI: test a non OpenMP build

.travis/check.sh
Since latest means whatever the maintainer wants to in docker images, I vote to make it clear what we want.
=> change the recent OS image to be used

src/encfs_common_plug.c
See:
https://github.com/magnumripper/JohnTheRipper/commit/aaeff8b3fe52dd3946c1a7f779c4f1eb170f4bf9
=> encfs_common.c: fix a leak

src/opencl_lotus5_fmt.h, src/opencl_lotus5_fmt_plug.c
Build on CI servers are failing now (for, at least, 2 different reasons).
In this PR I'm fixing things on OpenCL.
- If CI succeed and nobody complains, I'll merge this.
=> Fix a macro name in opencl Lotus5 format

run/filezilla2john.py
This PR fixes https://github.com/magnumripper/JohnTheRipper/issues/2373. 
No new format was needed :)
=> Add support for cracking FileZilla Server hashes

src/Makefile.in
See:
- https://circleci.com/gh/claudioandre/JohnTheRipper/13
=> circle: fix the build issue introduced in a63b819

src/Makefile.legacy
=> build: clean up some 7-zip tmp files

run/kwallet2john.py, src/kwallet_fmt_plug.c
This fixes #1626. I am currently refactoring this. DO NOT MERGE.
=> Add support for modern KWallet databases

run/enpass2john.py, src/enpass_common.h, src/enpass_common_plug.c, src/enpass_fmt_plug.c, src/opencl_enpass_fmt_plug.c
This fixes issue https://github.com/magnumripper/JohnTheRipper/issues/2336.
Latest revision supports both CPU and GPU.
=> Add support for Enpass Password Manager

src/hsrp_fmt_plug.c
Semi-useful PR to see how CircleCI is behaving with the new Fedora 25 Docker image.
=> HSRP: remove an old joke

run/iwork2john.py
+ Better Python 3 support
+ Fix processing of iWork '13 files with empty password hints
+ PEP8 fixes
=> Fixes and improvements for iwork2john.py

src/iwork_fmt_plug.c
I wonder why this wasn't caught earlier.
=> Fix a typo in iwork format

src/kwallet_fmt_plug.c
I am still new to SIMD stuff. Please review carefully.
=> Add SIMD support for cracking modern KWallet files

src/enpass_fmt_plug.c
This is similar to the recent fix I made in `iwork` format.
=> Fix a thinko in enpass format

run/dynamic.conf, run/ps_token2john.py
[ERPScan-tockenchpoken.zip (attaching for backup purposes)](https://github.com/magnumripper/JohnTheRipper/files/739328/ERPScan-tockenchpoken.zip)
=> Add support for Oracle PeopleSoft PS_TOKEN hashes

src/iwork_common.h, src/iwork_common_plug.c, src/iwork_fmt_plug.c, src/opencl/iwork_kernel.cl, src/opencl_iwork_fmt_plug.c
`../run/john --test-full=0 --device=0 --format=iwork-opencl` says `FAILED (iwork-opencl sets FMT_CASE but all test-vectors are case-insensitive)`. However, there is a test-vector with a mixed-case password! Weird?
=> iwork-opencl: move all work to GPU, v2

src/configure, src/configure.ac
I'm working to make CI act as my watchman.
=> Add a configure option to treat build warnings as errors

.travis/check.sh, src/fvde_common.h, src/fvde_common_plug.c, src/fvde_fmt_plug.c, src/opencl/7z_kernel.cl, src/opencl/agile_kernel.cl, src/opencl/enpass_kernel.cl, src/opencl/fvde_kernel.cl, src/opencl/iwork_kernel.cl, src/opencl/odf_aes_kernel.cl, src/opencl/office_kernel.cl, src/opencl_aes.h, src/opencl_fvde_fmt_plug.c
The format has "XXX is this correct?" in two places. I am not sure if I am doing the right thing at these places. Please review.
=> FVDE (FileVault 2) OpenCL support

src/opencl/7z_kernel.cl, src/opencl/agile_kernel.cl, src/opencl/cryptmd5_kernel.cl, src/opencl/enpass_kernel.cl, src/opencl/fvde_kernel.cl, src/opencl/gpg_kernel.cl, src/opencl/iwork_kernel.cl, src/opencl/keyring_kernel.cl, src/opencl/keystore_kernel.cl, src/opencl/odf_aes_kernel.cl, src/opencl/office_kernel.cl, src/opencl/pbkdf2_hmac_sha1_unsplit_kernel.cl, src/opencl/pbkdf2_hmac_sha256_kernel.cl, src/opencl/pbkdf2_hmac_sha512_kernel.cl, src/opencl/pbkdf2_ripemd160_kernel.cl, src/opencl/pwsafe_kernel.cl, src/opencl/salted_sha_kernel.cl, src/opencl_aes.h, src/opencl_enpass_fmt_plug.c, src/opencl_gpg_fmt_plug.c, src/opencl_iwork_fmt_plug.c, src/opencl_keystore_fmt_plug.c, src/opencl_office_fmt_plug.c
=> Various minor OpenCL optimizations and bug fixes.

src/episerver_fmt_plug.c
=> Improve salt and hash validation in EPiServer format

run/bitcoin2john.py, src/bitcoin_fmt_plug.c
This fixes https://github.com/magnumripper/JohnTheRipper/issues/2287.
=> Support handling of modern Bitcoin Core wallet versions

run/efs2john.py, src/efs_fmt_plug.c
- Format support for Windows 7 + Windows 2012 EFS hashes is pending
+ Windows 7 + Windows 2012 EFS support in efs2john.py works
+ Sync with https://bitbucket.org/jmichel/dpapick/ repository
+ Trim the source, easier to understand
=> Various efs2john.py enhancements

src/bestcrypt_fmt_plug.c
Fixes issue https://github.com/magnumripper/JohnTheRipper/issues/2458.
=> Fix a minor memory leak in BestCrypt format

src/padlock_fmt_plug.c
=> Fix a minor memory leak in Padlock format

run/pcap2john.py
Current version of ```pcap2john.py``` only supports the old ```GG_LOGIN80``` packets, but currently ```GG_LOGIN105``` is used to authenticate. This change adds support for extracting SHA1 hashes from more recent Gadu-Gadu versions.
The main difference between these packets is that the numeric user ID is stored as integer in ```GG_LOGIN80```, but is a hex-encoded ASCII string in ```GG_LOGIN105```. So the position of the SHA1 hash in the payload depends on the length of the uid.
This was tested by capturing GG auth packets with tcpdump, then extracting and successfully cracking a hash of a known password. I can share the tcpdump .pcap file privately if you would like to see it.
=> add support for more recent Gadu-Gadu login packets

doc/RULES
=> Rename HashCat to hashcat

doc/MASK, run/john.conf, run/kerberom/README.md, src/hccap2john.c, src/oldoffice_fmt_plug.c, src/opencl_oldoffice_fmt_plug.c, src/sapH_fmt_plug.c, src/wpapsk.h
(I didn't touch doc/CHANGES-jumbo.git.)
I just changed some comments and doc files, so there shouldn't be any problems.
=> Some more changes due to oclHashcat/HashCat being renamed to hashcat

src/john.c
It is C99, I see no problems. Do you?
=> general: mute a warning and a possible truncation

src/ssh_ng_fmt_plug.c
Fixes issue https://github.com/magnumripper/JohnTheRipper/issues/2495. Thanks a lot to Albert Veli for catching this bug.
=> Fix padding checks in ssh-ng format

run/aruba2john.py
There isn't much to review here but I would like a +1 before I commit this to the repository.
=> Add support for ArubaOS hashes

run/snmp2john.lua, src/snmp_fmt_plug.c
This fixes issue https://github.com/magnumripper/JohnTheRipper/issues/423.
Special thanks goes to @Lekensteyn for making this work possible.
=> Add support for cracking SNMPv3 hashes

src/opencl/bitlocker_kernel.cl, src/opencl_bitlocker.h, src/opencl_bitlocker_fmt_plug.c
=> New hash format

run/ethereum2john.py, src/ethereum_common.h, src/ethereum_common_plug.c, src/ethereum_fmt_plug.c
This fixes issue https://github.com/magnumripper/JohnTheRipper/pull/2525.
=> Add support for cracking Ethereum wallets

src/common-opencl.c
Auto-tune for actual loaded hashes instead of test-vectors, when applicable. See #2538.
This is not ready for merge yet. More testing needed.
=> Autotune cost

run/electrum2john.py, src/electrum_fmt_plug.c
This has only been lightly tested. Please leave the merging operation to me.
This PR fixes issue https://github.com/magnumripper/JohnTheRipper/issues/2504.
This format is roughly 20 times faster than the btcrecover program.
=> Add support for cracking Electrum wallets

run/multibit2john.py, src/multibit_fmt_plug.c
Here are [some MultiBit sample wallets](https://github.com/magnumripper/JohnTheRipper/files/1004226/MultiBitWallets.zip) for testing.
This fixes issue https://github.com/magnumripper/JohnTheRipper/issues/2539.
=> Add support for cracking MultiBit wallets

src/regex.c, src/regex.h
Reverts magnumripper/JohnTheRipper#2566
=> Revert "Using the new multibyte character aware API from rexgen"

run/blockchain2john.py, src/blockchain_common.h, src/blockchain_common_plug.c, src/blockchain_fmt_plug.c, src/opencl_blockchain_fmt_plug.c
[Here is a sample My Wallet v3 wallet for testing](https://github.com/magnumripper/JohnTheRipper/files/1082407/blockchain-v3-wallet-openwall123.txt).
=> Blockchain formats: Cleanup code and support My Wallet v3

src/multibit_fmt_plug.c
This fixes the performance part in issue https://github.com/magnumripper/JohnTheRipper/issues/2578.
=> MultiBit format: Improve performance by doing delayed decryption

src/opencl/pfx_kernel.cl, src/opencl_pfx_fmt_plug.c, src/pfx_common.h, src/pfx_common_plug.c, src/pfx_fmt_plug.c
The speedup isn't great (6x for GTX TITAN X over 4 cores) but at least it is something :-)
This fixes issue https://github.com/magnumripper/JohnTheRipper/issues/2469.
=> OpenCL support for cracking PFX files

src/ztex/task.c
Used online tool for conflict resolution, introduced error. Corrected it now.
=> error introduced by online conflict resolution - corrected

src/geli_common.h, src/geli_common_plug.c, src/geli_fmt_plug.c, src/opencl_geli_fmt_plug.c
=> OpenCL support for cracking FreeBSD GELI

run/eapmd5tojohn.lua, src/Makefile.in, src/chap_fmt_plug.c, src/eapmd5tojohn.c
http://www.willhackforsushi.com/code/eapmd5pass/1.4/eapmd5pass-1.4.tgz has sample .pcap files.
This PR has `eapmd5tojohn.lua` and also `eapmd5tojohn.c` for handling hash extraction.
=> Add support for EAP-MD5 hashes

src/electrum_fmt_plug.c
This fixes issue https://github.com/magnumripper/JohnTheRipper/issues/2591.
=> Electrum format: remove build hacks and add SIMD

src/opencl_electrum_modern_fmt_plug.c
This is related to https://github.com/magnumripper/JohnTheRipper/issues/2504.
=> OpenCL support for cracking Electrum 2.8+ wallets

src/ztex_bcrypt.c, src/ztex_descrypt.c
Added FMT_TRUNC to flags of *-ztex formats.
=> Added FMT_TRUNC

src/ztex/device_format.c, src/ztex/jtr_device.c, src/ztex/jtr_device.h
=> Оn bad input packet, board correctly removed from operation.

src/keepass2john.c
Also see https://github.com/magnumripper/JohnTheRipper/issues/2502.
=> Warn about unsupported configurations in keepass2john.c

run/office2john.py
This fixes issue https://github.com/magnumripper/JohnTheRipper/issues/2597.
=> Add support for Access 2007 files using CryptoAPI

src/gpg2john.c
=> Fix handling of GPG symmetric encryption without MDC

src/multibit_fmt_plug.c
This fixes https://github.com/magnumripper/JohnTheRipper/issues/2578.
=> Reduce false positives in MultiBit format (take 2)

circle.yml
Update: This should be OK to merge. I was able to test this earlier today.
=> Use Fedora 26 in CircleCI

src/uaf2john.c
Both bugs were found by libFuzzer.
=> Make uaf2john more robust in input handling

src/keepass2john.c
This commit fixes multiple crashes which were found with the help of libFuzzer.
There is still scope for improving the robustness of keepass2john.c further.
I have verified that this change does not cause the output of the program to change, but more testing is welcome!
=> Make keepass2john.c more robust in handling input

src/dmg2john.c
This commit fixes multiple bugs which were found by libFuzzer.
=> Make dmg2john.c more robust in input handling

src/SIPdump.c, src/SIPdump.h
The original code suffered from various correctness problems. It seems that it could even generate broken/partial hashes sometimes.
These bugs were found with libFuzzer.
=> Make SIPdump more robust in handling input

src/eapmd5tojohn.c
This PR fixes multiple bugs found with libFuzzer.
=> Make eapmd5tojohn more robust in input handling

src/Makefile.in, src/Makefile.legacy, src/bitlocker2john.c, src/john.c
I found no problems with bitlocker2john code with this fuzzer 👍
=> Enable fuzzing of bitlocker2john using libFuzzer

src/wpapsk.h
This fixes https://github.com/magnumripper/JohnTheRipper/issues/2635.
This PR depends on "new" OpenSSL functionality, namely `CMAC_Init` and family. I can try to implement this functionality in a native manner.
This works well with https://github.com/magnumripper/JohnTheRipper/pull/2642 too.
=> Add WPA2-PSK-SHA256 (802.11w) support

src/wpapcap2john.c, src/wpapcap2john.h
The primary purpose of this PR is to get feedback for the code. This code probably needs to be rewritten / refactored a lot.
=> Add support for Ethernet link type in wpapcap2john

run/dashlane2john.py, src/dashlane_common.h, src/dashlane_common_plug.c, src/dashlane_fmt_plug.c, src/opencl_dashlane_fmt_plug.c, src/openssl_code.h, src/openssl_code_plug.c, src/openssl_enc_fmt_plug.c
Only data from the Windows and macOS versions of Dashlane is supported currently.
This fixes issue #2658.
=> Add support for Dashlane password manager

src/common-opencl.c
If nobody complains, I will merge.
=> Mute ptxas info (from build log) in default verbosity

run/lastpass2john.py, src/lastpass_cli_fmt_plug.c
This is based on experiments with https://github.com/LastPass/lastpass-cli.
This also fixes issue https://github.com/magnumripper/JohnTheRipper/issues/890.
=> Add support for LastPass CLI

src/lastpass_cli_fmt_plug.c, src/lastpass_fmt_plug.c
Modernize code, and report tunable costs.
=> Few enhancements for the LastPass formats

src/ssh_ng_fmt_plug.c
This should partially fix issue https://github.com/magnumripper/JohnTheRipper/issues/2614.
I am not familiar with the `tunable costs` code in JtR.
=> Report tunable costs for ssh-ng format

src/formats.c, src/sapB_fmt_plug.c, src/secp256k1/Makefile.legacy, src/signals.c
-document some known sapB format hash collisions by adding them to the self tests
-some fixes for legacy builds
=> some sapB tests hashes with known collisions + some make -f Makefile.legacy fixes

run/pgpwde2john.py, src/pgpwde_fmt_plug.c
This fixes issue https://github.com/magnumripper/JohnTheRipper/issues/2473.
The main purpose of this PR is to get early feedback. I am still improving this stuff.
=> Add support for cracking PGP WDE encrypted drives

run/pgpdisk2john.py, src/pgpdisk_fmt_plug.c
This implements #2692.
PGP Disk == PGP Virtual Disk.
=> Add support for cracking PGP Virtual Disk images

src/pgpwde_fmt_plug.c
This should fix https://github.com/magnumripper/JohnTheRipper/issues/2702.
This bug did not have any bad effect in practice.
=> Fix a problem detected by ASan in PGP WDE format

src/common-opencl.c
=> Add the failure code to the error message

src/Makefile.in, src/Makefile.legacy, src/john.c, src/racf2john.c
This commit makes racf2john a standalone program.
Related to https://github.com/magnumripper/JohnTheRipper/issues/2674.
=> Enable fuzzing of racf2john using libFuzzer

src/Makefile.in, src/Makefile.legacy, src/hccap2john.c, src/john.c
This commit make hccap2john a standalone program.
=> Enable fuzzing of hccap2john using libFuzzer

src/opencl/pgpwde_kernel.cl, src/opencl_pgpwde_fmt_plug.c, src/pgpwde_common.h, src/pgpwde_common_plug.c, src/pgpwde_fmt_plug.c
This fixes https://github.com/magnumripper/JohnTheRipper/issues/2694.
=> OpenCL support for PGP WDE format

src/lastpass_cli_common.h, src/lastpass_cli_common_plug.c, src/lastpass_cli_fmt_plug.c, src/lastpass_common.h, src/lastpass_common_plug.c, src/lastpass_fmt_plug.c, src/opencl_lastpass_cli_fmt_plug.c, src/opencl_lastpass_fmt_plug.c
This fixes https://github.com/magnumripper/JohnTheRipper/issues/2671.
=> OpenCL support for LastPass formats

src/Makefile.legacy, src/best.sh
I think a similar change should be in core. As long as this isn't the case, I'd like to have it in bleeding-jumbo.
=> Legacy generic build: Test BF_X2 = 3 if BF_X2 = 1 was faster than BF_X2 = 0

run/pgpsda2john.py, src/pgpsda_common.h, src/pgpsda_common_plug.c, src/pgpsda_fmt_plug.c
=> Add support for cracking PGP SDAs (self-decrypting archives)

src/DMD5_fmt_plug.c
@magnumripper I was working https://github.com/magnumripper/JohnTheRipper/issues/1637 when I discovered https://tools.ietf.org/html/rfc2831#section-8.
I can't crack the test vectors from the RFC with JtR. Can you please take a look?
=> Cleanup DMD5 format a bit

run/luks2john.py
Let's use this PR instead of https://github.com/magnumripper/JohnTheRipper/pull/2732.
=> Make luks2john.py compatible with Python 3 too

src/argon2_fmt_plug.c, src/formats.h
This should fix https://github.com/magnumripper/JohnTheRipper/issues/2740
=> Enhance Argon2 tunable cost reporting

src/rar2john.c
This fixes issue https://github.com/magnumripper/JohnTheRipper/issues/2748.
=> Fix support for RAR 5.x SFX files

src/pdf_fmt_plug.c
=> Relax length_id check in PDF format

src/inc.c
Including:
- allow to set the incremental itself `--min-length=0` using the proper option;
- fix `--incremental` mode combined with `--mask` to produce longer candidates;
- since mask.c changes options.req_minlength and options.req_maxlength, `../run/john -stdout -inc:digits -mask:?w?w?1 -1=ab -max-len=3` produces 22p without specifying `--min-len`.
=> Tweaks to incremental vs. --min/max-length options

src/gpg2john.c
This should fix the main problems which were reported in #2783.
=> Improve error handling in gpg2john

src/gpg2john.c
This fixes https://github.com/magnumripper/JohnTheRipper/issues/2805.
This PR corrects and improves the handling of internal static state of various functions.
=> Fix a regression in gpg2john for multi-key armored ASCII files

.github/issue_template.md, doc/INSTALL-UBUNTU
If nobody complains, I will merge.
=> Minor docs improvement

src/krb5_asrep_fmt_plug.c
This fixes issue https://github.com/magnumripper/JohnTheRipper/issues/2821.
=> Fix reliability problems in KRB5 AS-REP format

src/krb5_db_fmt_plug.c
This is related to issue https://github.com/magnumripper/JohnTheRipper/issues/2824.
These hashes can be generated easily by https://github.com/CroweCybersecurity/echidna project.
=> Add support for cracking etype 17 "native" Kerberos hashes

src/wpapcap2john.c
Reasoning: the "wrap around" behavior in action.
=> Fix for compare that is always false

src/krb5_common_plug.c
After this change, salt length validation needs to be added to the format.
=> Minor speed improvement for krb5-3 format

doc/INSTALL-UBUNTU
=> docs: explicitly state it's about user-local build

src/secp256k1/libsecp256k1-config.h
This fixes https://github.com/magnumripper/JohnTheRipper/issues/2843. Well, it should.
=> Cleanup the bundled libsecp256k1 code a bit

.travis/check.sh
AVX2 builds are failing frequently due to VM issues.
If nobody complains, I will merge.
=> Disable AVX2 for all Travis builds

src/zip2john.c
Update: This fixes issue https://github.com/magnumripper/JohnTheRipper/issues/2418.
=> Fix parsing for WinZip AES encrypted archives

doc/Auditing-Openfire.md, src/xmpp_scram_fmt_plug.c
This was tested with Openfire 4.1.6.
=> Add information about auditing Openfire

doc/README-ZIP, src/securezip_common.h, src/securezip_common_plug.c, src/securezip_fmt_plug.c, src/zip2john.c
This fixes https://github.com/magnumripper/JohnTheRipper/issues/2839.
I have taken some care to test the OpenMP stuff in this format.
=> Add support for PKWARE's SecureZIP

src/bitlocker_fmt_plug.c
Tested on PPC64 Debian 8 VM (emulated using QEMU).
=> Fix endianness issue in BitLocker format

src/leet_cc_fmt_plug.c
This fixes https://github.com/magnumripper/JohnTheRipper/issues/2414 somehow. I don't understand the fix, but it works fine in practice.
=> Fix leet format on BE systems

doc/HACKING.md
The plan is to expand this file with more development, and testing tips in the near future.
=> Notes on testing JtR on big endian systems

src/gpg_common_plug.c
This improves the situation in https://github.com/magnumripper/JohnTheRipper/issues/1892.
=> Reduce false positives for GPG files lacking MDC

src/pomelo_fmt_plug.c, src/pomelo_plug.c
This is related to https://github.com/magnumripper/JohnTheRipper/issues/2868.
=> Disable POMELO on big-endian machines

src/zip2john.c
Changes,
+ Better processing of unknown `extra headers`
+ Separate hashes are generated for each file now
+ Tested with B1 Free Archiver and SecureZIP
This is related to https://github.com/magnumripper/JohnTheRipper/issues/2418 and https://github.com/magnumripper/JohnTheRipper/pull/2856.
@jfoug Does this look OK to you? The related issue has sample archives for testing this.
=> Improve parsing of WinZip style AES encrypted archives

doc/CHANGES, src/AFS_fmt.c, src/BSDI_fmt.c, src/DES_bs.c, src/DES_bs.h, src/DES_fmt.c, src/DES_std.h, src/LM_fmt.c, src/MD5_fmt.c, src/argon2_fmt_plug.c, src/dynamic_fmt.c, src/formats.c, src/opencl_DES_bs_plug.c, src/options.c, src/palshop_fmt_plug.c, src/params.h, src/trip_fmt.c, src/zipmonster_fmt_plug.c
=> Core merge

src/gpg_common_plug.c
This is related to https://github.com/magnumripper/JohnTheRipper/issues/1892.
=> Further reduce false positives for GPG files lacking MDC

src/pomelo_fmt_plug.c
This fixes the problems present in PR https://github.com/magnumripper/JohnTheRipper/pull/2872.
=> Disable POMELO correctly on BE machines

src/pomelo_fmt_plug.c, src/pomelo_plug.c
AVX2, 
```
$ ../run/john --format=pomelo --test
Benchmarking: pomelo [POMELO 128/128 AVX2]... (4xOMP) DONE
Raw:	40554 c/s real, 10265 c/s virtual
```
SSE2, 
```
$ ../run/john --format=pomelo --test
Benchmarking: pomelo [POMELO 128/128 SSE2 1x]... (4xOMP) DONE
Raw:	22968 c/s real, 5837 c/s virtual
```
=> Add AVX2 version of POMELO

src/zip2john.c
The `zip2john.c` file has the following code currently,
```
uint32_t crc = fget32LE(fp);
uint64_t uncompressed_size = fget32LE(fp);
if (IVSize == 0) { // XXX handle endianness
memset(iv, 0, 16);
memcpy(iv, &crc, 4);
memcpy(iv + 4, &uncompressed_size, 8);
IVSize = 12;
}
```
I will try to add a fix for this in this PR soon (update: done now).
[multi-password-archive.zip](https://github.com/magnumripper/JohnTheRipper/files/1464673/multi-password-archive.zip) (sample archive for testing).
[code.zip](https://github.com/magnumripper/JohnTheRipper/files/1464685/code.zip) (more appropriate file for testing the endianness problem).
=> Improve robustness and correctness of zip2john

src/pomelo_fmt_plug.c, src/pomelo_plug.c
This fixes the issues present in PR https://github.com/magnumripper/JohnTheRipper/pull/2878.
=> Assorted fixes for POMELO format

src/formats.c
A wrong command was selected as an else clause statement. Closes #2887 
Will merge as soon as CI gives me an ok.
=> Fix a bug introduced in 38d20bb

src/pomelo_plug.c
size_t is an unsigned integer type.
=> Remove a comparison that is always false

src/config.c
This is related to https://github.com/magnumripper/JohnTheRipper/issues/2868.
=> Fix alignment problem in config.c

src/vms_fmt_plug.c
See https://github.com/magnumripper/JohnTheRipper/issues/2868 for the discussion.
=> Fix alignment problem in OpenVMS format

src/dynamic_fmt.c
=> Fix alignment problem in "dynamic"

src/cryptsha256_fmt_plug.c
=> Fix alignment problem in sha256crypt format

src/ethereum_common.h, src/ethereum_fmt_plug.c
=> Fix alignment problems in ethereum format

src/pkzip_fmt_plug.c
=> Fix alignment problem in pkzip format

src/panama_fmt_plug.c
=> Fix alignment problem in panama format

src/krb5_asrep_common.h, src/krb5_asrep_common_plug.c, src/krb5_asrep_fmt_plug.c
This improves on issue https://github.com/magnumripper/JohnTheRipper/issues/2819.
=> Refactor krb5asrep format to facilitate OpenCL implementation

doc/HACKING.md
This fleshes out the VM setup notes.
=> Improve HACKING notes based on feedback from JimF

run/sspr2john.py, src/sspr_fmt_plug.c
This fixes https://github.com/magnumripper/JohnTheRipper/issues/2875.
I would like to get some early feedback on this PR. Feedback on the output hash format(s) is very welcome.
Sample hashes,
```
CN=lulu,CN=Users,DC=EXAMPLE,DC=NET:$pbkdf2-hmac-sha512$100000.347449354d637a67477258425850705a624f75493338574a5771354e39397451.bacc5a3256f4efcfa88a37f4ffb5835a33700f70df5292986d43640e37dbb37cd2de46c5414c5ee972c103cbd907899b3725a293c981052f5b83f023ef627532:::::What is the name of the main character in your favorite book?
CN=lulu,CN=Users,DC=EXAMPLE,DC=NET:$pbkdf2-hmac-sha512$100000.386d516c466f5846596d4b79374e78335151496346636c594431507578433346.b3e2eaad6c310a425ce932806393f79a1af268fb903e09b787a8a18bca27f8dd2aa27ecaa8a2cf25219d1841396318347020dd7c83ef0a8880eab37bec163bfb:::::What is the name of …
```
=> Add support for cracking NetIQ SSPR hashes

run/7z2john.pl
https://github.com/philsmd/7z2hashcat/commit/9d37dc9edc1
This fixes https://github.com/magnumripper/JohnTheRipper/issues/2889.
=> Treat various values as unsigned integers in 7z2john.pl

src/opencl_ethereum_fmt_plug.c, src/opencl_rawmd5_fmt_plug.c, src/opencl_zip_fmt_plug.c, src/panama_fmt_plug.c
These fixes should be safe.
See https://github.com/magnumripper/JohnTheRipper/issues/2868 and https://github.com/magnumripper/JohnTheRipper/pull/2911 for the discussion.
=> Various fixes for alignment problems

.travis.yml, .travis/check.sh, .travis/test.sh
* I'll add OSX only after/if it can be fixed.
=> Run the encoding test on its own job

src/tacacs_plus_fmt_plug.c
See discussion in https://github.com/magnumripper/JohnTheRipper/pull/2926.
=> Improve scalability in tacacs-plus format

run/pcap2john.py
All credit goes to the `loki` project, and Daniel Mende for this feature.
This is related to https://github.com/magnumripper/JohnTheRipper/issues/2933.
```
$ ../run/pcap2john.py wlccp_auth_and_reassoc_fast.pcap 
Note: This program does not have the functionality of wpapcap2john, SIPdump, eapmd5tojohn, and vncpcap2john.
[DEBUG] WLCCP: EAP-AUTH challenge from authenticator seen for 001121bfb5ff
[DEBUG] WLCCP: EAP-AUTH response from authenticator seen for 001121bfb5ff
[DEBUG] WLCCP: EAP-AUTH challenge from authenticator seen for 000f24747aa2
[DEBUG] WLCCP: EAP-AUTH response from authenticator seen for 000f24747aa2
[DEBUG] WLCCP: EAP-AUTH challenge from authenticator seen for 0007eb30f38c
[DEBUG] WLCCP: EAP-AUTH response from authenticator seen for 0007eb30f38c
[DEBUG] WLCCP: EAP-AUTH …
```
=> Add support for cracking WLCCP LEAP hashes

src/tacacs_plus_fmt_plug.c
See https://github.com/magnumripper/JohnTheRipper/issues/2868 for details.
=> Fix salt alignment in tacacs-plus format

run/iscsi2john.lua
This is related to https://github.com/magnumripper/JohnTheRipper/issues/2933.
=> Add support for extracting iSCSI CHAP hashes

.travis/test.sh
=> Test encoding inside the OSX job

run/radius2john.lua, src/chap_fmt_plug.c
I will either merge or move the `*.lua` files in the next commit.
This is related to https://github.com/magnumripper/JohnTheRipper/issues/2933.
=> Add support for RADIUS CHAP hashes

src/dpapimk_fmt_plug.c
Thanks to Claudio André and Solar Designer for finding these bugs.
This is related to https://github.com/magnumripper/JohnTheRipper/issues/2944.
=> Fix OpenSSL API usage, and hash validation bugs in DPAPImk format

run/pcap2john.py, src/tacacs_plus_fmt_plug.c
We haven't been able to reach Daniel Mende regarding licensing so far.
Let's wait three more days before merging this PR.
=> Assorted fixes for tacacs-plus stuff

src/configure, src/configure.ac, src/m4/jtr_generic_logic.m4, src/m4/jtr_ppc_logic.m4, src/m4/jtr_utility_macros.m4, src/ppc64.h
Adds logic required to build PowerPC64 into the configure script
Should add altivec SIMD also.
=> configure : Add PowerPC64 building

src/configure
It was missing some recent changes (783d27c2faaa135e7e567479bdb7f1b4f480958b).
From now on, any commit/PR will be tested using (from a real run) AVX2 and AVX. It seems to be random.
=> Update the ./configure script

run/pcap2john.py, src/tacacs_plus_fmt_plug.c
Daniel Mende has kindly agreed to re-license his code under our 0-clause BSD license. Thanks Daniel!
This PR reflects this change.
=> Update licensing terms for tacacs-plus stuff

circle.yml
Do not merge this yet. It seems "silent building" is broken somehow?
=> Use Fedora 27 in CircleCI

run/pcap2john.py, src/rsvp_fmt_plug.c
This is related to https://github.com/magnumripper/JohnTheRipper/issues/2933.
[rndc-sample-captures.zip](https://github.com/magnumripper/JohnTheRipper/files/1544489/rndc-sample-captures.zip) <- packet captures for testing purposes.
=> Add support for cracking BIND RNDC hashes

src/DOMINOSEC8_fmt_plug.c
I'm suggesting a code style change to avoid a possible dangling else in the future.
=> Suggestion for code style

src/rsvp_fmt_plug.c
This fixes https://github.com/magnumripper/JohnTheRipper/issues/2988.
=> Fix JtR-TestSuite failure for RSVP format

src/ppc_cpuid.c
=> Fix for unterminated '#if'

src/ppc_cpuid.c
=> Mute warnings in ppc_cpuid

src/wpapsk_fmt_plug.c
Win baby win.  Faster code, simpler (to read) code, works on LE or BE.
=> Port of wpapsk to use proper pbkdf2_hmac-sha1.h file.  Works on BE

src/cryptsha256_fmt_plug.c, src/cryptsha512_fmt_plug.c, src/pseudo_intrinsics.h
Simple fix. Worked fine on PPC ALTIVEC build.
=> non-intel SIMD fixes.   #3009

run/applenotes2john.py, src/notes_common.h, src/notes_common_plug.c, src/notes_fmt_plug.c, src/opencl_notes_fmt_plug.c
This fixes https://github.com/magnumripper/JohnTheRipper/issues/2999.
=> Add support for cracking Apple Notes databases

README.md
Updated the README.md for the current JtR.
=> Update README.md #1972

src/bitlocker2john.c, src/memory.h
I am trying to breakup https://github.com/magnumripper/JohnTheRipper/pull/3006 into manageable parts.
This particular PR adds support for new attack modes in `bitlocker2john.c`. I have tested that it doesn't affect/break the existing functionality.
@e-ago Please review this PR to ensure that I have not missed any of your changes. Thanks!
=> Add support for new BitLocker attack modes

src/openbsdsoftraid_fmt_plug.c
This is related to https://github.com/magnumripper/JohnTheRipper/issues/3001.
=> Minor cleanups for OpenBSD-SoftRAID format

src/Makefile.in, src/memory.h
In order to build one tool, a bug was introduced in all formats.
* if nobody complains, I'm going to merge right away.
=> Partial revert of 551e468

doc/README.BitLocker, src/bitlocker2john.c, src/bitlocker_variable_code.h, src/opencl/bitlocker_kernel.cl, src/opencl_bitlocker_fmt_plug.c
This is a cleaned up version of PR https://github.com/magnumripper/JohnTheRipper/pull/3038.
@e-ago Please review this. Thanks!
=> Various enhancements for BitLocker format

src/hmacSHA512_fmt_plug.c
=> Fix for uninitialized variable

src/bitlocker_common_plug.c, src/dahua_fmt_plug.c, src/fvde_common_plug.c, src/geli_fmt_plug.c, src/itunes_common_plug.c, src/mdc2_fmt_plug.c, src/mozilla_ng_fmt_plug.c, src/mssql12_fmt_plug.c
This is related to https://github.com/magnumripper/JohnTheRipper/issues/3001.
=> Assorted cleanups, part 3

src/ospf_fmt_plug.c, src/putty2john.c, src/sspr_fmt_plug.c
These should be harmless (TM).
=> Some minor cleanups

run/1password2john.py
This is somewhat related to https://github.com/magnumripper/JohnTheRipper/issues/2713.
Special thanks goes to @philsmd for figuring this stuff out.
=> Add support for cracking 1Password for macOS databases

src/opencl_bitlocker_fmt_plug.c
Profiling only kernels and final transfer. On my Tesla K40:
```
time ../run/john --test --format=bitlocker-opencl -v:5
Raw speed figures including buffer transfers:
init: 83.296us, loop: 4096x8.215ms, final: 552.448us, xfer: 2.624us
gws:      1024	     30c/s    31457280 rounds/s   33.652s per crypt_all()!
init: 85.472us, loop: 4096x7.976ms, final: 553.120us, xfer: 2.624us
gws:      2048	     62c/s    65011712 rounds/s   32.673s per crypt_all()!
init: 82.336us, loop: 4096x8.165ms, final: 471.424us, xfer: 2.272us
gws:      4096	    122c/s   127926272 rounds/s   33.445s per crypt_all()+
init: 141.152us, loop: 4096x15.609ms, final: 953.088us, xfer: 2.624us
gws:      8192	    128c/s   134217728 rounds/s   63.938s per crypt_all() - too slow
Calculating best LWS for GWS=4096
Testing LWS=32 …
```
=> BitLocker-Opencl: autotune problem

src/encfs_common_plug.c, src/encfs_fmt_plug.c, src/opencl_encfs_fmt_plug.c
I think that we no longer need the OpenSSL version check in this code.
=> Cleanup EncFS format a bit

src/vtp_fmt_plug.c
There is no functional change, hence this PR should be safe to merge.
=> Cleanup vtp format a bit

src/options.c
@frank-dittrich Is this sufficient?
=> Update copyright year

src/opencl_staroffice_fmt_plug.c, src/staroffice_fmt_plug.c
I will unify the CPU and GPU code in a new pull request.
=> Rename the sxc format to staroffice

src/opencl_staroffice_fmt_plug.c, src/staroffice_common.h, src/staroffice_common_plug.c, src/staroffice_fmt_plug.c
Update:
One problematic area could be the setting of FORMAT_NAME to `StarOffice (.sxc, .sdw, .sxd, .sxw, .sxi)` value.
@magnumripper What do you think about this change?
=> Unify common code for StarOffice format

run/encfs2john.py
I am trying to replace `base64.decodestring` with `base64.b64decode`.
=> Minor cleanups for encfs2john.py utility

src/libreoffice_fmt_plug.c
I don't know how I missed this earlier.
Hopefully, this won't create more work for @frank-dittrich with his ongoing PR.
=> Add attribution text in LibreOffice format

doc/DYNAMIC_COMPILER_FORMATS.md
This information was provided by @KiralyCraft, thanks!
=> Document the process of cracking AuthMe hashes

run/bitwarden2john.py, src/opencl/bitwarden_kernel.cl, src/opencl/fvde_kernel.cl, src/opencl/pbkdf2_hmac_sha256_kernel.cl, src/opencl_bitwarden_fmt_plug.c, src/opencl_pbkdf2_hmac_sha256.h
This doesn't work yet, and I can't spot the problem.
@magnumripper Got any tips? :-) Thanks!
=> Add GPU support for cracking Bitwarden hashes

src/john.c
* Closes #3076;
* More info [here](http://www.openwall.com/lists/john-dev/2018/01/01/1).
=> Enable fallback for CygWin

run/bitshares2john.py, src/bitshares_fmt_plug.c
Notes,
* I will find some time to tune OpenMP scaling tomorrow.
* I will also looking into cracking the backup `.bin` files soon.
=> Add support for cracking BitShares wallets

doc/README.RACF
@bigendiansmalls Please review, thanks!
=> Add documentation for RACF stuff

run/bitshares2john.py, src/bitshares_fmt_plug.c, src/secp256k1/secp256k1.h
This fixes https://github.com/magnumripper/JohnTheRipper/issues/3136.
This was harder than what I imagined ;)
=> Add support for cracking BitShares backup files

src/dmg_fmt_plug.c, src/opencl/dmg_kernel.cl, src/opencl/enpass_kernel.cl, src/opencl/pbkdf2_hmac_sha1_kernel.cl, src/opencl_des.h, src/opencl_dmg_fmt_plug.c, src/opencl_pbkdf2_hmac_sha1.h
WIP for #3129. This works on some devices, crashes on others. Apart from some clean-up needed, I'm sure there's some bugs present.
I think we'll get a really nice speed-up once this works as it should. As in 15x or better... @kholia if you test this, try `-cost=-cost=:,1:1` and `-cost=:,2` for benchmarks.
=> Shared OpenCL DES code, and use it in DMG-OpenCL

run/sshng2john.py, src/ssh_ng_fmt_plug.c
This fixes https://github.com/magnumripper/JohnTheRipper/issues/3157.
=> Add support for AES-192-CBC in SSH-ng format

src/symlink.c
This fixes https://github.com/magnumripper/JohnTheRipper/issues/3166.
=> Enhance symlink resolution feature in MinGW builds

src/net_ah_fmt_plug.c, src/wbb3_fmt_plug.c
See https://github.com/magnumripper/JohnTheRipper/issues/3091 for some background information.
=> Tune MKPC and OMP_SCALE in net-ah format

README.md
Otherwise no-op. I will merge right away.
=> doc: proper case OpenCL acronym

circle.yml
This tries to fix https://github.com/magnumripper/JohnTheRipper/issues/3179.
It can't be as easy as this, right?
=> Start using CircleCI 2.0 platform

doc/README-TACACS+
This fixes https://github.com/magnumripper/JohnTheRipper/issues/3148. Also see https://github.com/magnumripper/JohnTheRipper/pull/2926 for some background information.
=> Document cracking of TACACS+ hashes

run/androidfde2john.py, src/androidfde_fmt_plug.c
=> Cleanup the old Android FDE format a bit

src/opencl_pem_fmt_plug.c, src/pem_common.h, src/pem_common_plug.c, src/pem_fmt_plug.c
This improves https://github.com/magnumripper/JohnTheRipper/pull/3199.
=> Calculate correct key length in PEM-OpenCL format

src/opencl_common.c
Magnum, this is the workaround I used to handle 3191. 
* I was able to make CygWin pretend it is at `/`, as reported (e.g., see it doing `-I /run/kernels`);
* I'm not sure if it should be merged, but since it was useful in one of my tests, throwing it out does not seem appropriate either;
* Please, check if you find it useful. Otherwise, I'll discard it.
E.g:
```
C:\bleeding
|_ run
|_ doc
|_ ...
```
=> OpenCL: add workaround for '-I' on CygWin

src/opencl_pem_fmt_plug.c, src/pem_common.h, src/pem_common_plug.c, src/pem_fmt_plug.c
See https://github.com/magnumripper/JohnTheRipper/pull/3199 for the discussion.
=> Add support for tunable costs in PEM formats

src/opencl_ansible_fmt_plug.c
This fixes https://github.com/magnumripper/JohnTheRipper/issues/3210.
The code was failing to compile without the following changes,
```
int i = 0, j = 0;
```
=> Add OpenCL support for cracking Ansible Vaults

src/opencl/krb5_asrep_kernel.cl, src/opencl_krb5_asrep_aes_fmt_plug.c, src/opencl_misc.h
=> KRB5 AS-REP OpenCL format: Do everything on GPU and drop OMP.

CONTRIBUTING.md
=> docs: add license and code style to guidelines

run/andotp2john.py, src/aes_gcm.h, src/aes_gcm_plug.c, src/andotp_fmt_plug.c
I ran out of time to fix the two `XXX` present in the code. They are on my TODO list.
Update:
This is fixed now.
=> Add support for cracking andOTP backups

run/androidbackup2john.py, src/androidbackup_fmt_plug.c
The commented out code may be useful in the future.
=> Add support for cracking Android Backups

run/aem2john.py, run/andotp2john.py, run/ansible2john.py, run/aruba2john.py, run/bitshares2john.py, run/bitwarden2john.py, run/geli2john.py, run/kwallet2john.py, run/lotus2john.py, run/mcafee_epo2john.py, run/openbsd_softraid2john.py, run/openssl2john.py, run/prosody2john.py, run/sipdump2john.py, run/staroffice2john.py, run/strip2john.py, run/truecrypt2john.py
This has been sitting in my branch for a while.
=> Python PEP 8 and other trivial fixes

src/bestcrypt_fmt_plug.c
I will be using this format as a template soon.
=> Cleanup BestCrypt format a bit

run/network2john.lua, src/radius_fmt_plug.c
Sample .pcap file -> [freeradius.pcap.txt](https://github.com/magnumripper/JohnTheRipper/files/2109074/freeradius.pcap.txt) (from hashcat forums).
Username is "custom2", user password is "Passw0rd2" and the radius secret is "password2".
=> Add support for cracking RADIUS authentication hashes

run/network2john.lua
Cracking DHCPv4 authentication is still to be done.
Sample .pcap files are available at https://github.com/kholia/my-pcaps/tree/master/DHCPv6.
This is related to https://github.com/magnumripper/JohnTheRipper/issues/3275 (Add support for cracking DHCP authentication).
=> Add support for cracking DHCPv6 authentication

run/bitshares2john.py
For some reason, the format auto-detection is failing for the output `$dynamic_84$` hash format.
=> Add support for cracking older BitShares wallets

src/ztex/device.c
Frequency for boards was displayed incorrectly with --test
=> ztex formats with --test fix

run/telegram2john.py
Allows the user to supply a direct path to the map file or a partial directory instead of just the Telegram Desktop directory
=> Improved path detection in telegram2john

run/pse2john.py, src/sap_pse_fmt_plug.c
This is related to https://github.com/magnumripper/JohnTheRipper/issues/3302 (Add support for cracking SAP's PSE files with PBES1-3DES-SHA).
=> Add support for cracking SAP's PSE files

src/androidbackup_fmt_plug.c, src/opencl/pfx_kernel.cl, src/opencl_geli_fmt_plug.c, src/opencl_pbkdf2_hmac_sha512_fmt_plug.c
Bunch of indentation and similar fixes.
=> Some assorted trivial fixes

src/opencl_pfx_fmt_plug.c, src/pfx_common.h, src/pfx_common_plug.c, src/pfx_fmt_plug.c
This PR exposes the `iteration count` value as tunable cost for PFX formats.
=> Add another tunable cost in PFX formats

src/ztex_drupal7.c, src/ztex_sha512crypt.c
=> FMT_TRUNC corrected

run/tezos2john.py, src/opencl/tezos_kernel.cl, src/opencl_tezos_fmt_plug.c, src/tezos_common.h, src/tezos_common_plug.c, src/tezos_fmt_plug.c
This is failing Travis CI testing on macOS + CPU device.
=> Add OpenCL support for cracking Tezos keys

src/ztex/ztex.c, src/ztex/ztex_scan.c
After firmware is uploaded on such board, it reappear with standard hexadecimal SN
=> firmware upload on ztex board with user-defined SN

doc/README-ZTEX, src/ztex/fpga-sha512crypt/README.md
Updated:
docs/README-ZTEX
src/ztex/fpga-sha512crypt/README.md
=> docs update

.circle/Dockerfile, circle.yml, src/dynamic_fmt.c, src/krb5pa-sha1_fmt_plug.c, src/truecrypt_fmt_plug.c
This PR ensure that we use the latest MinGW toolchain to build and test JtR Jumbo.
=> Use Fedora Rawhide in CircleCI

doc/DYNAMIC_COMPILER_FORMATS.md
This fixes https://github.com/magnumripper/JohnTheRipper/issues/3285 (Add support for cracking ZooKeeper hashes).
=> Add a note on cracking ZooKeeper hashes

src/opencl_wpapmk_fmt_plug.c, src/opencl_wpapsk_fmt_plug.c, src/wpapcap2john.c, src/wpapcap2john.h, src/wpapmk_fmt_plug.c, src/wpapsk.h, src/wpapsk_fmt_plug.c
=> wpapcap2john: Add support for getting PMKID hashes.  Closes #3364.

src/john.c
=> maint: refuse --device if the format is not device-aware

run/adxcsouf2john.py, src/adxcrypt_fmt_plug.c
Note: I will be tuning the format properly soon.
Update: Done now.
=> Add support for cracking IBM 4690 ADXCRYPT hashes

src/cloudkeychain_common.h, src/cloudkeychain_common_plug.c, src/cloudkeychain_fmt_plug.c, src/opencl/cloudkeychain_kernel.cl, src/opencl_cloudkeychain_fmt_plug.c
This fixes https://github.com/magnumripper/JohnTheRipper/issues/3413.
=> Add OpenCL support for cracking 1Password Cloud Keychains

.github/issue_template.md
This change was requested in https://github.com/magnumripper/JohnTheRipper/issues/3441.
=> Fix up our issue template language

src/opencl_agilekeychain_fmt_plug.c, src/opencl_blockchain_fmt_plug.c, src/opencl_enpass_fmt_plug.c, src/opencl_keychain_fmt_plug.c, src/opencl_keyring_fmt_plug.c, src/opencl_rar5_fmt_plug.c, src/opencl_sha1crypt_fmt_plug.c, src/opencl_strip_fmt_plug.c, src/opencl_tc_fmt_plug.c, src/opencl_wpapmk_fmt_plug.c, src/opencl_wpapsk_fmt_plug.c, src/opencl_zip_fmt_plug.c
=> Fix comment styling a bit

run/ml2john.py
On a related note, isn't the name `ml2john.py` a little obscure? Should we rename it to something else? Perhaps `mac2john.py`?
Suggestions are welcome!
=> Support Python 3 in ml2john.py utility

run/john.conf, src/cracker.c, src/params.h
=> cracker.c: Warn about too few candidate passwords. See #3386

run/dynamic.conf
I don't know much about this format.
=> Add support for QAS vas_auth

doc/INSTALL-UBUNTU, src/opencl_rawsha256_fmt_plug.c, src/opencl_rawsha512_gpl_fmt_plug.c, src/opencl_sha256crypt_fmt_plug.c, src/opencl_sha512crypt_fmt_plug.c
Basically, set GWS to next LWS multiple larger than count for "my" formats.
Closes #3495
=> Assorted fixes

run/mac2john-alt.py
This fixes issue https://github.com/magnumripper/JohnTheRipper/issues/3496 (Add the machash.py script).
=> Add an alternate implementation of mac2john.py script

src/john.c, src/opencl_bf_fmt_plug.c, src/opencl_common.c, src/opencl_common.h, src/opencl_mscash2_fmt_plug.c, src/options.c
=> Sort OpenCL devices

src/opencl_rawsha256_fmt_plug.c, src/opencl_rawsha512_gpl_fmt_plug.c
=> OpenCL: self test using sane GWS and LWS

src/john.c
=> fuzz: suppress collision warnings

src/opencl/sha256_kernel.cl, src/opencl/sha512_gpl_kernel.cl
=> Comment about rawSHA256/512 rounds reversing

run/ccache2john.py, run/kirbi2john.py
This fixes https://github.com/magnumripper/JohnTheRipper/issues/3526 and https://github.com/magnumripper/JohnTheRipper/issues/3524.
=> [MAINT] Fix an informational message regarding KRB stuff

src/unused/dynamic_big_crypt.c
=> updated the unused pre-built version of this file to its proper state

src/diskcryptor_common.h
This might fix https://github.com/magnumripper/JohnTheRipper/issues/3542 and address https://github.com/magnumripper/JohnTheRipper/pull/3540 as well.
=> Fix structure packing in DiskCryptor stuff

run/pem2john.py
Demo Key: https://github.com/chipx0r/crackpkcs8/blob/master/AAA010101AAA.key
Pass: 12345678a
My CA gives us DER encoded certificates and I saw the chance to modify your program, in the reading part to be able to use it. I'm not an expert in python, but it worked.
=> PKCS#8 DER Compatibility

src/diskcryptor_common_plug.c
This fixes https://github.com/magnumripper/JohnTheRipper/issues/3569.
=> Make DiskCryptor format functional on BE machines

src/misc.c
#3574
Both functions would (usually) skip the next line, if there was a NULL byte in the current line.
fgetll returned the wrong pointer if there was a NULL in the line (on long lines). Looks like a cut/paste bug from the code handling nulls prior to the section to handle long lines.
=> fgetl and fgetll lines with NULLs.  fgetll memory leak

src/opencl/cryptsha512_kernel_GPU.cl, src/opencl_sha256crypt_fmt_plug.c, src/opencl_sha512crypt_fmt_plug.c
Although the AMD driver is going slightly mad, a workaround is feasible. Tasks:
* Fix sha512crypt for Radeon RX Vega
* Tune for GTX 1080
=> Fix sha512crypt for new hardware/software on super

run/john.conf, src/john.c, src/logger.c, src/unicode.c
=> Uncommented params from john.conf Options section.

run/radius2john.py
Hi,
I found myself in a situation where I needed to use the radius2john perl script, but had some trouble making it work (mostly because I have no knowledge of perl whatsoever). 
So I wrote a new script in python to achieve my goal and I wanted to share it with you guys.
I'm open to suggestion on whether or not I need to modify my code.
Thanks!
=> Add radius2john python script

src/hccap2john.c
Minor output changes in uid/gid/gecos fields.
=> Unify hccap2john output format with wpapcap2john

src/opencl_common.c
- avoid a buffer overrun;
- improve source code documentation.
=> Refactor opencl_load_environment()

src/bench.c, src/gpu_common.c, src/gpu_common.h, src/john.c, src/opencl_common.c, src/opencl_mscash2_fmt_plug.c, src/opencl_mscash2_helper_plug.c, src/status.c
- avoid a buffer overrun (it is '-1' terminated);
- rename; the previous name was confusing.
=> Refactor the gpu_device_list[] variable

src/bench.c, src/gpu_common.c, src/gpu_common.h, src/john.c, src/opencl_common.c, src/status.c
=> More refactoring

src/opencl_common.c
=> Use base1 --device

src/Makefile.in
You guys are complaining about moving unit-tests to 'make check'. But that is an easy task. 
* Rethink how JtR should run unit-tests is another issue and can be done later. E.g., in #3566.
=> Move the unit tests into make check

src/misc.c, src/misc.h, src/opencl_common.c
It seems to me that `trim()` functions do a better job.
=> Remove isspace() in common_opencl

src/tests/unit-tests.c
TDD
```
**** Performing unit tests for functions from [misc.c] ****
[...]
test 16 test_jtr_lltoa          -  Performed  8400420 tests 0.91 seconds used
test 17 test_jtr_ulltoa         -  Performed  8400420 tests 1.49 seconds used
test 18 test_trim               -  Performed    22736 tests 0.01 seconds used
[...]
**** Performing unit tests for functions from [sha2.c] ****
test 34 test_sha224             -  Performed      129 tests 0.09 seconds used
test 35 test_sha256             -  Performed      780 tests 0.14 seconds used
test 36 test_sha384             -  Performed      908 tests 0.21 seconds used
test 37 test_sha512             -  Performed      908 tests 0.21 seconds used
Performed testing on 37 total functions.
Total time taken : 7.94
```
=> Add unit-tests for trim() functions

src/opencl_common.c, src/opencl_common.h
=> OpenCL: add const qualifier

src/opencl_autotune.c, src/opencl_common.c
=> OpenCL auto-tune tweaks. Add backward GWS runs.

src/mask.c, src/opencl_common.c
=> Change auto-tune/mask-test password length to 7

src/opencl_common.c
=> OpenCL: fix the device name not printed

doc/INSTALL-WINDOWS
* We can add some notes about how to build on Windows;
* Unfortunately, nobody here uses Windows;
* So, this is a shot in the dark. Nobody can test it;
Anyway, this is up to you guys to see if it can be valuable.
In general, it is correct (I copied from a CI recipe).
=> Add a recipe on how to build on Windows

src/configure, src/m4/jtr_x86_logic.m4
This fixed all issues on my SSE2-only i686 laptop from stone age.
=> AC: Fix intel 32-bit issues. Closes, I hope, #3678

src/Makefile.in
=> Make the windows target the default when running on Windows

src/loader.c
https://www.openwall.com/lists/john-dev/2019/04/07/1
=> Tweaks to ldr_split_line per discussion at john-dev ml

src/BFEgg_fmt_plug.c, src/DOMINOSEC8_fmt_plug.c, src/DOMINOSEC_fmt_plug.c, src/NETNTLMv2_fmt_plug.c, src/SybasePROP_fmt_plug.c, src/agilekeychain_fmt_plug.c, src/aix_ssha_fmt_plug.c, src/bitlocker_fmt_plug.c, src/vmx_fmt_plug.c, src/wow_srp_fmt_plug.c
=> OMP tune, a bunch of formats. See #3091

src/ztex/Makefile.in
=> src/ztex/Makefile.in: added distclean target

src/opencl/cryptmd5_kernel.cl
This speeds up the check when LWS is greater than 64 _and_ it avoids unnecessary disabling of length specialization when there are different length passwords somewhere within the local group, but not in the immediate group of 64.
=> md5crypt-opencl: only detect divergence in 64 lid's near current

src/opencl_common.c, src/opencl_rawsha512_fmt_plug.c, src/opencl_xsha512_fmt_plug.c
Triggered by https://github.com/magnumripper/JohnTheRipper/issues/3779#issuecomment-481474190
=> Add cmp_all() to auto-tune.

src/opencl_axcrypt2_fmt_plug.c, src/opencl_axcrypt_fmt_plug.c, src/opencl_cloudkeychain_fmt_plug.c, src/opencl_diskcryptor_aes_fmt_plug.c, src/opencl_diskcryptor_fmt_plug.c, src/opencl_sappse_fmt_plug.c, src/opencl_ssh_fmt_plug.c, src/opencl_tezos_fmt_plug.c
=> Fix the last few OpenCL formats that didn't set GWS to next LWS multiple

run/john.conf, src/opencl_common.c, src/pp.c, src/subsets.c
=> Un-comment a number of config options, so they're seen with --list

src/configure, src/configure.ac, src/yescrypt/yescrypt-opt.c
=> yescrypt warnings botcheck

src/fuzz.c
=> fuzz: add const qualifier to fuzzing

src/opencl_rawsha512_gpl_fmt_plug.c
See recent cracking contest discussion.
=> OpenCL: rawSHA512 force auto-tuning

run/john.conf, src/gpu_common.c, src/gpu_common.h, src/opencl_common.c
See #3831. Review is easier if you ignore spaces.
BTW: Bonaire looks malfunctioning (I see nobody there).
```
Adapter 2 - AMD Radeon HD 7700 Series
Core (MHz)    Memory (MHz)
Current Clocks :    0           0
Current Peak :    1075           1600
Configurable Peak Range : [300-1200]     [150-1600]
GPU load :    100%
```
=> Handle GPU overheating gracefully

src/bench.c, src/john.c, src/mask.c, src/mask.h, src/sha512crypt_common.h
=> sha512common.h fix

src/gpu_common.c
```
Press 'q' or Ctrl-C to abort, almost any other key for status
1 0g 0:00:00:00  (3) 0g/s 0p/s 0c/s 0C/s Dev#1:65C
Device 1 overheat (70C, fan 100%), sleeping.
Device 1 overheat (70C, fan 100%), sleeping.
Device 1 is waking up (51C, fan 100%).
Device 1 is waking up (51C, fan 100%).
Device 1 overheat (64C, fan 100%), sleeping.
Device 1 overheat (64C, fan 100%), sleeping.
Device 1 is waking up (49C, fan 100%).
Device 1 is waking up (49C, fan 100%).
Device 1 overheat (64C, fan 100%), sleeping.
Device 1 overheat (63C, fan 100%), sleeping.
Device 1 is waking up (52C, fan 100%).
Device 1 is waking up (52C, fan 100%).
1 0g 0:00:01:42  (3) 0g/s 0p/s 3854c/s 3854C/s Dev#1:52C a..#ec
2 0g 0:00:01:42  (3) 0g/s 0p/s 3853c/s 3853C/s Dev#1:52C ...dB 
Waiting for 1 child to terminate
Session aborted …
```
=> Print a message when a GPU wakes up from overheating

src/ztex_sha256crypt.c
=> ztex: fix an overflow in sha256crypt

src/rules.c
=> fix buffer overflow in HC rule p (duplicate word N times) cutting length

src/radius_fmt_plug.c
radius: just output some recovered passwords when we can, and don't benchmark "cracking" of directly recoverable passwords. Fixes #3809.
=> radius: just output some recovered passwords when we can

src/opencl_krb5pa-md5_fmt_plug.c, src/opencl_mscash_fmt_plug.c, src/opencl_mysqlsha1_fmt_plug.c, src/opencl_ntlmv2_fmt_plug.c, src/opencl_rawsha1_fmt_plug.c, src/opencl_salted_sha_fmt_plug.c, src/opencl_sl3_fmt_plug.c
=> hash_ids uninitialized allocation

src/aix_smd5_fmt_plug.c
This is in preparation for #3872.
=> aix-smd5: Trivial optimizations

README.md
This is a reminder to (do something)
=> Change or remove the link for the Windows Build

src/configure, src/m4/jtr_x86_logic.m4
=> Fix AVX512BW detection

doc/MASK
I reuse my john-users posting for this. Ideally, we should also revise the preceding text, but I have no time.
=> [skip ci] Add usage examples to doc/MASK

src/rawMD4_fmt_plug.c, src/rawMD5_fmt_plug.c
=> Re-unify raw-md4 and raw_md5 formats, fixing bugs in the former.

src/bench.c
=> Don't report virtual c/s if virtual time didn't advance

src/john.c, src/md5crypt_long_fmt.c
Sorry I couldn't resist. ;-) In my testing, this is +16% for length 7, +7% for length 24, +13% for length 47 on super.
=> md5crypt-long optimizations

src/blake2-impl.h, src/blake2.h
=> Fix non-SIMD blake2 aliasing violations leading to failures. Closes #3079

src/Makefile.in, src/configure, src/configure.ac
#3939 will be no longer automatically merge-able.
=> autotools: remove references of HT

src/Makefile.in, src/Makefile.legacy, src/params.h
Merge this (rebase) when all else is fine (and after #3931 / #1911). Then tag whatever commit-hash this produced, as `john-1.9.0-Jumbo-1`. And `git push --tags origin`.
=> Define RELEASE_BUILD

.circleci/config.yml
=> CI: add more tests

src/Makefile.legacy, src/params.h
This takes us back to bleeding Jumbo.
=> MERGE THIS FIRST - Back to the Future, a.k.a. drop the release macros.

src/listconf.c, src/misc.c, src/misc.h, src/timer.c, src/timer.h
… that decreased resolution significantly under macOS. Also add some diagnostics to --list=build-info.
Closes #3949.
=> Fix a "bug" in Jim's portable hi-res timer code

src/opencl_oldoffice_fmt_plug.c
Add the salt_compare from CPU format while at it.  Closes #3957.
=> oldoffice-opencl: Fix bug introduced with 7078470.

src/Makefile.in, src/symlink.c
=> On Windows, use symlink.c to pick the best SIMD

src/configure, src/configure.ac, src/listconf.c, src/timer.h
=> timer.h: Use CLOCK_MONOTONIC_RAW if available.

src/ztex/ztex.c
=> Correct some calls of ztex_error()

appveyor.yml
* Nothing will happen after the PR got merged.
* This is a stripped version (since AppVeyor run sequential builds, you have to decide which tests run).
- no fallback;
=> Add AppVeyor yaml file (do not merge)

run/atmail2john.pl
=> Add atmail2john.pl
